/**
 * Card aggregations, ported from depictio's server-side reductions so a value
 * previewed here and the same card rendered in depictio cannot disagree.
 *
 * Sources of truth:
 *   `_agg_value` / `_agg_expr` / `_coerce_agg_result`
 *      — depictio/api/v1/endpoints/dashboards_endpoints/routes.py
 *   `_POLARS_AGG_EXPRS` (the precomputed specs a card reads unfiltered)
 *      — depictio/api/v1/endpoints/deltatables_endpoints/utils.py
 *
 * The details that a naive reimplementation gets wrong, and that
 * `src/test/cardMetrics.test.ts` pins against payloads generated by the Python:
 *   - `variance` / `std_dev` are the SAMPLE statistics (ddof=1), not population;
 *   - `skewness` / `kurtosis` are the bias-corrected (scipy) estimators, and
 *     are null below 3 and 4 observations respectively;
 *   - `percentile` is the linear-interpolated median, not a configurable one;
 *   - `mode` is the SMALLEST of the tied most-frequent values, because that is
 *     what `drop_nulls().mode().min()` records in the specs;
 *   - `count` and `nunique` ignore nulls, and an empty CSV cell is a null.
 */
import type { FrameColumn, StudioFrame } from './frame';
import { isNumericKind, numericValues } from './frame';

/** Tukey five-number summary + outliers, the payload the `box_plot` strip reads. */
export interface BoxPlotStats {
  min: number;
  max: number;
  q1: number;
  q3: number;
  median: number;
  mean: number;
  lower_whisker: number;
  upper_whisker: number;
  outliers: number[];
  outlier_count: number;
}

export type AggResult = number | string | BoxPlotStats | null;

/** Linear-interpolated quantile — polars' `quantile(q, interpolation='linear')`
 *  and numpy's default, so q1/q3/median match the server exactly. */
export function quantileLinear(sorted: number[], q: number): number | null {
  const n = sorted.length;
  if (n === 0) return null;
  if (n === 1) return sorted[0];
  const pos = q * (n - 1);
  const lo = Math.floor(pos);
  const hi = Math.ceil(pos);
  if (lo === hi) return sorted[lo];
  return sorted[lo] + (sorted[hi] - sorted[lo]) * (pos - lo);
}

/** Population central moment of order `k` — the building block scipy's
 *  bias-corrected skew/kurtosis are expressed in. */
function centralMoment(values: number[], mean: number, k: number): number {
  let total = 0;
  for (const v of values) total += (v - mean) ** k;
  return total / values.length;
}

function sampleVariance(values: number[]): number | null {
  const n = values.length;
  if (n < 2) return null;
  const mean = values.reduce((a, b) => a + b, 0) / n;
  let total = 0;
  for (const v of values) total += (v - mean) ** 2;
  return total / (n - 1);
}

/** scipy/polars `skew(bias=False)`. Null below 3 points, where the correction
 *  divides by zero and pandas historically returned NaN. */
function skewness(values: number[]): number | null {
  const n = values.length;
  if (n < 3) return null;
  const mean = values.reduce((a, b) => a + b, 0) / n;
  const m2 = centralMoment(values, mean, 2);
  if (m2 === 0) return null;
  const m3 = centralMoment(values, mean, 3);
  return (Math.sqrt((n - 1) * n) / (n - 2)) * (m3 / m2 ** 1.5);
}

/** scipy/polars `kurtosis(bias=False)` — Fisher (excess) definition. */
function kurtosis(values: number[]): number | null {
  const n = values.length;
  if (n < 4) return null;
  const mean = values.reduce((a, b) => a + b, 0) / n;
  const m2 = centralMoment(values, mean, 2);
  if (m2 === 0) return null;
  const m4 = centralMoment(values, mean, 4);
  return (1 / ((n - 2) * (n - 3))) * ((n ** 2 - 1) * (m4 / m2 ** 2) - 3 * (n - 1) ** 2);
}

export function boxPlotStats(values: number[]): BoxPlotStats | null {
  if (values.length === 0) return null;
  const sorted = [...values].sort((a, b) => a - b);
  const min = sorted[0];
  const max = sorted[sorted.length - 1];
  const q1 = quantileLinear(sorted, 0.25) as number;
  const q3 = quantileLinear(sorted, 0.75) as number;
  const median = quantileLinear(sorted, 0.5) as number;
  const mean = sorted.reduce((a, b) => a + b, 0) / sorted.length;
  const iqr = q3 - q1;
  const fenceLo = q1 - 1.5 * iqr;
  const fenceHi = q3 + 1.5 * iqr;
  const within = sorted.filter((v) => v >= fenceLo && v <= fenceHi);
  const outlierValues = values.filter((v) => v < fenceLo || v > fenceHi);
  return {
    min,
    max,
    q1,
    q3,
    median,
    mean,
    lower_whisker: within.length ? within[0] : min,
    upper_whisker: within.length ? within[within.length - 1] : max,
    // Capped at 100 like the server: past that the dots merge into a bar.
    outliers: outlierValues.length ? outlierValues.slice(0, 100) : [],
    outlier_count: outlierValues.length,
  };
}

/** Smallest of the most-frequent non-null values, matching the specs'
 *  `drop_nulls().mode().min()`. Ties are broken numerically on a numeric
 *  column and lexically otherwise, exactly as polars compares them. */
function modeValue(col: FrameColumn): number | string | null {
  const freq = new Map<string | number | boolean, number>();
  for (const v of col.present) freq.set(v!, (freq.get(v!) ?? 0) + 1);
  if (freq.size === 0) return null;
  let bestCount = -1;
  let best: string | number | boolean | null = null;
  for (const [value, count] of freq) {
    if (count > bestCount) {
      bestCount = count;
      best = value;
    } else if (count === bestCount && best !== null) {
      const lower =
        typeof value === 'number' && typeof best === 'number'
          ? value < best
          : String(value) < String(best);
      if (lower) best = value;
    }
  }
  if (best === null) return null;
  return typeof best === 'number' ? best : String(best);
}

/**
 * One aggregation over one column. Returns `null` — never NaN and never a
 * placeholder string — when the reduction has no answer, so callers render no
 * value rather than a fabricated one.
 */
export function aggregate(
  frame: StudioFrame,
  column: string,
  aggregation: string,
): AggResult {
  const col = frame.byName.get(column);
  if (!col) return null;
  const agg = (aggregation || '').toLowerCase();

  // Work on any dtype.
  if (agg === 'count') return col.present.length;
  if (agg === 'nunique' || agg === 'unique') return new Set(col.present).size;
  if (agg === 'mode') return modeValue(col);

  const numeric = isNumericKind(col.kind);
  if (agg === 'min' || agg === 'max') {
    if (col.present.length === 0) return null;
    if (!numeric) {
      const strings = col.present.map(String).sort();
      return agg === 'min' ? strings[0] : strings[strings.length - 1];
    }
    const nums = numericValues(col);
    return agg === 'min' ? Math.min(...nums) : Math.max(...nums);
  }

  const nums = numericValues(col);
  if (nums.length === 0) return null;
  const sorted = [...nums].sort((a, b) => a - b);

  switch (agg) {
    case 'sum':
      return nums.reduce((a, b) => a + b, 0);
    case 'average':
    case 'mean':
      return nums.reduce((a, b) => a + b, 0) / nums.length;
    case 'median':
      return quantileLinear(sorted, 0.5);
    case 'range':
      return sorted[sorted.length - 1] - sorted[0];
    case 'variance':
    case 'var':
      return sampleVariance(nums);
    case 'std_dev':
    case 'std': {
      const variance = sampleVariance(nums);
      return variance === null ? null : Math.sqrt(variance);
    }
    case 'q1':
      return quantileLinear(sorted, 0.25);
    case 'q3':
      return quantileLinear(sorted, 0.75);
    // The precompute table maps `percentile` to `quantile`, whose expression is
    // fixed at 0.5 — a "percentile" card shows the median.
    case 'percentile':
      return quantileLinear(sorted, 0.5);
    case 'skewness':
      return skewness(nums);
    case 'kurtosis':
      return kurtosis(nums);
    case 'box_plot_stats':
      return boxPlotStats(nums);
    default:
      return null;
  }
}
