import type { WalkthroughDefinition } from '../types';

/** Authenticated / builder walkthrough — runs once for any logged-in user
 *  (single- or multi-user mode). Goal: walk them through the full pipeline
 *  *projects → dashboards → editor → component → save*, so they understand
 *  data has to live somewhere before a dashboard can render it. */
export const authBuilderWalkthrough: WalkthroughDefinition = {
  id: 'builder',
  // v4 — bumped after expanding the component-build phase (recommend a type,
  // configure data + design, then layout/resize before saving the dashboard).
  version: 'v4',
  label: 'Take the builder tour',
  steps: [
    {
      id: 'welcome',
      target: null,
      title: 'Welcome to Depictio',
      body: "👋 Your reads are processed, your dataframes are clean — now let's make them clickable. We start with a project — that's where the data lives.",
      position: 'bottom',
      image: {
        src: '/dashboard/favicon.svg',
        alt: 'Depictio',
        height: 64,
      },
      navigateTo: '/projects',
    },
    {
      id: 'projects-page',
      target: 'projects-header',
      route: /^\/projects\/?$/,
      title: 'Projects bundle your data',
      body: "A project groups the data collections your dashboards read from, the permissions controlling who sees them, and optionally one or more workflows that produced the data.",
      position: 'bottom',
    },
    {
      id: 'projects-create',
      target: 'projects-create',
      route: /^\/projects\/?$/,
      title: 'Create your first project',
      body: "Click here to spin up a new project. You'll pick a name and attach the data collections it should hold — without data, a project doesn't do much. The tour resumes once you land on the project page.",
      position: 'left',
      awaitClick: true,
    },
    {
      id: 'project-detail',
      target: null,
      route: /^\/projects\/[^/]+\/?$/,
      title: 'Inside a project',
      body: "Here you can browse this project's data collections and the workflow runs that fed them. Permissions live on a separate page. Next we'll head to the Dashboards page and start visualizing this data.",
      position: 'bottom',
      navigateTo: '/dashboards',
    },
    {
      id: 'dashboards-page',
      target: null,
      route: /^\/dashboards\/?$/,
      title: 'Dashboards live here',
      body: "A dashboard is a layout of components that read from a project's data. Each dashboard can have multiple tabs and multiple components — figures, cards, tables, interactive filters, MultiQC plots, and geomaps.",
      position: 'bottom',
    },
    {
      id: 'dashboards-create',
      target: 'dashboards-create',
      route: /^\/dashboards\/?$/,
      title: 'Create a dashboard',
      body: "Click here to start a new dashboard. Pick the project you just made — the new dashboard will show up in the list, and the tour resumes once you open it.",
      position: 'left',
      awaitClick: true,
    },
    {
      id: 'enter-edit-mode',
      target: 'enter-edit-mode',
      route: /^\/dashboard\/[^/]+/,
      title: 'Open the editor',
      body: 'Your new dashboard opens in view mode. Click Edit to drop into the editor — that\'s where you add components.',
      position: 'bottom',
      awaitClick: true,
    },
    {
      id: 'editor-add',
      target: 'editor-add-component',
      route: /^\/dashboard-edit\//,
      title: 'Add your first component',
      body: 'A dashboard is built from components. Click "Add component" to open the builder.',
      position: 'bottom',
      awaitClick: true,
    },
    {
      id: 'component-type',
      target: 'component-type-grid',
      route: /\/component\/(add|edit)\//,
      title: 'Pick a Figure to start with',
      body: "For this tour, pick **Figure** — it's the most flexible component and great for getting a feel for the builder. (You can come back later and try cards, tables, interactive filters, MultiQC plots, or geomaps.)",
      position: 'bottom',
      awaitClick: true,
    },
    {
      id: 'component-configure',
      target: 'component-wizard-stepper',
      route: /\/component\/(add|edit)\//,
      title: 'Configure your component',
      body: 'Walk through the wizard: **Data Source** picks the workflow and data collection, then **Design** chooses the chart type and axes. Use Next on each stage to advance.',
      position: 'bottom',
    },
    {
      id: 'component-save',
      target: 'component-save',
      route: /\/component\/(add|edit)\//,
      title: 'Save the component',
      body: 'Design configured? Hit save. The wizard closes and your new component lands on the dashboard grid.',
      position: 'top',
      awaitClick: true,
    },
    {
      id: 'component-resize',
      target: 'editor-grid',
      route: /^\/dashboard-edit\//,
      title: 'Arrange and resize',
      body: 'Drag your component from dedicated button to move it. Drag the bottom-right corner to resize. Add a few more components and lay them out however you like.',
      position: 'left',
    },
    {
      id: 'editor-save',
      target: 'editor-save',
      route: /^\/dashboard-edit\//,
      title: 'Save the dashboard',
      body: 'Components are added on the dashboard, but the layout itself needs an explicit save. Hit Save to persist updated layout.',
      position: 'bottom',
    },
    {
      id: 'done',
      target: null,
      title: "You're a builder now",
      body: 'You can re-launch this tour any time from the user menu. Add more components, share the dashboard with your team, or duplicate it as a starting point.',
      position: 'bottom',
    },
  ],
};
