"""Hand a local server over to Docker Compose (`depictio local export-compose`).

The MongoDB and SeaweedFS data and the token signing keys are copied into a
directory, with the docker-compose.yaml that matches the running version, a .env
holding the local server's credentials, and an override that runs the same
MongoDB and SeaweedFS versions on the copied data.
"""

from __future__ import annotations

import json
import os
import re
import shutil
import sys
import urllib.request
from pathlib import Path

from depictio.cli.cli.local_stack import (
    ADMIN_EMAIL,
    S3_BUCKET,
    S3_USER,
    LocalStackError,
    Paths,
    load_secrets,
    package_root,
    running_status,
    stop_all,
    write_private_file,
)
from depictio.cli.cli.utils.telemetry import cli_version

# The compose file a release's images were built with.
COMPOSE_URL = "https://raw.githubusercontent.com/depictio/depictio/v{version}/docker-compose.yaml"
# Data carried over. Redis holds only cache and queue, and thumbnails are re-rendered.
EXPORTED_DIRS = ("mongo", "s3")
KEY_FILES = ("private_key.pem", "public_key.pem", "api_internal_key.pem")


def release_version() -> str | None:
    """The installed version as release tags spell it, or None for a dev build.

    That is the git tag without its ``v`` and the image tag: ``1.2.3``, or
    ``1.2.3-b1`` for a beta, whose package version is ``1.2.3b1``. Read from the
    package metadata, since the CLI-only package (depictio-cli) does not ship
    depictio.version.
    """
    match = re.fullmatch(r"(\d+\.\d+\.\d+)(?:-?b(\d+))?", cli_version())
    if match is None:
        return None
    release, beta = match.groups()
    return f"{release}-b{beta}" if beta else release


def installed_version(paths: Paths, package: str) -> str:
    """Version of a conda-forge package in ``<home>/env``, read from its conda-meta record."""
    for record in (paths.env / "conda-meta").glob(f"{package}-*.json"):
        meta = json.loads(record.read_text())
        if meta.get("name") == package:
            return meta["version"]
    raise LocalStackError(
        f"{package} is not installed under {paths.env}; run `depictio local up` once"
    )


def compose_override(mongo_version: str, seaweedfs_version: str, user: str | None) -> str:
    """The override that points the stock docker-compose.yaml at the exported data.

    Mongo and SeaweedFS run the exact versions the local server wrote the data
    with. Paths are relative to the export directory, so it can be moved. The key
    files are mounted one by one over the keys volume: the API also writes a lock
    file next to them, which a bind-mounted directory owned by the host user would
    refuse to the image's own user.
    """
    run_as = f'    user: "{user}"\n' if user else ""
    keys = "".join(
        f"      - ./data/keys/{name}:/app/depictio/keys/{name}:ro\n" for name in KEY_FILES
    )
    return (
        "# Generated by `depictio local export-compose`: the Docker stack on the data\n"
        "# of a local server. docker compose reads it next to docker-compose.yaml.\n"
        "services:\n"
        "  mongo:\n"
        f"    image: mongo:{mongo_version}\n"
        f"{run_as}"
        "    volumes:\n"
        "      - ./data/mongo:/data/db\n"
        "  s3:\n"
        f"    image: chrislusf/seaweedfs:{seaweedfs_version}\n"
        f"{run_as}"
        "    volumes:\n"
        "      - ./data/s3:/data\n"
        "  depictio-backend:\n"
        "    volumes:\n"
        f"{keys}"
        "  depictio-celery-worker:\n"
        "    volumes:\n"
        f"{keys}"
    )


def compose_env(secret_values: dict, version: str | None) -> str:
    lines = [
        "# Generated by `depictio local export-compose`: the local server's credentials.",
        "DEPICTIO_AUTH_SINGLE_USER_MODE=true",
        f"DEPICTIO_S3_ROOT_USER={S3_USER}",
        f"DEPICTIO_S3_ROOT_PASSWORD={secret_values['s3_password']}",
        f"DEPICTIO_S3_BUCKET={S3_BUCKET}",
        f"DEPICTIO_BOOTSTRAP_ADMIN_EMAIL={ADMIN_EMAIL}",
        f"DEPICTIO_BOOTSTRAP_ADMIN_PASSWORD={secret_values['admin_password']}",
    ]
    if version:
        lines.append(f"DEPICTIO_VERSION={version}")
    return "\n".join(lines) + "\n"


def checkout_compose() -> Path | None:
    """The docker-compose.yaml of the source checkout depictio runs from, if any."""
    root = package_root()
    if root is None:
        return None
    compose = root.parent / "docker-compose.yaml"
    return compose if compose.is_file() else None


def download(url: str) -> bytes:
    # Unlike the loopback checks, this goes through any proxy set in the
    # environment: on an HPC login node it is the only way out.
    try:
        with urllib.request.urlopen(url, timeout=30) as resp:
            return resp.read()
    except OSError as exc:
        raise LocalStackError(
            f"Could not download {url}: {exc}. Check your network or proxy."
        ) from exc


def compose_file(version: str | None, log=print) -> bytes:
    """The docker-compose.yaml that matches the running code.

    A checkout's own file comes first: it matches the code even where the version
    number still names the last release, whose compose file may predate it. Else
    the file of the release tag, which that version's images were built with.
    """
    local = checkout_compose()
    if local is not None:
        log(f"Using {local}")
        return local.read_bytes()
    if version is None:
        raise LocalStackError(
            "This depictio build is not a release or a beta, so no published "
            "docker-compose.yaml matches it. The hand-over needs a released version (e.g. "
            'uv tool install "depictio[local]==X.Y.Z") or a source checkout of depictio.'
        )
    url = COMPOSE_URL.format(version=version)
    log(f"Downloading {url}")
    return download(url)


def _rebind_seaweedfs(options: Path) -> None:
    """Open the copied SeaweedFS to the Compose network.

    ``weed mini`` saves its flags in ``mini.options`` and reloads them, so the copy
    would keep listening on the container's loopback only. ``ip`` stays: the
    master's raft state is keyed on it, and every SeaweedFS component shares the
    one container.
    """
    if not options.is_file():
        return
    pinned = {"ip.bind": "0.0.0.0", "s3.port": "9000"}
    lines = [
        line
        for line in options.read_text().splitlines()
        if line.partition("=")[0].strip() not in pinned
    ]
    options.write_text("\n".join([*lines, *(f"{k}={v}" for k, v in pinned.items())]) + "\n")


def export_compose(paths: Paths, out: Path, log=print) -> None:
    """Copy the local server's data into ``out`` with what Docker Compose needs to run it.

    The data is copied, not shared: MongoDB must never run twice on one data
    directory, and the local server stays usable. A running local server is
    stopped first, so the copy is consistent; everything that can fail before
    the copy is checked before that.
    """
    if not any((paths.home / "mongo").glob("*")):
        raise LocalStackError(f"No local server data under {paths.home}")
    if out.exists() and any(out.iterdir()):
        raise LocalStackError(f"{out} is not empty")
    version = release_version()
    compose = compose_file(version, log=log)
    override = compose_override(
        installed_version(paths, "mongodb"),
        installed_version(paths, "seaweedfs"),
        # Bind-mounted data stays owned by the host user, so the database and
        # the object store run as that user rather than the images' own.
        f"{os.getuid()}:{os.getgid()}" if sys.platform == "linux" else None,
    )
    secret_values = load_secrets(paths)

    if any(running_status(paths).values()):
        log("Stopping the local server for a consistent copy (depictio local up restarts it)")
        stop_all(paths, log=lambda _msg: None)

    # Owner-only like the local home, since the copies keep their modes and
    # data/keys holds the token-signing key. Containers reach their bind mounts
    # without going through this directory.
    out.mkdir(parents=True, exist_ok=True)
    out.chmod(0o700)
    data = out / "data"
    for sub in EXPORTED_DIRS:
        log(f"Copying {sub} data")
        shutil.copytree(paths.home / sub, data / sub)
    _rebind_seaweedfs(data / "s3" / "mini.options")
    (data / "keys").mkdir(parents=True)
    for name in KEY_FILES:
        shutil.copy2(paths.home / "keys" / name, data / "keys" / name)

    (out / "docker-compose.yaml").write_bytes(compose)
    (out / "docker-compose.override.yaml").write_text(override)
    write_private_file(out / ".env", compose_env(secret_values, version))
