/**
 * serializeOption pins the codebook-key convention shared with the Python
 * builder — the AUTHORITATIVE side is
 * `depictio.serverless.companions.serialize_option` (plain str(), bools
 * lowered to Polars' "true"/"false"). These literals are the coordination
 * contract; if one side changes, the other must change with it. The fixture
 * codebooks are generated by the real builder (`build_companions` in
 * scripts/generate_fixture.py), so the mask tests are the cross-language
 * proof; this file pins the pure-function edges.
 */

import { describe, expect, it } from 'vitest';

import { serializeOption } from '../../src/engine/filters';

describe('serializeOption (codebook key convention — Python str() authoritative)', () => {
  it('strings: codebook keys AS-IS, never quoted (primary runtime path)', () => {
    expect(serializeOption('alpha')).toBe('alpha');
    expect(serializeOption('2007')).toBe('2007');
    expect(serializeOption('2.5')).toBe('2.5');
    expect(serializeOption('2024-01-02 03:04:05')).toBe('2024-01-02 03:04:05');
    expect(serializeOption('')).toBe('');
    expect(serializeOption('with "quote"')).toBe('with "quote"');
  });

  it('numbers: String(v) fallback (matches Python str() for ints)', () => {
    expect(serializeOption(2)).toBe('2');
    expect(serializeOption(-3)).toBe('-3');
    expect(serializeOption(2.5)).toBe('2.5');
    expect(serializeOption(0)).toBe('0');
    // Documented caveat: JS cannot render Python's str(2.0) == "2.0" — this
    // branch is unreachable in practice (values arrive as option strings).
    expect(serializeOption(2.0)).toBe('2');
  });

  it("booleans: lowercase true/false (builder's deliberate exception to str())", () => {
    expect(serializeOption(true)).toBe('true');
    expect(serializeOption(false)).toBe('false');
  });

  it('null/undefined: match nothing (codebooks never map nulls)', () => {
    expect(serializeOption(null)).toBe('null');
    expect(serializeOption(undefined)).toBe('undefined');
  });
});
