import React, { useState } from 'react';
import { Alert, Button, Collapse, Group, List, Modal, Stack, Text } from '@mantine/core';
import { Icon } from '@iconify/react';

import { AI_COLOR, AI_ICON } from '../icons';
import type { AIGenerationInfo } from '../types';

interface Props {
  info: AIGenerationInfo;
  /** Flip the draft into a regular dashboard. A rejection is shown inline;
   *  on success the host updates its own dashboard state, which unmounts
   *  this banner. */
  onPromote: () => Promise<void>;
  /** Delete the draft. Runs only after the confirm dialog; on success the
   *  host navigates away. */
  onDiscard: () => Promise<void>;
}

/** API timestamps arrive as naive UTC (no offset). `Date` would read such a
 *  string as local time, so pin it to UTC before formatting. */
function formatGeneratedAt(raw: string): string {
  if (!raw) return '';
  const pinned = /(Z|[+-]\d{2}:?\d{2})$/.test(raw) ? raw : `${raw}Z`;
  const d = new Date(pinned);
  return Number.isNaN(d.getTime()) ? raw : d.toLocaleString();
}

/**
 * Editor-only notice on a dashboard the AI generated whole and nobody has
 * reviewed yet. Two exits: Promote keeps it as a regular dashboard, Discard
 * deletes it (behind a confirm). Everything else about the dashboard is
 * already editable underneath; the banner only carries the provenance and
 * the decision.
 */
const AIDraftBanner: React.FC<Props> = ({ info, onPromote, onDiscard }) => {
  const [promoting, setPromoting] = useState(false);
  const [discarding, setDiscarding] = useState(false);
  const [confirmOpen, setConfirmOpen] = useState(false);
  const [warningsOpen, setWarningsOpen] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const busy = promoting || discarding;
  const when = formatGeneratedAt(info.generated_at);
  const warnings = info.warnings ?? [];

  const promote = async () => {
    setPromoting(true);
    setError(null);
    try {
      await onPromote();
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setPromoting(false);
    }
  };

  const discard = async () => {
    setDiscarding(true);
    setError(null);
    try {
      await onDiscard();
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setDiscarding(false);
      setConfirmOpen(false);
    }
  };

  return (
    <>
      <Alert
        variant="light"
        color={AI_COLOR}
        icon={<Icon icon={AI_ICON} width={18} />}
        title="AI-generated draft"
        mb="sm"
        data-testid="ai-draft-banner"
      >
        <Stack gap="xs">
          <Text size="sm">
            Generated by{' '}
            <Text span fw={600}>
              {info.model}
            </Text>
            {when ? ` on ${when}` : ''}. Review the components, then promote the dashboard to
            keep it or discard it.
          </Text>
          {info.prompt && (
            <Text size="xs" c="dimmed" lineClamp={2} title={info.prompt}>
              Prompt: {info.prompt}
            </Text>
          )}
          {warnings.length > 0 && (
            <Stack gap={2} align="flex-start">
              <Button
                size="compact-xs"
                variant="subtle"
                color="gray"
                rightSection={
                  <Icon icon={warningsOpen ? 'mdi:chevron-up' : 'mdi:chevron-down'} width={14} />
                }
                onClick={() => setWarningsOpen((o) => !o)}
                data-testid="ai-draft-warnings-toggle"
              >
                {warnings.length} warning{warnings.length === 1 ? '' : 's'}
              </Button>
              <Collapse in={warningsOpen}>
                <List size="xs" spacing={2}>
                  {warnings.map((w, i) => (
                    <List.Item key={i}>{w}</List.Item>
                  ))}
                </List>
              </Collapse>
            </Stack>
          )}
          {error && (
            <Text size="xs" c="red">
              {error}
            </Text>
          )}
          <Group gap="xs">
            <Button
              size="xs"
              color={AI_COLOR}
              leftSection={<Icon icon="mdi:check" width={14} />}
              loading={promoting}
              disabled={busy}
              onClick={() => void promote()}
              data-testid="ai-draft-promote"
            >
              Promote
            </Button>
            <Button
              size="xs"
              variant="subtle"
              color="red"
              leftSection={<Icon icon="mdi:delete-outline" width={14} />}
              disabled={busy}
              onClick={() => setConfirmOpen(true)}
              data-testid="ai-draft-discard"
            >
              Discard
            </Button>
          </Group>
        </Stack>
      </Alert>

      <Modal
        opened={confirmOpen}
        onClose={() => {
          if (!discarding) setConfirmOpen(false);
        }}
        title="Discard this draft?"
        centered
      >
        <Stack gap="md">
          <Text size="sm">
            The dashboard and every component in it are deleted. This cannot be undone.
          </Text>
          <Group justify="flex-end" gap="xs">
            <Button variant="default" onClick={() => setConfirmOpen(false)} disabled={discarding}>
              Keep draft
            </Button>
            <Button
              color="red"
              loading={discarding}
              onClick={() => void discard()}
              data-testid="ai-draft-discard-confirm"
            >
              Discard
            </Button>
          </Group>
        </Stack>
      </Modal>
    </>
  );
};

export default AIDraftBanner;
