// Register the bundled Iconify icons.
//
// Import this once, first thing in an entry point. Without it `<Icon/>` falls
// back to fetching icon data from the public Iconify API, which the app's
// `connect-src 'self'` CSP blocks — every icon then renders as an empty box.
// That failure only shows up outside `vite dev`, which sends no CSP at all.
//
// The subset is generated by scripts/generate-icon-subset.mjs, which every
// `pnpm dev` / `pnpm build` / `pnpm build:static` runs first. It scans the
// source tree *and* the dashboard
// corpus under depictio/projects/** — tab/dashboard/card icons are authored in
// YAML and `.db_seeds/*.json`, never in a .tsx file, so a source-only scan left
// them blank at runtime.

import { addCollection } from '@iconify/react';

import { iconCollections } from './generated/iconSubset';

for (const collection of iconCollections) {
  addCollection(collection);
}
