services:
  minio-backup:
    container_name: minio-backup
    image: minio/minio:latest
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./minio_backup_data:/data
    environment:
      MINIO_ROOT_USER: backup_minio
      MINIO_ROOT_PASSWORD: backup_minio123
    command: server /data --console-address :9003
    ports:
      - "9002:9000"
      - "9003:9003"
    networks:
      - default
