services:
  mongo:
    image: mongo:8.0
    container_name: mongo
    command: mongod --dbpath /data/depictioDB --port 27018 --logpath /dev/null
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - 27018:27018
    volumes:
      - ../depictioDB:/data/depictioDB

  depictio-frontend:
    image: depictio:dev
    container_name: depictio-frontend
    build:
      dockerfile: docker-images/Dockerfile_depictio.dockerfile
      context: ..
    ports:
      - 5080:5080
    volumes:
      - ../depictio:/app/depictio
    env_file:
      - .env
    environment:
        DEV_MODE: "${DEV_MODE:-false}"
        DEPICTIO_LOGGING_VERBOSITY_LEVEL: "DEBUG"
    command: ["/app/run_dash.sh"]
    user: "${UID:-1000}:${GID:-1000}"
    depends_on:
      - mongo
      - depictio-backend

  depictio-backend:
    container_name: depictio-backend
    image: depictio:dev
    build:
      dockerfile: docker-images/Dockerfile_depictio.dockerfile
      context: ..
    ports:
      - 8058:8058
    volumes:
      - ../depictio:/app/depictio
    env_file:
      - .env
    environment:
        DEV_MODE: "${DEV_MODE:-false}"
        DEPICTIO_LOGGING_VERBOSITY_LEVEL: "DEBUG"
    command: ["/app/run_fastapi.sh"]
    user: "${UID:-1000}:${GID:-1000}"
    tty: true
    depends_on:
      - mongo
