#!/usr/bin/env python
"""Generate ``dashboards/reference_extended.yaml`` from ``dashboards/base.yaml``.

``base.yaml`` is the generic nf-core template. It may only bind columns that any
ampliseq run has, which rules out a map, a date range and environmental filters:
a real run without ``latitude`` would not be pruned, it would render a red
``Map error`` annotation in an HTTP 200 figure (``render_map``), because the
component pruner is DC-granular and never inspects columns.

The reference project shipped in this repo *does* have those columns, so its demo
dashboard can use them. Rather than fork ``base.yaml`` into a second 2000-line
file that drifts, this applies the demo layer on top of it:

    base.yaml  --(this script)-->  reference_extended.yaml  --(import)--> seeds

``reference_extended.yaml`` is generated and committed, never hand-edited.
``depictio/tests/models/test_ampliseq_reference_dashboard.py`` rebuilds it in
memory and fails when the committed file drifts from its source.

Template variables are resolved here (from ``template.reference.vars``), so the
output is a concrete dashboard rather than a template: ``depictio dashboard
import`` performs no substitution of its own.

Run:
    python depictio/projects/nf-core/ampliseq/2.16.0/build_reference_dashboard.py
"""

from __future__ import annotations

import copy
import csv
import math
import re
import sys
from pathlib import Path
from typing import Any

import yaml

HERE = Path(__file__).resolve().parent
BASE_YAML = HERE / "dashboards" / "base.yaml"
TEMPLATE_YAML = HERE / "template.yaml"
OUT_YAML = HERE / "dashboards" / "reference_extended.yaml"

# Habitat palette, shared by the map and every figure below so a colour means the
# same thing across the whole dashboard.
HABITAT_COLORS = {
    "Riverwater": "#348ABD",
    "Groundwater": "#45B8AC",
    "Sediment": "#8B5A2B",
    "Soil": "#E24A33",
}

TEAL, ORANGE, CYAN, PURPLE, BLUE, INDIGO = (
    "#45B8AC",
    "#F68B33",
    "#00BCD4",
    "#984EA3",
    "#1976D2",
    "#3F51B5",
)
BROWN, GRAPE = "#8B5A2B", "#8E44AD"

_VAR = re.compile(r"\{([A-Z_][A-Z0-9_]*)\}")

BANNER = """\
# GENERATED by build_reference_dashboard.py — do not edit.
#
# Source: dashboards/base.yaml plus the demo layer that script applies (a
# sampling map, a date range, CTD filters and two extra tabs). Regenerate with:
#     python depictio/projects/nf-core/ampliseq/2.16.0/build_reference_dashboard.py
#
# Template variables are already resolved here for the reference dataset, so this
# file is a concrete dashboard rather than a template. It is imported on top of
# base.yaml when the reference seeds are rebuilt; it is never listed in
# `template.dashboards`, so `depictio run --template nf-core/ampliseq/2.16.0`
# against a real run still only gets base.yaml.
"""


def load_reference_vars() -> dict[str, str]:
    """The variables `template.reference.vars` pins, minus the file paths."""
    template = yaml.safe_load(TEMPLATE_YAML.read_text())
    pinned = template["template"]["reference"]["vars"]
    return {k: v for k, v in pinned.items() if not str(v).startswith("{DATA_ROOT}")}


def substitute(node: Any, variables: dict[str, str]) -> Any:
    if isinstance(node, dict):
        return {k: substitute(v, variables) for k, v in node.items()}
    if isinstance(node, list):
        return [substitute(v, variables) for v in node]
    if isinstance(node, str):
        for name in _VAR.findall(node):
            if name not in variables:
                raise SystemExit(
                    f"reference.vars does not pin {{{name}}}, which base.yaml uses: {node!r}"
                )
            node = node.replace(f"{{{name}}}", variables[name])
        return node
    return node


# --- building blocks ---------------------------------------------------------


def interactive(
    index: str,
    section: str,
    group: str | None,
    kind: str,
    column: str,
    column_type: str,
    title: str,
    icon: str,
    color: str,
    y: int,
    h: int,
) -> dict[str, Any]:
    comp: dict[str, Any] = {
        "component_type": "interactive",
        "workflow_tag": "ampliseq",
        "data_collection_tag": "metadata",
        "interactive_component_type": kind,
        "column_name": column,
        "column_type": column_type,
        "display": {"title_size": "md", "custom_color": color, "icon_name": icon},
        "title_align": "left",
        "placement": "left",
        "section": section,
        "tag": f"interactive-{index}",
        "index": index,
        "layout": {"x": 0, "y": y, "w": 1, "h": h},
        "title": title,
    }
    if group:
        comp["group"] = group
    return comp


def text(index: str, section: str, title: str, body: str, x, y, w, h) -> dict[str, Any]:
    return {
        "component_type": "text",
        "workflow_tag": "ampliseq",
        "title_size": "sm",
        "title_align": "left",
        "order": 2,
        "alignment": "left",
        "section": section,
        "tag": f"text-{index}",
        "index": index,
        "layout": {"x": x, "y": y, "w": w, "h": h},
        "title": title,
        "body": body,
    }


def card(
    index: str,
    section: str,
    dc: str,
    aggregation: str,
    column: str,
    column_type: str,
    title: str,
    icon: str,
    color: str,
    x,
    y,
    extra: dict[str, Any] | None = None,
) -> dict[str, Any]:
    comp: dict[str, Any] = {
        "component_type": "card",
        "workflow_tag": "ampliseq",
        "data_collection_tag": dc,
        "aggregation": aggregation,
        "column_name": column,
        "column_type": column_type,
    }
    comp.update(extra or {})
    comp.update(
        {
            "display": {
                "icon_name": icon,
                "icon_color": color,
                "title_color": color,
                "title_font_size": "xl",
                "value_font_size": "xl",
            },
            "title_size": "sm",
            "title_align": "left",
            "section": section,
            "tag": f"card-{index}",
            "index": index,
            # h=2 like every other shipped card: the viewer measures what the
            # content actually needs and grows the row when a breakdown asks
            # for more, so a stored 3 only ever left a blank band.
            "layout": {"x": x, "y": y, "w": 2, "h": 2},
            "title": title,
        }
    )
    return comp


def code_figure(
    index: str,
    section: str,
    dc: str,
    title: str,
    code: str,
    x,
    y,
    w,
    h,
    selection_column: str | None = None,
) -> dict[str, Any]:
    """A code-mode figure, optionally feeding the Analysis panel.

    ``selection_column`` only makes sense for a figure whose points are rows
    rather than aggregates, and it is only half the wiring: the reader takes the
    id from ``customdata[0]``, which on this path comes from a ``custom_data=``
    argument in the code itself. Setting the key without that argument yields a
    lasso that selects nothing at all, silently.
    """
    comp: dict[str, Any] = {
        "component_type": "figure",
        "workflow_tag": "ampliseq",
        "data_collection_tag": dc,
        "mode": "code",
        "code_content": code.strip() + "\n",
        "title_size": "sm",
        "title_align": "left",
        "section": section,
        "tag": f"figure-{index}",
        "index": index,
        "layout": {"x": x, "y": y, "w": w, "h": h},
        "title": title,
    }
    if selection_column:
        comp["selection_enabled"] = True
        comp["selection_column"] = selection_column
    return comp


def _colors_literal() -> str:
    return repr(HABITAT_COLORS)


# --- the demo layer ----------------------------------------------------------


def main_tab_layer(main: dict[str, Any], group_col: str, id_col: str) -> None:
    """Two more persistent filter sections and the floating map, on the main tab."""
    main["filter_sections"].extend(
        [
            {
                "name": "Campaign design",
                "icon": "mdi:calendar-outline",
                "color": "indigo",
                "description": "When and where each sample was taken",
                "persistent": True,
                "pin": "top",
            },
            {
                "name": "Environment",
                "icon": "mdi:waves",
                "color": "cyan",
                "description": "Sonde readings; synthetic in this reference dataset",
                "collapsed": True,
                "persistent": True,
                "pin": "bottom",
            },
        ]
    )

    main["components"].extend(
        [
            interactive(
                "ref-sampling-date",
                "Campaign design",
                "Where & when",
                "DateRangePicker",
                "sampling_date",
                "datetime",
                "Sampling date",
                "mdi:calendar-outline",
                INDIGO,
                5,
                3,
            ),
            interactive(
                "ref-city",
                "Campaign design",
                "Where & when",
                "MultiSelect",
                "city",
                "object",
                "Site",
                "mdi:map-marker-outline",
                INDIGO,
                8,
                3,
            ),
            interactive(
                "ref-ctd-temperature",
                "Environment",
                "Sonde readings",
                "RangeSlider",
                "ctd_temperature_c",
                "float64",
                "Temperature (°C)",
                "mdi:thermometer",
                CYAN,
                11,
                3,
            ),
            interactive(
                "ref-ctd-conductivity",
                "Environment",
                "Sonde readings",
                "RangeSlider",
                "ctd_conductivity_us_cm",
                "float64",
                "Conductivity (µS/cm)",
                "mdi:flash",
                CYAN,
                14,
                3,
            ),
            interactive(
                "ref-ctd-do",
                "Environment",
                "Sonde readings",
                "RangeSlider",
                "ctd_do_mg_l",
                "float64",
                "Dissolved O₂ (mg/L)",
                "mdi:water-percent",
                CYAN,
                17,
                3,
            ),
            interactive(
                "ref-ctd-nitrate",
                "Environment",
                "Sonde readings",
                "RangeSlider",
                "ctd_nitrate_mg_l",
                "float64",
                "Nitrate (mg/L)",
                "mdi:molecule",
                CYAN,
                20,
                3,
            ),
            # `placement: floating` takes no layout entry at all (see
            # DashboardData.to_full), so the map claims no grid slot and reaches
            # every tab of the family from the header.
            {
                "component_type": "map",
                "workflow_tag": "ampliseq",
                "data_collection_tag": "metadata",
                "map_type": "scatter_map",
                "lat_column": "lat",
                "lon_column": "lon",
                "color_column": group_col,
                # No size_column on purpose: encoding conductivity as marker
                # area made 12 sites read as 12 different-sized dots with no
                # legend to decode them. Conductivity stays on the hover and in
                # the CTD figures, where it has an axis.
                "hover_columns": [id_col, "city", "sampling_date"],
                # Explicit: the lite default and the YAML-to-full conversion
                # default do not agree.
                "map_style": "carto-positron",
                "size_max": 22,
                "opacity": 0.9,
                "selection_enabled": True,
                "selection_column": id_col,
                "placement": "floating",
                "floating_initial_state": "compact",
                # Same habitat palette as every code-mode figure on the demo
                # tabs. Without it render_map falls back to px.colors.qualitative
                # .Plotly, so the two habitat legends on Sampling Campaign
                # disagree with each other side by side.
                "dict_kwargs": {"color_discrete_map": dict(HABITAT_COLORS)},
                "tag": "map-ref-sampling-sites",
                "index": "ref-sampling-sites",
                "title": "Sampling sites",
            },
        ]
    )


def sampling_campaign_tab(group_col: str, group_display: str, id_col: str, order: int) -> dict:
    colors = _colors_literal()
    return {
        "title": "Sampling Campaign",
        "subtitle": "Where and when the Ammer catchment was sampled",
        "tab_order": order,
        "tab_icon": "mdi:map-marker-outline",
        "tab_icon_color": "blue",
        "icon": "/assets/images/workflows/nf-core.png",
        "icon_color": "green",
        "workflow_system": "nf-core",
        "dashboard_id": "646b0f3c1e4a2d7f8e5b8cc3",
        # No filter section of its own: the three persistent sections on the main
        # tab reach this one, which is also what satisfies `_tab_meets_minimum`
        # via `_family_fans_out_a_filter`.
        "grid_sections": [
            {
                "name": "Campaign at a glance",
                "icon": "mdi:counter",
                "color": "blue",
                "description": "How many samples, from how many sites, over what period",
            },
            {
                "name": "Where & when",
                "icon": "mdi:map-marker-outline",
                "color": "teal",
                "description": "The catchment, and the order the sites were visited in",
            },
            {
                "name": "Sampling design",
                "icon": "mdi:chart-donut",
                "color": "violet",
                "description": f"How the {group_display.lower()} groups are spread across sites",
            },
            {
                "name": "Run manifest",
                "icon": "mdi:table",
                "color": "gray",
                "description": "The samplesheet the pipeline was launched with",
                "collapsed": True,
            },
        ],
        "components": [
            text(
                "ref-campaign-header",
                "Campaign at a glance",
                "The sampling campaign",
                "Twelve samples taken across the Ammer catchment near Tübingen in January 2023, "
                "four habitats over six villages. This tab is the *where* and *when* behind every "
                "other tab: the date range and site selector on the left are persistent, so a "
                "period picked here narrows the diversity, taxonomy and differential tiles too.",
                0,
                0,
                8,
                1,
            ),
            card(
                "ref-campaign-samples",
                "Campaign at a glance",
                "metadata",
                "nunique",
                id_col,
                "object",
                "Samples",
                "mdi:flask",
                TEAL,
                0,
                1,
                extra={"secondary_layout": "top_n", "breakdown_col": group_col},
            ),
            card(
                "ref-campaign-habitats",
                "Campaign at a glance",
                "metadata",
                "nunique",
                group_col,
                "object",
                f"{group_display} groups",
                "mdi:earth",
                PURPLE,
                2,
                1,
                extra={"secondary_layout": "donut", "breakdown_col": group_col},
            ),
            card(
                "ref-campaign-sites",
                "Campaign at a glance",
                "metadata",
                "nunique",
                "city",
                "object",
                "Sites visited",
                "mdi:map-marker-outline",
                BLUE,
                4,
                1,
                extra={"secondary_layout": "composition", "breakdown_col": "city"},
            ),
            # `count` rather than `nunique`: AGGREGATION_COMPATIBILITY['datetime']
            # is count/min/max only, and the trend axis is the date column.
            card(
                "ref-campaign-effort",
                "Campaign at a glance",
                "metadata",
                "count",
                id_col,
                "object",
                "Sampling effort",
                "mdi:calendar-outline",
                INDIGO,
                6,
                1,
                extra={"secondary_layout": "trend", "trend_col": "sampling_date"},
            ),
            text(
                "ref-campaign-map-header",
                "Where & when",
                "The catchment",
                "Each marker is one sample, placed at its site and coloured by "
                f"{group_display.lower()}. The same map is available as "
                "a floating panel from every tab, and clicking a marker filters the whole "
                "dashboard to that sample. The strip beside it reads the campaign in time order.",
                0,
                4,
                8,
                1,
            ),
            {
                "component_type": "map",
                "workflow_tag": "ampliseq",
                "data_collection_tag": "metadata",
                "map_type": "scatter_map",
                "lat_column": "lat",
                "lon_column": "lon",
                "color_column": group_col,
                "hover_columns": [id_col, "city", "sampling_date"],
                "map_style": "carto-positron",
                "size_max": 26,
                "opacity": 0.9,
                "selection_enabled": True,
                "selection_column": id_col,
                "placement": "grid",
                "section": "Where & when",
                "dict_kwargs": {"color_discrete_map": dict(HABITAT_COLORS)},
                "tag": "map-ref-campaign-grid",
                "index": "ref-campaign-grid",
                "layout": {"x": 0, "y": 5, "w": 5, "h": 8},
                "title": "Sampling sites",
            },
            code_figure(
                "ref-campaign-timeline",
                "Where & when",
                "metadata",
                "Visit order",
                f"""
colors = {colors}
# Colour by the viewer's analysis groups when there are some, else by the
# pipeline's own {group_display.lower()}. One grouping axis, and the groups
# bring their own colours with them.
grp_col = depictio_group_by[0] if depictio_group_by else '{group_col}'
colors = depictio_group_kwargs.get('color_discrete_map') or colors
df_modified = df.sort('sampling_date')
fig = px.scatter(
    df_modified.to_pandas(),
    x='sampling_date', y='city', color=grp_col,
    color_discrete_map=colors,
    hover_name='{id_col}',
)
fig.update_traces(marker={{'size': 14}})
fig.update_layout(
    xaxis_title='Sampling date', yaxis_title=None, legend_title_text=None if depictio_group_by else '{group_display}',
    margin={{'t': 24, 'l': 8, 'r': 8, 'b': 40}},
)
""",
                5,
                5,
                3,
                8,
            ),
            text(
                "ref-campaign-design-header",
                "Sampling design",
                "Sampling design",
                f"How many samples each site contributed, split by {group_display.lower()}. The "
                "design is deliberately unbalanced: some sites carry a single habitat, others "
                "carry three, which is what makes the between-group contrasts on the other tabs "
                "worth reading with the sample counts in view.",
                0,
                13,
                8,
                1,
            ),
            code_figure(
                "ref-campaign-design",
                "Sampling design",
                "metadata",
                "Samples per site",
                f"""
colors = {colors}
# Colour by the viewer's analysis groups when there are some, else by the
# pipeline's own {group_display.lower()}. One grouping axis, and the groups
# bring their own colours with them.
grp_col = depictio_group_by[0] if depictio_group_by else '{group_col}'
colors = depictio_group_kwargs.get('color_discrete_map') or colors
df_modified = df.group_by(list(dict.fromkeys(['city', grp_col]))).len().rename({{'len': 'samples'}}).sort('city')
fig = px.bar(
    df_modified.to_pandas(),
    x='city', y='samples', color=grp_col,
    color_discrete_map=colors, barmode='stack',
)
fig.update_layout(
    xaxis_title=None, yaxis_title='Samples', legend_title_text=None if depictio_group_by else '{group_display}',
    margin={{'t': 24, 'l': 56, 'r': 16, 'b': 60}},
)
""",
                0,
                14,
                8,
                6,
            ),
            text(
                "ref-campaign-manifest-header",
                "Run manifest",
                "Run manifest",
                "The samplesheet the pipeline was launched with, one row per library.",
                0,
                20,
                8,
                1,
            ),
            {
                "component_type": "table",
                "workflow_tag": "ampliseq",
                "data_collection_tag": "samplesheet",
                # Second selection source on this tab, beside the map: tick
                # libraries here and save them as a group in the Analysis panel.
                "row_selection_enabled": True,
                "row_selection_column": "sampleID",
                "title_size": "sm",
                "title_align": "left",
                "section": "Run manifest",
                "tag": "table-ref-campaign-samplesheet",
                "index": "ref-campaign-samplesheet",
                "layout": {"x": 0, "y": 21, "w": 8, "h": 6},
                "title": "Samplesheet",
            },
        ],
    }


def environment_tab(group_col: str, group_display: str, id_col: str, order: int) -> dict:
    colors = _colors_literal()
    return {
        "title": "Environment (CTD)",
        "subtitle": "Sonde readings per sample, and the diversity they go with",
        "tab_order": order,
        "tab_icon": "mdi:waves",
        "tab_icon_color": "cyan",
        "icon": "/assets/images/workflows/nf-core.png",
        "icon_color": "green",
        "workflow_system": "nf-core",
        "dashboard_id": "646b0f3c1e4a2d7f8e5b8cc4",
        "grid_sections": [
            {
                "name": "Water & soil chemistry",
                "icon": "mdi:waves",
                "color": "cyan",
                "description": "Four sonde channels, each with its distribution",
            },
            {
                "name": "Profiles",
                "icon": "mdi:chart-scatter-plot",
                "color": "cyan",
                "description": f"How the {group_display.lower()} groups separate chemically",
            },
            {
                "name": "Diversity under the current environment",
                "icon": "mdi:chart-bell-curve",
                "color": "orange",
                "description": "What the environmental filters do to alpha diversity",
            },
        ],
        "components": [
            text(
                "ref-env-header",
                "Water & soil chemistry",
                "Environmental context",
                "**These CTD values are synthetic.** They are shaped to be plausible for a "
                "January campaign in the Ammer catchment and to separate the four habitats "
                "cleanly, so that the environmental filters in the left panel have something "
                "real to bite on. They are here to demonstrate environmental filtering, not to "
                "be analysed.",
                0,
                0,
                8,
                1,
            ),
            card(
                "ref-env-temperature",
                "Water & soil chemistry",
                "metadata",
                "median",
                "ctd_temperature_c",
                "float64",
                "Temperature (°C)",
                "mdi:thermometer",
                ORANGE,
                0,
                1,
                extra={"aggregations": ["box_plot_stats"], "secondary_layout": "box_plot"},
            ),
            card(
                "ref-env-conductivity",
                "Water & soil chemistry",
                "metadata",
                "median",
                "ctd_conductivity_us_cm",
                "float64",
                "Conductivity (µS/cm)",
                "mdi:flash",
                CYAN,
                2,
                1,
                extra={"aggregations": ["box_plot_stats"], "secondary_layout": "box_plot"},
            ),
            card(
                "ref-env-do",
                "Water & soil chemistry",
                "metadata",
                "median",
                "ctd_do_mg_l",
                "float64",
                "Dissolved O₂ (mg/L)",
                "mdi:water-percent",
                BLUE,
                4,
                1,
                extra={"aggregations": ["box_plot_stats"], "secondary_layout": "box_plot"},
            ),
            card(
                "ref-env-nitrate",
                "Water & soil chemistry",
                "metadata",
                "median",
                "ctd_nitrate_mg_l",
                "float64",
                "Nitrate (mg/L)",
                "mdi:molecule",
                GRAPE,
                6,
                1,
                extra={"aggregations": ["box_plot_stats"], "secondary_layout": "box_plot"},
            ),
            text(
                "ref-env-profiles-header",
                "Profiles",
                "Chemical profiles",
                "Temperature against conductivity separates the four habitats almost on its own: "
                "groundwater is thermally buffered and carbonate-rich, riverwater is cold and "
                "oxygen-saturated, hyporheic sediment is the most conductive and nearly anoxic, "
                "and soil is the coldest and least mineralised. Nitrate against dissolved organic "
                "carbon shows the same split from the other side.",
                0,
                4,
                8,
                1,
            ),
            code_figure(
                "ref-env-scatter-temp-cond",
                "Profiles",
                "metadata",
                "Temperature × conductivity",
                f"""
colors = {colors}
# Colour by the viewer's analysis groups when there are some, else by the
# pipeline's own {group_display.lower()}. One grouping axis, and the groups
# bring their own colours with them.
grp_col = depictio_group_by[0] if depictio_group_by else '{group_col}'
colors = depictio_group_kwargs.get('color_discrete_map') or colors
fig = px.scatter(
    df.to_pandas(),
    x='ctd_temperature_c', y='ctd_conductivity_us_cm', color=grp_col,
    color_discrete_map=colors, hover_name='city', custom_data=['{id_col}'],
)
fig.update_traces(marker={{'size': 14}})
fig.update_layout(
    xaxis_title='Temperature (°C)', yaxis_title='Conductivity (µS/cm)',
    legend_title_text=None if depictio_group_by else '{group_display}', margin={{'t': 24, 'l': 64, 'r': 16, 'b': 48}},
)
""",
                0,
                5,
                4,
                6,
                selection_column=id_col,
            ),
            code_figure(
                "ref-env-box-do",
                "Profiles",
                "metadata",
                "Dissolved oxygen",
                f"""
colors = {colors}
# Colour by the viewer's analysis groups when there are some, else by the
# pipeline's own {group_display.lower()}. One grouping axis, and the groups
# bring their own colours with them.
grp_col = depictio_group_by[0] if depictio_group_by else '{group_col}'
colors = depictio_group_kwargs.get('color_discrete_map') or colors
fig = px.box(
    df.to_pandas(),
    x=grp_col, y='ctd_do_mg_l', color=grp_col,
    color_discrete_map=colors, points='all',
)
fig.update_layout(
    xaxis_title=None, yaxis_title='Dissolved O₂ (mg/L)', showlegend=False,
    margin={{'t': 24, 'l': 64, 'r': 16, 'b': 48}},
)
""",
                4,
                5,
                4,
                6,
            ),
            code_figure(
                "ref-env-scatter-nitrate-doc",
                "Profiles",
                "metadata",
                "Nitrate × dissolved carbon",
                f"""
colors = {colors}
# Colour by the viewer's analysis groups when there are some, else by the
# pipeline's own {group_display.lower()}. One grouping axis, and the groups
# bring their own colours with them.
grp_col = depictio_group_by[0] if depictio_group_by else '{group_col}'
colors = depictio_group_kwargs.get('color_discrete_map') or colors
fig = px.scatter(
    df.to_pandas(),
    x='ctd_nitrate_mg_l', y='ctd_doc_mg_l', color=grp_col,
    size='ctd_turbidity_ntu', color_discrete_map=colors, hover_name='city', size_max=26,
    custom_data=['{id_col}'],
)
fig.update_layout(
    xaxis_title='Nitrate (mg/L)', yaxis_title='Dissolved organic carbon (mg/L)',
    legend_title_text=None if depictio_group_by else '{group_display}', margin={{'t': 24, 'l': 64, 'r': 16, 'b': 48}},
)
""",
                0,
                11,
                8,
                6,
                selection_column=id_col,
            ),
            text(
                "ref-env-diversity-header",
                "Diversity under the current environment",
                "Diversity under the current environment",
                "The only tile on this tab that is not metadata: Shannon diversity per sample, "
                "reached through the project link from the metadata sample column. Moving a CTD "
                "slider on the left really does shrink this figure, which is the point of the "
                "whole tab. It is also what keeps the tab alive, since a tab whose every "
                "visualisation sits on a metadata collection is pruned at import.",
                0,
                17,
                8,
                1,
            ),
            code_figure(
                "ref-env-diversity",
                "Diversity under the current environment",
                "alpha_diversity_multi_canonical",
                "Shannon diversity",
                f"""
colors = {colors}
# Colour by the viewer's analysis groups when there are some, else by the
# pipeline's own {group_display.lower()}. One grouping axis, and the groups
# bring their own colours with them.
grp_col = depictio_group_by[0] if depictio_group_by else '{group_col}'
colors = depictio_group_kwargs.get('color_discrete_map') or colors
fig = px.box(
    df.to_pandas(),
    x=grp_col, y='shannon', color=grp_col,
    color_discrete_map=colors, points='all',
)
fig.update_layout(
    xaxis_title=None, yaxis_title='Shannon index', showlegend=False,
    margin={{'t': 24, 'l': 64, 'r': 16, 'b': 48}},
)
""",
                0,
                18,
                8,
                6,
            ),
        ],
    }


# Sections the reference dataset cannot fill. The ampliseq reference run is a
# normal 16S run, so `sintax_rel_abundance` is pruned by the template's
# `if_var_absent: SKIP_QIIME` rule and every SINTAX tile disappears at import.
# The *sections* do not: the import prunes components, never section specs, and
# a section's text header has no data_collection_tag so it is always kept. The
# shipped seed therefore carried an empty "SINTAX scope" filter card and a
# "SINTAX classifier" section holding nothing but its own explanatory text.
# base.yaml keeps both, because a real --skip_qiime run needs them.
SINTAX_SECTIONS = ("SINTAX scope", "SINTAX classifier")


def strip_sections(dashboard: dict[str, Any], names: tuple[str, ...]) -> None:
    """Drop the named sections and every component assigned to them."""
    dropped = 0
    for tab in [dashboard["main_dashboard"], *dashboard.get("tabs", [])]:
        for key in ("filter_sections", "grid_sections"):
            if key in tab:
                tab[key] = [s for s in tab[key] if s.get("name") not in names]
        before = len(tab.get("components", []))
        tab["components"] = [c for c in tab.get("components", []) if c.get("section") not in names]
        dropped += before - len(tab["components"])
    print(f"  stripped {names}: {dropped} components removed")


def set_upset_set_colors(dashboard: dict[str, Any], colors: dict[str, str]) -> None:
    """Give every upset_plot an explicit set -> colour map.

    Without it `color_intersections_by: set` falls through to plotly-upset's
    `self.color` default for every bar, which is #333333 — the whole plot
    renders black. base.yaml cannot carry this map because its set names are
    {GROUP_COL} values, unknown until a run is ingested; the reference run's
    are the four habitats.
    """
    for tab in [dashboard["main_dashboard"], *dashboard.get("tabs", [])]:
        for comp in tab.get("components", []):
            cfg = comp.get("config") or {}
            if cfg.get("viz_kind") == "upset_plot":
                cfg["set_colors"] = dict(colors)
                # base.yaml leaves this on `degree` because a generic template
                # cannot name its sets. Here they are the four habitats, so the
                # UpSet can carry the same colours as every other habitat tile.
                cfg["color_intersections_by"] = "set"
                print(f"  set_colors on {comp.get('index', comp.get('tag'))}")


def annotate_heatmap_columns(
    dashboard: dict[str, Any], group_col: str, id_col: str, colors: dict[str, str]
) -> None:
    """Give every clustered heatmap a habitat strip above its columns.

    Both heatmaps have samples for columns, and until now nothing on either said
    which habitat a column came from: the clustering visibly groups the samples,
    and the reader had no way to check that the groups it found are the habitats.
    The row annotation cannot answer that, because `row_annotation_cols` reads
    columns of the heatmap's own DC and habitat lives in the metadata.

    base.yaml cannot carry this: `col_annotations` is a literal
    ``{column_label: category}`` map, so it names this run's samples. That is
    exactly the kind of run-specific value the demo layer exists for.
    """
    metadata = Path(__file__).parent / "input" / "Metadata_full.tsv"
    with metadata.open(encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle, delimiter="\t"))
    by_sample = {r[id_col]: r[group_col] for r in rows if r.get(id_col) and r.get(group_col)}
    if not by_sample:
        raise SystemExit(f"no {id_col}/{group_col} pairs in {metadata}")

    for tab in [dashboard["main_dashboard"], *dashboard.get("tabs", [])]:
        for comp in tab.get("components", []):
            cfg = comp.get("config") or {}
            if cfg.get("viz_kind") != "complex_heatmap":
                continue
            cfg["col_annotations"] = {group_col: dict(by_sample)}
            # Same four hexes as every other habitat tile. Without the override
            # the strip picks its own categorical palette and the dashboard
            # shows two different colours for Riverwater on the same screen.
            cfg["col_annotation_colors"] = {group_col: dict(colors)}
            print(f"  {group_col} column strip on {comp.get('index', comp.get('tag'))}")


CHARS_PER_ROW = 300
GRID_COLS = 8


def fit_text_tiles(dashboard: dict[str, Any]) -> None:
    """Give every text tile enough rows for its body, then close the gap.

    The viewer autofits text tiles at render (TextRenderer measures its prose
    and DashboardGrid turns that into rows), so this is only the stored estimate
    that decides the first paint. It is deliberately rough: a tighter number
    here buys nothing, and too generous a one leaves the tile half empty for the
    instant before the measurement lands.

    Re-packs the section afterwards so a changed height does not leave the tile
    overlapping its neighbour in the stored layout.

    Section-scoped because DashboardGrid mounts one ResponsiveGridLayout per
    section (DashboardGrid.tsx:566), so y is section-relative.
    """
    bumped = 0
    for tab in [dashboard["main_dashboard"], *dashboard.get("tabs", [])]:
        left = {s.get("name") for s in (tab.get("filter_sections") or [])}
        buckets: dict[Any, list] = {}
        touched: set = set()
        for comp in tab.get("components", []):
            if comp.get("placement") == "left" or comp.get("section") in left:
                continue
            layout = comp.get("layout")
            if not isinstance(layout, dict):
                continue
            if comp.get("component_type") == "text":
                need = max(1, math.ceil(len(comp.get("body") or "") / CHARS_PER_ROW))
                if need != layout["h"]:
                    layout["h"] = need
                    touched.add(comp.get("section"))
                    bumped += 1
            buckets.setdefault(comp.get("section"), []).append(layout)
        for name, items in buckets.items():
            if name not in touched:
                continue
            heights = [0] * GRID_COLS
            for item in sorted(items, key=lambda d: (d["y"], d["x"])):
                span = range(item["x"], min(item["x"] + item["w"], GRID_COLS))
                item["y"] = max((heights[c] for c in span), default=0)
                for col in span:
                    heights[col] = item["y"] + item["h"]
    print(f"  fit text tiles: {bumped} raised")


def build() -> dict[str, Any]:
    variables = load_reference_vars()
    dashboard = substitute(yaml.safe_load(BASE_YAML.read_text()), variables)
    dashboard = copy.deepcopy(dashboard)

    group_col = variables["GROUP_COL"]
    group_display = variables["GROUP_COL_DISPLAY"]
    id_col = variables["METADATA_ID_COL"]

    strip_sections(dashboard, SINTAX_SECTIONS)
    set_upset_set_colors(dashboard, HABITAT_COLORS)
    annotate_heatmap_columns(dashboard, group_col, id_col, HABITAT_COLORS)

    main = dashboard["main_dashboard"]
    main["title"] = "nf-core/ampliseq"
    main["subtitle"] = "Ammer catchment reference dataset — QC, diversity, campaign and environment"
    main_tab_layer(main, group_col, id_col)

    next_order = max(t.get("tab_order", 0) for t in dashboard["tabs"]) + 1
    dashboard["tabs"].append(sampling_campaign_tab(group_col, group_display, id_col, next_order))
    dashboard["tabs"].append(environment_tab(group_col, group_display, id_col, next_order + 1))

    # Last, so it also covers the two tabs appended just above.
    fit_text_tiles(dashboard)
    return dashboard


def main() -> int:
    dashboard = build()
    body = yaml.safe_dump(
        dashboard, sort_keys=False, allow_unicode=True, default_flow_style=False, width=1000
    )
    OUT_YAML.write_text(BANNER + body)
    tabs = 1 + len(dashboard["tabs"])
    components = len(dashboard["main_dashboard"]["components"]) + sum(
        len(t["components"]) for t in dashboard["tabs"]
    )
    print(f"wrote {OUT_YAML.relative_to(HERE.parents[3])}: {tabs} tabs, {components} components")
    return 0


if __name__ == "__main__":
    sys.exit(main())
