#!/usr/bin/env bash
# Populate the ampliseq .db_seeds/ dashboards by running a local depictio
# CLI ingest against the template, then exporting the resulting Mongo
# dashboard documents. Mirror of the viralrecon generate_seeds.sh.
#
# Inputs:
#   $1: path to an ampliseq 2.16.0 test-data run (containing input/,
#       multiqc/, qiime2/). Defaults to
#       ~/Data/ampliseq/ampliseq-2.16.0-testdata.
#
# Prerequisites:
#   - Local depictio stack running (API + MongoDB) via docker compose.
#   - depictio CLI venv (or `python -m depictio.cli`) available with the
#     admin token in ~/.depictio/CLI_config.yaml.
#   - Test data generated with depictio/projects/nf-core/ampliseq/2.16.0/
#     download_test_data.sh (only needed once), and the canonical seed TSVs
#     materialised with generate_canonical_seeds.py.
#
# Output:
#   - depictio/projects/nf-core/ampliseq/2.16.0/.db_seeds/dashboard_*.json
#     for the 6 ampliseq dashboards (multiqc + alpha_diversity + community +
#     differential + ordination + phylogeny).
#
# The template YAML under dashboards/ is the SOURCE OF TRUTH: `use:` catalog
# bindings and `*_tag` references are resolved into viz_kind + oids during the
# `depictio run` import, and this script bakes that resolved form into the
# seeds. After exporting, run remap_seeds_to_static_ids.py so the DC ids match
# the static reference-init ids (otherwise tiles 404 on a fresh deploy).
set -euo pipefail

DATA_ROOT="${1:-${HOME}/Data/ampliseq/ampliseq-2.16.0-testdata}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SEEDS_DIR="${SCRIPT_DIR}/.db_seeds"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../../.." && pwd)"

if [ ! -d "$DATA_ROOT" ]; then
    echo "ERROR: ampliseq test-data not found at $DATA_ROOT" >&2
    echo "Generate it via: $SCRIPT_DIR/download_test_data.sh $DATA_ROOT" >&2
    exit 1
fi

mkdir -p "$SEEDS_DIR"

# 1. Run the depictio CLI ingest against the template (must be invoked via
#    `python -m depictio.cli` so the rich-display / polars monkey-patch is
#    applied; see CLAUDE.md note on cli_rich_info_monkeypatch). METADATA_FILE
#    is what flips the template to the full 6-dashboard variant (the
#    `if_var_present: METADATA_FILE` conditional in template.yaml).
cd "$REPO_ROOT"
python -m depictio.cli run \
    --template "nf-core/ampliseq/2.16.0" \
    --data-root "$DATA_ROOT" \
    --var SAMPLESHEET_FILE="$DATA_ROOT/input/samplesheet.csv" \
    --var METADATA_FILE="$DATA_ROOT/input/Metadata_full.tsv"

# 2. Export the 6 ampliseq dashboards from Mongo into .db_seeds/. The
#    dashboard_ids below come from db_init_reference_datasets.STATIC_IDS
#    ("ampliseq" → "dashboards") and the template's dashboards/ YAML.
PROJECT_ID="646b0f3c1e4a2d7f8e5b8ca2"

declare -A DASH_FILES=(
    ["646b0f3c1e4a2d7f8e5b8cb7"]="dashboard_multiqc.json"
    ["646b0f3c1e4a2d7f8e5b8cbe"]="dashboard_alpha_diversity.json"
    ["646b0f3c1e4a2d7f8e5b8cb3"]="dashboard_community.json"
    ["646b0f3c1e4a2d7f8e5b8cb4"]="dashboard_differential.json"
    ["646b0f3c1e4a2d7f8e5b8cc2"]="dashboard_ordination.json"
    ["646b0f3c1e4a2d7f8e5b8cbf"]="dashboard_phylogeny.json"
)

MONGO_URL="${DEPICTIO_MONGODB_URL:-mongodb://localhost:27018/depictioDB}"

for dashboard_id in "${!DASH_FILES[@]}"; do
    out_file="${SEEDS_DIR}/${DASH_FILES[$dashboard_id]}"
    echo "Exporting $dashboard_id → $out_file"
    mongosh --quiet "$MONGO_URL" --eval "
        const doc = db.dashboards_collection.findOne({_id: ObjectId('${dashboard_id}')});
        if (!doc) {
            print('ERROR: dashboard ${dashboard_id} not found in Mongo');
            quit(1);
        }
        printjson(doc);
    " > "$out_file"
done

# 3. Remap the freshly-exported DC ids (auto-generated by the ingest) back to
#    the static reference-init ids so the seeds render on a fresh deploy.
echo ""
echo "Remapping DC ids to static reference ids…"
python "$SCRIPT_DIR/remap_seeds_to_static_ids.py"

echo ""
echo "Seeds exported + remapped in $SEEDS_DIR"
echo "The 6 ampliseq dashboards are already registered in"
echo "  depictio/api/v1/db_init.py (dashboards_config) — no further wiring needed."
