#!/usr/bin/env python
"""Generate ``dashboards/reference_extended.yaml`` from ``dashboards/base.yaml``.

``base.yaml`` is the generic nf-core template. It may only bind columns that any
ampliseq run has, which rules out a map, a date range and environmental filters:
a real run without ``latitude`` would not be pruned, it would render a red
``Map error`` annotation in an HTTP 200 figure (``render_map``), because the
component pruner is DC-granular and never inspects columns.

The reference project shipped in this repo *does* have those columns, so its demo
dashboard can use them. Rather than fork ``base.yaml`` into a second 2000-line
file that drifts, this applies the demo layer on top of it:

    base.yaml  --(this script)-->  reference_extended.yaml  --(import)--> seeds

``reference_extended.yaml`` is generated and committed, never hand-edited.
``depictio/tests/models/test_ampliseq_reference_dashboard.py`` rebuilds it in
memory and fails when the committed file drifts from its source.

Template variables are resolved here (from ``template.reference.vars``), so the
output is a concrete dashboard rather than a template: ``depictio dashboard
import`` performs no substitution of its own.

Run:
    python depictio/projects/nf-core/ampliseq/2.18.0/build_reference_dashboard.py
"""

from __future__ import annotations

import copy
import csv
import math
import re
import sys
from pathlib import Path
from typing import Any

import yaml

from depictio.models.components.text_layout import estimate_text_rows

HERE = Path(__file__).resolve().parent
BASE_YAML = HERE / "dashboards" / "base.yaml"
TEMPLATE_YAML = HERE / "template.yaml"
OUT_YAML = HERE / "dashboards" / "reference_extended.yaml"

# Habitat palette, set as the family's `category_colors` so the map, every figure,
# the advanced viz and the filter chips agree on what a colour means.
HABITAT_COLORS = {
    "Riverwater": "#348ABD",
    "Groundwater": "#45B8AC",
    "Sediment": "#8B5A2B",
    "Soil": "#E24A33",
}


_VAR = re.compile(r"\{([A-Z_][A-Z0-9_]*)\}")

BANNER = """\
# GENERATED by build_reference_dashboard.py; do not edit.
#
# Source: dashboards/base.yaml plus the demo layer that script applies (a
# sampling map, a date range, CTD filters and two extra tabs). Regenerate with:
#     python depictio/projects/nf-core/ampliseq/2.18.0/build_reference_dashboard.py
#
# Template variables are already resolved here for the reference dataset, so this
# file is a concrete dashboard rather than a template. It is imported on top of
# base.yaml when the reference seeds are rebuilt; it is never listed in
# `template.dashboards`, so `depictio ingest --template nf-core/ampliseq/2.18.0`
# against a real run still only gets base.yaml.
"""


def load_reference_vars() -> dict[str, str]:
    """The variables `template.reference.vars` pins, minus the file paths."""
    template = yaml.safe_load(TEMPLATE_YAML.read_text())
    pinned = template["template"]["reference"]["vars"]
    return {k: v for k, v in pinned.items() if not str(v).startswith("{DATA_ROOT}")}


def substitute(node: Any, variables: dict[str, str]) -> Any:
    # Keys too (`category_colors: {"{GROUP_COL}": auto}`), as the CLI's
    # `substitute_template_variables` does. A substituted key landing on one
    # written as is merges into it, the one written as is winning value by
    # value; a bare `auto` meets a map as `{"*": "auto"}`.
    def merge(kept: Any, other: Any) -> Any:
        if isinstance(kept, dict) and other == "auto":
            other = {"*": "auto"}
        if isinstance(other, dict) and kept == "auto":
            kept = {"*": "auto"}
        if isinstance(kept, dict) and isinstance(other, dict):
            merged = dict(other)
            for k, v in kept.items():
                merged[k] = merge(v, merged[k]) if k in merged else v
            return merged
        return kept

    if isinstance(node, dict):
        out: dict[Any, Any] = {}
        static: set[Any] = set()
        for key, value in node.items():
            new_key, new_value = substitute(key, variables), substitute(value, variables)
            if new_key not in out:
                out[new_key] = new_value
            elif new_key == key and new_key not in static:
                out[new_key] = merge(new_value, out[new_key])
            else:
                out[new_key] = merge(out[new_key], new_value)
            if new_key == key:
                static.add(new_key)
        return out
    if isinstance(node, list):
        return [substitute(v, variables) for v in node]
    if isinstance(node, str):
        for name in _VAR.findall(node):
            if name not in variables:
                raise SystemExit(
                    f"reference.vars does not pin {{{name}}}, which base.yaml uses: {node!r}"
                )
            node = node.replace(f"{{{name}}}", variables[name])
        return node
    return node


# --- building blocks ---------------------------------------------------------


def interactive(
    index: str,
    section: str,
    group: str | None,
    kind: str,
    column: str,
    column_type: str,
    title: str,
    icon: str,
    color: str,
    y: int,
    h: int,
) -> dict[str, Any]:
    comp: dict[str, Any] = {
        "component_type": "interactive",
        "workflow_tag": "ampliseq",
        "data_collection_tag": "metadata",
        "interactive_component_type": kind,
        "column_name": column,
        "column_type": column_type,
        # A Mantine palette name, one per column across the dashboard, so a
        # filter reads as the same filter wherever it appears.
        "display": {"icon_name": icon, "custom_color": color},
        "section": section,
        "tag": f"am-ref-filter-{index}",
        "index": index,
        "layout": {"x": 0, "y": y, "w": 1, "h": h},
        "title": title,
    }
    if group:
        comp["group"] = group
    return comp


def card(
    index: str,
    section: str,
    column: str,
    aggregation: str,
    title: str,
    icon: str,
    color: str,
    description: str,
    x: int,
    w: int,
    extra: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """A strip card on the metadata DC; the section's `card_variant` styles it."""
    comp: dict[str, Any] = {
        "component_type": "card",
        "workflow_tag": "ampliseq",
        "data_collection_tag": "metadata",
        "aggregation": aggregation,
        "column_name": column,
        "column_type": "float64" if aggregation == "median" else "object",
    }
    comp.update(extra or {})
    comp.update(
        {
            "display": {"icon_name": icon, "icon_color": color},
            "section": section,
            "tag": f"am-ref-card-{index}",
            "index": index,
            "title": title,
            "description": description,
            "layout": {"x": x, "y": 0, "w": w, "h": 1},
        }
    )
    return comp


def code_figure(
    index: str,
    section: str,
    dc: str,
    title: str,
    code: str,
    x,
    y,
    w,
    h,
    selection_column: str | None = None,
) -> dict[str, Any]:
    """A code-mode figure, optionally feeding the Analysis panel.

    ``selection_column`` only makes sense for a figure whose points are rows
    rather than aggregates, and it is only half the wiring: the reader takes the
    id from ``customdata[0]``, which on this path comes from a ``custom_data=``
    argument in the code itself. Setting the key without that argument yields a
    lasso that selects nothing at all, silently.
    """
    comp: dict[str, Any] = {
        "component_type": "figure",
        "workflow_tag": "ampliseq",
        "data_collection_tag": dc,
        "mode": "code",
        "code_content": code.strip() + "\n",
        "section": section,
        "tag": f"am-ref-figure-{index}",
        "index": index,
        "layout": {"x": x, "y": y, "w": w, "h": h},
        "title": title,
    }
    if selection_column:
        comp["selection_enabled"] = True
        comp["selection_column"] = selection_column
    return comp


def _group_colors(group_col: str) -> str:
    """The code-figure preamble every demo figure shares (RULES.md, Colours).

    Colours by Analysis mode's groups when there are some, else by the
    pipeline's group column in the family's category colours. The figures name
    their own `color`, so they take the pieces of `depictio_group_kwargs`
    rather than spreading it.
    """
    return (
        f"grp_col = depictio_group_by[0] if depictio_group_by else '{group_col}'\n"
        "colors = depictio_group_kwargs.get('color_discrete_map') or "
        f"depictio_category_colors.get('{group_col}') or {{}}\n"
    )


# --- the demo layer ----------------------------------------------------------


def main_tab_layer(main: dict[str, Any], group_col: str, id_col: str) -> None:
    """Two more persistent filter sections and the floating map, on the main tab."""
    # The four habitats get their own colours rather than the generated ones:
    # every tile, the map and the filter chips read this one map.
    main.setdefault("category_colors", {})[group_col] = dict(HABITAT_COLORS)

    main["filter_sections"].extend(
        [
            {
                "name": "Campaign design",
                "icon": "mdi:calendar-outline",
                "color": "indigo",
                "description": "When and where each sample was taken",
                "persistent": True,
                "pin": "top",
            },
            {
                "name": "Environment",
                "icon": "mdi:waves",
                "color": "cyan",
                "description": "Sonde readings; synthetic in this reference dataset",
                "collapsed": True,
                "persistent": True,
                "pin": "bottom",
            },
        ]
    )

    main["components"].extend(
        [
            interactive(
                "ref-sampling-date",
                "Campaign design",
                "Where & when",
                "DateRangePicker",
                "sampling_date",
                "datetime",
                "Sampling date",
                "mdi:calendar-outline",
                "indigo",
                5,
                3,
            ),
            interactive(
                "ref-city",
                "Campaign design",
                "Where & when",
                "MultiSelect",
                "city",
                "object",
                "Site",
                "mdi:map-marker-outline",
                "orange",
                8,
                3,
            ),
            interactive(
                "ref-ctd-temperature",
                "Environment",
                "Sonde readings",
                "RangeSlider",
                "ctd_temperature_c",
                "float64",
                "Temperature (°C)",
                "mdi:thermometer",
                "red",
                11,
                3,
            ),
            interactive(
                "ref-ctd-conductivity",
                "Environment",
                "Sonde readings",
                "RangeSlider",
                "ctd_conductivity_us_cm",
                "float64",
                "Conductivity (µS/cm)",
                "mdi:flash",
                "yellow",
                14,
                3,
            ),
            interactive(
                "ref-ctd-do",
                "Environment",
                "Sonde readings",
                "RangeSlider",
                "ctd_do_mg_l",
                "float64",
                "Dissolved O₂ (mg/L)",
                "mdi:water-percent",
                "blue",
                17,
                3,
            ),
            interactive(
                "ref-ctd-nitrate",
                "Environment",
                "Sonde readings",
                "RangeSlider",
                "ctd_nitrate_mg_l",
                "float64",
                "Nitrate (mg/L)",
                "mdi:molecule",
                "green",
                20,
                3,
            ),
            # `placement: floating` takes no layout entry at all (see
            # DashboardData.to_full), so the map claims no grid slot and reaches
            # every tab of the family from the header. Its markers take the
            # family's category colours, like every other habitat tile.
            {
                "component_type": "map",
                "workflow_tag": "ampliseq",
                "data_collection_tag": "metadata",
                "map_type": "scatter_map",
                "lat_column": "lat",
                "lon_column": "lon",
                "color_column": group_col,
                # No size_column on purpose: encoding conductivity as marker
                # area made 12 sites read as 12 different-sized dots with no
                # legend to decode them. Conductivity stays on the hover and in
                # the CTD figures, where it has an axis.
                "hover_columns": [id_col, "city", "sampling_date"],
                # Explicit: the lite default and the YAML-to-full conversion
                # default do not agree.
                "map_style": "carto-positron",
                "size_max": 22,
                "opacity": 0.9,
                "selection_enabled": True,
                "selection_column": id_col,
                "placement": "floating",
                # Docked to the filter panel: floating, it covered the key figures.
                "floating_initial_state": "docked",
                "tag": "am-ref-map-sampling-sites",
                "index": "ref-sampling-sites",
                "title": "Sampling sites",
            },
        ]
    )


def sampling_campaign_tab(group_col: str, group_display: str, id_col: str, order: int) -> dict:
    groups = _group_colors(group_col)
    return {
        "title": "Sampling Campaign",
        "subtitle": "Where and when was each sample taken?",
        "tab_group": "Data & QC",
        "tab_order": order,
        "tab_icon": "mdi:map-marker-outline",
        "tab_icon_color": "blue",
        "icon": "/assets/images/workflows/nf-core.png",
        "icon_color": "green",
        "workflow_system": "nf-core",
        "dashboard_id": "646b0f3c1e4a2d7f8e5b8cc3",
        # No filter section of its own: the persistent sections on the main tab
        # (sample, campaign, environment) reach this one, which is also what
        # satisfies `_tab_meets_minimum` via `_family_fans_out_a_filter`.
        "grid_sections": [
            {
                "name": "Campaign at a glance",
                "icon": "mdi:counter",
                "color": "blue",
                "card_variant": "compact",
                "description": f"Samples by {group_display.lower()}, and the sites they came from",
            },
            {
                "name": "Where & when",
                "icon": "mdi:map-marker-outline",
                "color": "teal",
                "description": "One marker per sample at its site; click one to filter every tab",
            },
            {
                "name": "Sampling design",
                "icon": "mdi:chart-donut",
                "color": "violet",
                "description": f"Samples per site by {group_display.lower()}; the design is unbalanced",
            },
            {
                "name": "Run manifest",
                "icon": "mdi:table",
                "color": "gray",
                "description": "The samplesheet the pipeline was launched with, one row per library",
                "collapsed": True,
            },
        ],
        "components": [
            card(
                "ref-campaign-samples",
                "Campaign at a glance",
                id_col,
                "nunique",
                "Samples",
                "mdi:flask-outline",
                "blue",
                f"Samples in the campaign. The bar splits them by {group_display.lower()}.",
                0,
                4,
                extra={"secondary_layout": "composition", "breakdown_col": group_col},
            ),
            card(
                "ref-campaign-sites",
                "Campaign at a glance",
                "city",
                "nunique",
                "Sites visited",
                "mdi:map-marker-outline",
                "teal",
                "Villages sampled. The bar splits the samples by site.",
                4,
                4,
                extra={"secondary_layout": "composition", "breakdown_col": "city"},
            ),
            {
                "component_type": "map",
                "workflow_tag": "ampliseq",
                "data_collection_tag": "metadata",
                "map_type": "scatter_map",
                "lat_column": "lat",
                "lon_column": "lon",
                "color_column": group_col,
                "hover_columns": [id_col, "city", "sampling_date"],
                "map_style": "carto-positron",
                "size_max": 26,
                "opacity": 0.9,
                "selection_enabled": True,
                "selection_column": id_col,
                "placement": "grid",
                "section": "Where & when",
                "tag": "am-ref-map-campaign-grid",
                "index": "ref-campaign-grid",
                "layout": {"x": 0, "y": 0, "w": 5, "h": 7},
                "title": "Sampling sites",
            },
            code_figure(
                "ref-campaign-timeline",
                "Where & when",
                "metadata",
                "Visit order",
                f"""
{groups}df_modified = df.sort('sampling_date')
fig = px.scatter(
    df_modified.to_pandas(),
    x='sampling_date', y='city', color=grp_col,
    color_discrete_map=colors,
    hover_name='{id_col}',
)
fig.update_traces(marker={{'size': 14}})
fig.update_layout(
    xaxis_title='Sampling date', yaxis_title=None, legend_title_text=None if depictio_group_by else '{group_display}',
    margin={{'t': 24, 'l': 8, 'r': 8, 'b': 40}},
)
""",
                5,
                0,
                3,
                7,
            ),
            code_figure(
                "ref-campaign-design",
                "Sampling design",
                "metadata",
                "Samples per site",
                f"""
{groups}df_modified = df.group_by(list(dict.fromkeys(['city', grp_col]))).len().rename({{'len': 'samples'}}).sort('city')
fig = px.bar(
    df_modified.to_pandas(),
    x='city', y='samples', color=grp_col,
    color_discrete_map=colors, barmode='stack',
)
fig.update_layout(
    xaxis_title=None, yaxis_title='Samples', legend_title_text=None if depictio_group_by else '{group_display}',
    margin={{'t': 24, 'l': 56, 'r': 16, 'b': 60}},
)
""",
                0,
                0,
                8,
                5,
            ),
            {
                "component_type": "table",
                "workflow_tag": "ampliseq",
                "data_collection_tag": "samplesheet",
                # Second selection source on this tab, beside the map: tick
                # libraries here and save them as a group in the Analysis panel.
                "row_selection_enabled": True,
                "row_selection_column": "sampleID",
                "section": "Run manifest",
                "tag": "am-ref-table-campaign-samplesheet",
                "index": "ref-campaign-samplesheet",
                "layout": {"x": 0, "y": 0, "w": 8, "h": 6},
                "title": "Samplesheet",
            },
        ],
    }


def environment_tab(group_col: str, group_display: str, id_col: str, order: int) -> dict:
    groups = _group_colors(group_col)
    sonde = [
        ("temperature", "ctd_temperature_c", "Temperature (°C)", "mdi:thermometer", "orange"),
        ("conductivity", "ctd_conductivity_us_cm", "Conductivity (µS/cm)", "mdi:flash", "cyan"),
        ("do", "ctd_do_mg_l", "Dissolved O₂ (mg/L)", "mdi:water-percent", "blue"),
        ("nitrate", "ctd_nitrate_mg_l", "Nitrate (mg/L)", "mdi:molecule", "grape"),
    ]
    return {
        "title": "Environment (CTD)",
        "subtitle": "How do the habitats differ chemically, and does diversity follow?",
        "tab_group": "Data & QC",
        "tab_order": order,
        "tab_icon": "mdi:waves",
        "tab_icon_color": "cyan",
        "icon": "/assets/images/workflows/nf-core.png",
        "icon_color": "green",
        "workflow_system": "nf-core",
        "dashboard_id": "646b0f3c1e4a2d7f8e5b8cc4",
        "grid_sections": [
            {
                "name": "Sonde readings",
                "icon": "mdi:waves",
                "color": "cyan",
                "card_variant": "compact",
                "description": "Synthetic readings, shaped to separate the four habitats",
            },
            {
                "name": "Profiles",
                "icon": "mdi:chart-scatter-plot",
                "color": "cyan",
                "description": "Temperature against conductivity separates the habitats almost alone",
            },
            {
                "name": "Diversity under the current environment",
                "icon": "mdi:chart-bell-curve",
                "color": "orange",
                "description": "Shannon per sample; the sonde filters on the left narrow it too",
            },
        ],
        "components": [
            *(
                card(
                    f"ref-env-{key}",
                    "Sonde readings",
                    column,
                    "median",
                    title,
                    icon,
                    color,
                    f"Median {title.split(' (')[0].lower()} over the samples in view.",
                    2 * i,
                    2,
                )
                for i, (key, column, title, icon, color) in enumerate(sonde)
            ),
            code_figure(
                "ref-env-scatter-temp-cond",
                "Profiles",
                "metadata",
                "Temperature × conductivity",
                f"""
{groups}fig = px.scatter(
    df.to_pandas(),
    x='ctd_temperature_c', y='ctd_conductivity_us_cm', color=grp_col,
    color_discrete_map=colors, hover_name='city', custom_data=['{id_col}'],
)
fig.update_traces(marker={{'size': 14}})
fig.update_layout(
    xaxis_title='Temperature (°C)', yaxis_title='Conductivity (µS/cm)',
    legend_title_text=None if depictio_group_by else '{group_display}', margin={{'t': 24, 'l': 64, 'r': 16, 'b': 48}},
)
""",
                0,
                0,
                4,
                5,
                selection_column=id_col,
            ),
            code_figure(
                "ref-env-box-do",
                "Profiles",
                "metadata",
                "Dissolved oxygen",
                f"""
{groups}fig = px.box(
    df.to_pandas(),
    x=grp_col, y='ctd_do_mg_l', color=grp_col,
    color_discrete_map=colors, points='all',
)
fig.update_layout(
    xaxis_title=None, yaxis_title='Dissolved O₂ (mg/L)', showlegend=False,
    margin={{'t': 24, 'l': 64, 'r': 16, 'b': 48}},
)
""",
                4,
                0,
                4,
                5,
            ),
            code_figure(
                "ref-env-scatter-nitrate-doc",
                "Profiles",
                "metadata",
                "Nitrate × dissolved carbon",
                f"""
{groups}fig = px.scatter(
    df.to_pandas(),
    x='ctd_nitrate_mg_l', y='ctd_doc_mg_l', color=grp_col,
    size='ctd_turbidity_ntu', color_discrete_map=colors, hover_name='city', size_max=26,
    custom_data=['{id_col}'],
)
fig.update_layout(
    xaxis_title='Nitrate (mg/L)', yaxis_title='Dissolved organic carbon (mg/L)',
    legend_title_text=None if depictio_group_by else '{group_display}', margin={{'t': 24, 'l': 64, 'r': 16, 'b': 48}},
)
""",
                0,
                5,
                8,
                5,
                selection_column=id_col,
            ),
            # The only tile on this tab that is not metadata, reached through the
            # project link from the metadata sample column: moving a sonde slider
            # shrinks it. It also keeps the tab alive, since a tab whose every
            # visualisation sits on a metadata collection is pruned at import.
            code_figure(
                "ref-env-diversity",
                "Diversity under the current environment",
                "alpha_diversity_multi_canonical",
                "Shannon diversity",
                f"""
{groups}fig = px.box(
    df.to_pandas(),
    x=grp_col, y='shannon', color=grp_col,
    color_discrete_map=colors, points='all',
)
fig.update_layout(
    xaxis_title=None, yaxis_title='Shannon index', showlegend=False,
    margin={{'t': 24, 'l': 64, 'r': 16, 'b': 48}},
)
""",
                0,
                0,
                8,
                5,
            ),
        ],
    }


def annotate_heatmap_columns(dashboard: dict[str, Any], group_col: str, id_col: str) -> None:
    """Give every clustered heatmap a habitat strip above its columns.

    Both heatmaps have samples for columns, and nothing on either says which
    habitat a column came from: the clustering visibly groups the samples, and
    the reader has no way to check that the groups it found are the habitats.
    The row annotation cannot answer that, because `row_annotation_cols` reads
    columns of the heatmap's own DC and habitat lives in the metadata.

    base.yaml cannot carry this: `col_annotations` is a literal
    ``{column_label: category}`` map, so it names this run's samples. That is
    exactly the kind of run-specific value the demo layer exists for. The
    strip's colours come from the family's category colours.
    """
    metadata = Path(__file__).parent / "input" / "Metadata_full.tsv"
    with metadata.open(encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle, delimiter="\t"))
    by_sample = {r[id_col]: r[group_col] for r in rows if r.get(id_col) and r.get(group_col)}
    if not by_sample:
        raise SystemExit(f"no {id_col}/{group_col} pairs in {metadata}")

    for tab in [dashboard["main_dashboard"], *dashboard.get("tabs", [])]:
        for comp in tab.get("components", []):
            cfg = comp.get("config") or {}
            if cfg.get("viz_kind") != "complex_heatmap":
                continue
            cfg["col_annotations"] = {group_col: dict(by_sample)}
            print(f"  {group_col} column strip on {comp.get('index', comp.get('tag'))}")


def add_tree_group_colour(dashboard: dict[str, Any]) -> None:
    """Offer the tree's dominant-group column as a tip colour.

    The tip-metadata recipe names that column ``dominant_habitat`` after the
    reference study's design, so base.yaml cannot list it: on another run the
    option would name a design the run does not have. The reference run is
    exactly that design, so the demo layer puts the option back.
    """
    for tab in [dashboard["main_dashboard"], *dashboard.get("tabs", [])]:
        for comp in tab.get("components", []):
            cfg = comp.get("config") or {}
            if cfg.get("viz_kind") != "phylogenetic":
                continue
            cols = cfg.setdefault("extra_color_cols", [])
            if "dominant_habitat" not in cols:
                cols.append("dominant_habitat")
                print(f"  dominant_habitat colour on {comp.get('index', comp.get('tag'))}")


def list_demo_tabs(main: dict[str, Any], titles: list[str]) -> None:
    """Name the demo tabs in the Overview's tab tiles, under "Data & QC".

    base.yaml lists only the tabs every run can have; the reference run also
    has the two demo tabs, which would otherwise be reachable from the sidebar
    alone.
    """
    for comp in main["components"]:
        body = comp.get("body") or ""
        if comp.get("index") != "ov-how-to-read" or "### Data & QC" not in body:
            continue
        head, rest = body.split("### Data & QC\n", 1)
        lines = rest.split("\n")
        end = next(i for i, line in enumerate(lines) if not line.startswith("- "))
        lines[end:end] = [f"- [{title}](tab:{title})" for title in titles]
        comp["body"] = head + "### Data & QC\n" + "\n".join(lines)
        return
    raise SystemExit("no Data & QC tab list on the Overview")


def insert_after_group(dashboard: dict[str, Any], group: str, new_tabs: list[dict]) -> None:
    """Add ``new_tabs`` at the end of tab group ``group``, shifting the tabs after it.

    `tab_order` stays contiguous within each group (RULES.md, Family), so the
    demo tabs join "Data & QC" right after MultiQC and every later tab moves
    down by as many slots. The list itself stays base tabs first: the import
    matches tabs by title, and `tab_order` alone sets the display order.
    """
    last = max(t.get("tab_order", 0) for t in dashboard["tabs"] if t.get("tab_group") == group)
    for tab in dashboard["tabs"]:
        if tab.get("tab_order", 0) > last:
            tab["tab_order"] += len(new_tabs)
    for offset, tab in enumerate(new_tabs, start=1):
        tab["tab_order"] = last + offset
    dashboard["tabs"].extend(new_tabs)


GRID_COLS = 8


def fit_text_tiles(dashboard: dict[str, Any]) -> None:
    """Raise a text tile shorter than its body needs, then close the gap.

    The viewer autofits text tiles at render (TextRenderer measures its content
    and DashboardGrid turns that into rows), so this is only the stored floor
    that decides the first paint: half the shared estimate, the shipped-YAML
    lint's rule for an autofit tile. Tiles already tall enough are left alone.

    Re-packs a touched section afterwards so a raised tile does not overlap its
    neighbour in the stored layout. Route alternates share one slot (same
    layout), so they move together; filter-bar controls render in the bar, not
    the grid, and are not packed.

    Section-scoped because DashboardGrid mounts one ResponsiveGridLayout per
    section, so y is section-relative.
    """
    raised = 0
    for tab in [dashboard["main_dashboard"], *dashboard.get("tabs", [])]:
        left = {s.get("name") for s in (tab.get("filter_sections") or [])}
        buckets: dict[Any, list] = {}
        touched: set = set()
        for comp in tab.get("components", []):
            if comp.get("component_type") == "interactive" or comp.get("section") in left:
                continue
            layout = comp.get("layout")
            if not isinstance(layout, dict):
                continue
            slot = (layout["x"], layout["y"], layout["w"], layout["h"])
            if comp.get("component_type") == "text":
                need = math.ceil(estimate_text_rows(comp.get("body") or "", layout["w"]) / 2)
                if layout["h"] < need:
                    layout["h"] = need
                    touched.add(comp.get("section"))
                    raised += 1
            buckets.setdefault(comp.get("section"), []).append((slot, layout))
        for name, items in buckets.items():
            if name not in touched:
                continue
            heights = [0] * GRID_COLS
            placed: dict[tuple, int] = {}
            for slot, item in sorted(items, key=lambda pair: (pair[0][1], pair[0][0])):
                if slot not in placed:
                    span = range(item["x"], min(item["x"] + item["w"], GRID_COLS))
                    placed[slot] = max((heights[c] for c in span), default=0)
                    for col in span:
                        heights[col] = max(heights[col], placed[slot] + item["h"])
                item["y"] = placed[slot]
    print(f"  fit text tiles: {raised} raised")


def build() -> dict[str, Any]:
    variables = load_reference_vars()
    dashboard = substitute(yaml.safe_load(BASE_YAML.read_text()), variables)
    dashboard = copy.deepcopy(dashboard)

    group_col = variables["GROUP_COL"]
    group_display = variables["GROUP_COL_DISPLAY"]
    id_col = variables["METADATA_ID_COL"]

    annotate_heatmap_columns(dashboard, group_col, id_col)
    add_tree_group_colour(dashboard)

    main = dashboard["main_dashboard"]
    main["title"] = "nf-core/ampliseq"
    main["subtitle"] = "Ammer catchment reference dataset: QC, diversity, campaign and environment"
    main_tab_layer(main, group_col, id_col)

    insert_after_group(
        dashboard,
        "Data & QC",
        [
            sampling_campaign_tab(group_col, group_display, id_col, 0),
            environment_tab(group_col, group_display, id_col, 0),
        ],
    )

    list_demo_tabs(main, ["Sampling Campaign", "Environment (CTD)"])

    # Last, so it also covers the two tabs added just above.
    fit_text_tiles(dashboard)
    return dashboard


def main() -> int:
    dashboard = build()
    body = yaml.safe_dump(
        dashboard, sort_keys=False, allow_unicode=True, default_flow_style=False, width=1000
    )
    OUT_YAML.write_text(BANNER + body)
    tabs = 1 + len(dashboard["tabs"])
    components = len(dashboard["main_dashboard"]["components"]) + sum(
        len(t["components"]) for t in dashboard["tabs"]
    )
    print(f"wrote {OUT_YAML.relative_to(HERE.parents[3])}: {tabs} tabs, {components} components")
    return 0


if __name__ == "__main__":
    sys.exit(main())
