services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile

    init: true

    extra_hosts:
      - host.docker.internal:host-gateway

    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Uncomment the next line to use a non-root user for all processes.
    user: vscode
    depends_on:
      - mongo
      # - minio
      # - depictio_backend
      # - depictio_frontend
      # - jbrowse2


  mongo:
    image: mongo:latest
    command: --dbpath /data/depictioDB --port 27018
    user: "${UID}:${GID}"  # Run as the specified user (not root)
    ports:
      - 27018:27018
    volumes:
      - ../depictioDB:/data/depictioDB


  minio:
    image: minio/minio:latest
    user: "${UID}:${GID}"  # Run as the specified user (not root)
    volumes:
      - "../minio_data:/data"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address :9001
    ports:
      - "9000:9000"
      - "9001:9001"


  depictio_frontend:
    # image: registry.git.embl.de/tweber/depictio/depictio:latest
    # platform: linux/arm64
    # image: depictio:dev
    build:
      dockerfile: ../docker-images/Dockerfile_depictio.dockerfile
    ports:
      - 5080:5080
    volumes:
      - ../depictio:/app/depictio
      - ../configs:/configs
      - ../data:/app/data
      - ../minio_data:/minio_data
      - ../.env:/app/.env
    command: ["python", "/app/depictio/dash/app.py"]
    user: "${UID}:${GID}"
    depends_on:
      - mongo
      - minio
      - depictio_backend
      # - redis
      # - rabbitmq


  depictio_backend:
    # image: registry.git.embl.de/tweber/depictio/depictio:latest
    # platform: linux/arm64
    # image: depictio:dev
    build:
      dockerfile: ../docker-images/Dockerfile_depictio.dockerfile
    ports:
      - 8058:8058
    volumes:
      # - "${DEPICTIO_BACKEND_DATA_VOLUME_HOST}:${DEPICTIO_BACKEND_DATA_VOLUME_HOST}"
      - ../depictio:/app/depictio
      - ../data:/app/data
      - ../minio_data:/minio_data
      - ../jbrowse-watcher-plugin/sessions:/jbrowse-watcher-plugin/sessions
      - ../configs:/configs
      - ../.env:/app/.env
    command: ["python", "/app/depictio/api/run.py"]
    user: "${UID}:${GID}"  # Run as the specified user (not root)
    depends_on:
      - mongo
      - minio


  # jbrowse2:
  #   image: registry.git.embl.de/tweber/depictio/jbrowse2:latest
  #   # image: jbrowse2:latest
  #   # build:
  #   #   dockerfile: docker-images/Dockerfile_jbrowse.dev.240424.dockerfile
  #   ports: 
  #     - 3000:3000
  #     - 9010:9010
  #   volumes:
  #     - "../jbrowse-watcher-plugin:/usr/src/plugin"
  #     - "../jbrowse-watcher-plugin/sessions:/usr/src/jbrowse/plugin/sessions"


  # depictio_nb:
  #   image: registry.git.embl.de/tweber/depictio/depictio_nb:dev
  #   # image: depictio_nb:dev
  #   # build:
  #   #   dockerfile: docker-images/Dockerfile_depictio_nb_debug.dockerfile
  #   ports:
  #     - 8888:8888
  #   volumes:
  #     - "${DEPICTIO_BACKEND_DATA_VOLUME_HOST}:${DEPICTIO_BACKEND_DATA_VOLUME_HOST}"
  #     - ../depictio:/app/depictio
  #     - ../data:/app/data
  #     - ../minio_data:/minio_data
  #     - ../jbrowse-watcher-plugin/sessions:/jbrowse-watcher-plugin/sessions
  #     - ../dev:/app/dev
  #     - ../.env:/app/.env
  #     - ../dev/jup_nb/.jupyter:/app/.jupyter
  #   depends_on:
  #     - mongo
  #     - minio
  #     - depictio_backend
  #     # - redis
  #     # - rabbitmq
  #   command: ["jupyter", "lab", "--config=/app/.jupyter/jupyter_notebook_config.py"]



  # redis:
  #   image: redis:latest
  #   command: redis-server
  #   ports:
  #     - 6379:6379

  # redis-cli-monitor:
  #   image: redis:latest
  #   command: redis-cli -h redis monitor
  #   depends_on:
  #     - redis

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
