"""Integration tests for ``validate_multiqc_reports_uniform`` against real MultiQC parquets.

Where the sibling ``test_multiqc_uniformity.py`` exercises the validator with
hand-built dicts, this file loads **real** parquet files generated by
MultiQC 1.31 from the dev fixture script and runs them through
``extract_multiqc_metadata`` before validation. The point is to prove that the
end-to-end parse-then-validate pipeline catches the mismatches that the unit
tests exercise in isolation, AND to keep on-disk artefacts the user can drag
into the Depictio UI for manual 422-path verification.

Fixtures are produced by::

    python dev/multiqc-multi-reports/generate_multi_run_reports.py --scenarios bad

They land under ``dev/multiqc-multi-reports/data/bad/`` (gitignored). When the
tree is missing, all tests in this file skip with a message pointing at that
command — CI without the fixtures stays green.
"""

from __future__ import annotations

from pathlib import Path

import pytest
from fastapi import HTTPException

from depictio.api.v1.endpoints.multiqc_endpoints.uniformity import (
    validate_multiqc_reports_uniform,
)

FIXTURE_ROOT = Path(__file__).resolve().parents[4] / "dev/multiqc-multi-reports/data/bad"

pytestmark = pytest.mark.skipif(
    not FIXTURE_ROOT.exists(),
    reason=(
        "Bad-scenario fixtures not generated. Run "
        "`python dev/multiqc-multi-reports/generate_multi_run_reports.py "
        "--scenarios bad` to create them under dev/multiqc-multi-reports/data/bad/."
    ),
)


def _scenario_parquets(scenario: str) -> tuple[Path, Path]:
    """Return the (run_a, run_b) parquet paths for a scenario directory."""
    scenario_dir = FIXTURE_ROOT / scenario
    pq_a = scenario_dir / "run_a/multiqc_data/multiqc.parquet"
    pq_b = scenario_dir / "run_b/multiqc_data/multiqc.parquet"
    if not pq_a.exists() or not pq_b.exists():
        pytest.skip(f"Missing parquet(s) for scenario '{scenario}' — regenerate fixtures.")
    return pq_a, pq_b


def _load_meta(parquet_path: Path) -> dict:
    """Parse a MultiQC parquet and wrap it in the Mongo-doc shape the real
    upload path uses.

    ``_replace_multiqc_dc_uploads`` / ``_append_multiqc_dc_uploads`` pass the
    validator a list of raw ``multiqc_collection`` documents — those have a
    distinct ``original_file_path`` per report plus the extracted fields under
    a nested ``metadata`` subdoc, plus ``multiqc_version`` at the top level.
    Without that wrapping the validator's ``_report_label`` falls back to
    ``"<unknown>"`` for every report, which makes the sample-uniqueness check
    treat duplicates as same-report repeats and silently skip them.
    """
    from depictio.cli.cli.utils.multiqc_processor import extract_multiqc_metadata

    extracted = extract_multiqc_metadata(str(parquet_path))
    return {
        "original_file_path": str(parquet_path),
        "multiqc_version": extracted.get("multiqc_version"),
        "metadata": {
            "samples": extracted.get("samples", []),
            "modules": extracted.get("modules", []),
            "plots": extracted.get("plots", {}),
        },
    }


class TestUniformityFromRealParquets:
    def test_ok_pair_passes(self):
        """Two structurally identical runs with disjoint samples → passes."""
        pq_a, pq_b = _scenario_parquets("ok_pair")
        meta_a = _load_meta(pq_a)
        meta_b = _load_meta(pq_b)
        validate_multiqc_reports_uniform([meta_a, meta_b])

    def test_modules_mismatch_raises(self):
        """run_b injects a samtools-stats log → module set is a superset."""
        pq_a, pq_b = _scenario_parquets("modules_mismatch")
        meta_a = _load_meta(pq_a)
        meta_b = _load_meta(pq_b)
        with pytest.raises(HTTPException) as exc_info:
            validate_multiqc_reports_uniform([meta_a, meta_b])
        assert exc_info.value.status_code == 422
        detail = exc_info.value.detail
        assert detail["code"] == "multiqc_report_mismatch"
        assert detail["kind"] == "modules"
        added = detail["details"]["added_in_compared"]
        removed = detail["details"]["removed_in_compared"]
        assert "samtools" in added or "samtools" in removed

    def test_plots_mismatch_raises(self):
        """run_b's FastQC data omits the adapter-content sub-section, so its
        flattened plot-id set is a strict subset of run_a's. The validator's
        ``_flat_plot_ids`` produces ``{"<module>::<plot>"}`` identifiers, so
        the missing plot surfaces even though both runs share the same
        top-level module key (``fastqc``).
        """
        pq_a, pq_b = _scenario_parquets("plots_mismatch")
        meta_a = _load_meta(pq_a)
        meta_b = _load_meta(pq_b)
        with pytest.raises(HTTPException) as exc_info:
            validate_multiqc_reports_uniform([meta_a, meta_b])
        detail = exc_info.value.detail
        assert detail["kind"] == "plots"
        removed = detail["details"]["removed_in_compared"]
        assert any("Adapter Content" in r for r in removed), (
            f"expected adapter-content plot id in removed_in_compared, got {removed}"
        )

    def test_samples_overlap_raises(self):
        """Both runs include the same sample name → 422 kind=samples."""
        pq_a, pq_b = _scenario_parquets("samples_overlap")
        meta_a = _load_meta(pq_a)
        meta_b = _load_meta(pq_b)
        with pytest.raises(HTTPException) as exc_info:
            validate_multiqc_reports_uniform([meta_a, meta_b])
        detail = exc_info.value.detail
        assert detail["kind"] == "samples"
        duplicates = detail["details"]["duplicate_samples"]
        # FastQC parsing splits paired-end reads into <sample>_R1 / <sample>_R2
        # samples. The fixture uses NA12878 as the shared name; assert at
        # least one of its FastQC-suffixed variants is flagged.
        assert any("NA12878" in dup for dup in duplicates), (
            f"expected NA12878 sample to appear in duplicates, got {list(duplicates)}"
        )

    def test_version_mismatch_raises(self):
        """run_b's parquet has its ``multiqc_version`` column rewritten to a
        different major.minor by the fixture generator. ``extract_multiqc_metadata``
        reads that column directly (not ``multiqc.__version__``), so the
        validator's version check fires from real on-disk data — no in-test
        override required.
        """
        pq_a, pq_b = _scenario_parquets("version_mismatch")
        meta_a = _load_meta(pq_a)
        meta_b = _load_meta(pq_b)
        assert meta_a["multiqc_version"] == "1.31"
        assert meta_b["multiqc_version"] == "1.21"
        with pytest.raises(HTTPException) as exc_info:
            validate_multiqc_reports_uniform([meta_a, meta_b])
        detail = exc_info.value.detail
        assert detail["kind"] == "version"
        assert detail["details"]["baseline_version"] == "1.31"
        assert detail["details"]["compared_version"] == "1.21"
