"""The depictio logo, as pixels for the CLI landing to draw in block characters.

Generated by scripts/generate_cli_logo.py: do not edit by hand. Regenerate with

    .venv/bin/python scripts/generate_cli_logo.py --size large=23x12 --size compact=18x9
"""

# The logo's own colours, by the letter its pixels use.
PALETTE = {
    "a": "#7F5FEE",
    "b": "#59B5CC",
    "c": "#BE63E2",
    "d": "#F09745",
    "e": "#627BF2",
    "f": "#A2D64E",
    "g": "#DE6E94",
    "h": "#F3C647",
}

# Each rendition's pixel rows, top to bottom, with '.' where the logo is transparent.
# "half" cells hold 1x2 pixels, "quadrant" cells 2x2; a cell never mixes more than
# two colours, nor a colour with a transparent pixel and a second colour.
LOGOS = {
    "large": {
        "glyphs": "half",
        "pixels": (
            "...............aaaaa...",
            "...............aaaaaaa.",
            "...............aaaaaaaa",
            "............c..aaaaaaaa",
            ".........cccc..aaaaaaa.",
            "........ccccc..aaaaaa..",
            "........ccccc..aaaaa...",
            ".........cccc..aaaa....",
            "..........ccc..aaa...ee",
            "...........cc..aa...eee",
            "............c..a...eeee",
            "........gg........eeeee",
            "........ggg......eeeeee",
            ".......................",
            ".......................",
            "bbbbbbbbbbb......dddddd",
            "bbbbbbbbbb........ddddd",
            "bbbbbbbbb...f..h...dddd",
            "bbbbbbbb...ff..hh...ddd",
            "bbbbbbb...fff..hhh...dd",
            ".bbbbb...ffff..h......d",
            ".bbbb...fffff..........",
            "..bb....fffff..........",
            ".........ffff..........",
        ),
    },
    "compact": {
        "glyphs": "half",
        "pixels": (
            "...........aaa....",
            "...........aaaaa..",
            "...........aaaaaa.",
            ".......ccc.aaaaa..",
            "......cccc.aaaa...",
            "......cccc.aaa....",
            ".......ccc.aa..ee.",
            "........cc.a..eee.",
            "......gg.....eeeee",
            "......gg....eeeeee",
            "..................",
            "bbbbbbbb....dddddd",
            "bbbbbbb....h.ddddd",
            "bbbbbb..ff.hh.ddd.",
            ".bbbb..fff.hh..dd.",
            ".bbb..ffff........",
            "..b...ffff........",
            "........ff........",
        ),
    },
}
