apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ .Release.Namespace }}
data:
  DEPICTIO_CONTEXT: {{ .Values.backend.env.DEPICTIO_CONTEXT | quote }}
  DEV_MODE: {{ .Values.backend.env.DEV_MODE | quote }}
  DEPICTIO_LOGGING_VERBOSITY_LEVEL: {{ .Values.backend.env.DEPICTIO_LOGGING_VERBOSITY_LEVEL | quote }}
  DEPICTIO_FASTAPI_PORT: {{ .Values.backend.env.DEPICTIO_FASTAPI_PORT | quote }}
  DEPICTIO_DASH_PORT: {{ .Values.backend.env.DEPICTIO_DASH_PORT | quote }}
  DEPICTIO_DASH_SERVICE_NAME: {{ .Values.backend.env.DEPICTIO_DASH_SERVICE_NAME | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: {{ .Release.Namespace }}
data:
  DEV_MODE: {{ .Values.frontend.env.DEV_MODE | quote }}
  DEPICTIO_FASTAPI_SERVICE_NAME: {{ .Values.frontend.env.DEPICTIO_FASTAPI_SERVICE_NAME | quote }}
  DEPICTIO_FASTAPI_PORT: {{ .Values.frontend.env.DEPICTIO_FASTAPI_PORT | quote }}
  DEPICTIO_DASH_PORT: {{ .Values.frontend.env.DEPICTIO_DASH_PORT | quote }}
