apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongo
  namespace: {{ .Release.Namespace }}
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      app: mongo
      project: {{ .Values.project.slug }}
      type: app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
        app: mongo
        project: {{ .Values.project.slug }}
        type: app
    spec:
      containers:
        - name: mongo
          image: "{{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}"
          imagePullPolicy: {{ .Values.mongo.image.pullPolicy }}
          args:
            - "mongod"
            - "--dbpath"
            - "/data/depictioDB"
            - "--port"
            - "27018"
          ports:
            - containerPort: {{ .Values.mongo.service.port }}
          resources:
            {{- toYaml .Values.mongo.resources | nindent 12 }}
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/depictioDB
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-mongo-pvc
---
{{- if .Values.minio.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-minio
  namespace: {{ .Release.Namespace }}
  labels:
    app: minio
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      app: minio
      project: {{ .Values.project.slug }}
      type: app
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
        app: minio
        project: {{ .Values.project.slug }}
        type: app
    spec:
      containers:
        - name: minio
          image: "{{ .Values.minio.image.repository }}:{{ .Values.minio.image.tag }}"
          imagePullPolicy: {{ .Values.minio.image.pullPolicy }}
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-depictio-secrets
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-depictio-secrets
                  key: MINIO_ROOT_PASSWORD
          args:
            - "server"
            - "/data"
          ports:
            - containerPort: {{ .Values.minio.service.httpPort }}
            - containerPort: {{ .Values.minio.service.consolePort }}
          resources:
            {{- toYaml .Values.minio.resources | nindent 12 }}
          volumeMounts:
            - name: minio-storage
              mountPath: /data
      volumes:
        - name: minio-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-minio-pvc
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-depictio-backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: depictio-backend
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      app: depictio-backend
      project: {{ .Values.project.slug }}
      type: app
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
        app: depictio-backend
        project: {{ .Values.project.slug }}
        type: app
    spec:
      securityContext:
        fsGroup: {{ .Values.backend.securityContext.fsGroup }}
      initContainers:
        - name: wait-for-mongo
          image: busybox:1.35
          command: ['sh', '-c', 'until nc -z {{ .Release.Name }}-mongo {{ .Values.mongo.service.port }}; do echo "Waiting for mongo..."; sleep 2; done']
        {{- if .Values.minio.enabled }}
        - name: wait-for-minio
          image: busybox:1.35
          command: ['sh', '-c', 'until nc -z {{ .Release.Name }}-minio {{ .Values.minio.service.httpPort }}; do echo "Waiting for minio..."; sleep 2; done']
        {{- end }}
      containers:
        - name: depictio-backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-backend-config
          env:
            - name: DEPICTIO_MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-depictio-secrets
                  key: MINIO_ROOT_USER
            - name: DEPICTIO_MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-depictio-secrets
                  key: MINIO_ROOT_PASSWORD
          command:
            - "/app/run_fastapi.sh"
          ports:
            - containerPort: {{ .Values.backend.service.targetPort }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          volumeMounts:
            - name: depictio-screenshots
              mountPath: /app/depictio/dash/static/screenshots
            - name: depictio-keys
              mountPath: /app/depictio/keys
      volumes:
        - name: depictio-screenshots
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-depictio-screenshots-pvc
        - name: depictio-keys
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-depictio-keys-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-depictio-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app: depictio-frontend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      app: depictio-frontend
      project: {{ .Values.project.slug }}
      type: app
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
        app: depictio-frontend
        project: {{ .Values.project.slug }}
        type: app
    spec:
      initContainers:
        - name: wait-for-backend
          image: busybox:1.35
          command: ['sh', '-c', 'until nc -z {{ .Release.Name }}-depictio-backend {{ .Values.backend.service.httpPort }}; do echo "Waiting for backend..."; sleep 2; done']
      containers:
        - name: depictio-frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-frontend-config
          env:
            - name: DEPICTIO_MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-depictio-secrets
                  key: MINIO_ROOT_USER
            - name: DEPICTIO_MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-depictio-secrets
                  key: MINIO_ROOT_PASSWORD
          command:
            - "/app/run_dash.sh"
          ports:
            - containerPort: {{ .Values.frontend.service.targetPort }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          volumeMounts:
            - name: depictio-screenshots
              mountPath: /app/depictio/dash/static/screenshots
            - name: depictio-keys
              mountPath: /app/depictio/keys
      volumes:
        - name: depictio-screenshots
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-depictio-screenshots-pvc
        - name: depictio-keys
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-depictio-keys-pvc
