apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: {{ .Release.Namespace }}
  labels: 
    app: mongo
spec:
  storageClassName: {{ .Values.storageClass }}
  accessModes:
    - {{ .Values.persistence.mongo.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.mongo.size }}
---
{{- if .Values.minio.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: {{ .Release.Namespace }}
  labels: 
    app: minio
spec:
  storageClassName: {{ .Values.storageClass }}
  accessModes:
    - {{ .Values.persistence.minio.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.minio.size }}
{{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: depictio-screenshots-pvc
  namespace: {{ .Release.Namespace }}
  labels: 
    app: depictio
    # component: storage
    # storage-type: screenshots
spec:
  storageClassName: {{ .Values.storageClass }}
  accessModes:
    - {{ .Values.persistence.screenshots.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.screenshots.size }}