apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: {{ .Release.Namespace }}
  labels: 
    {{- include "depictio.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.storageClass }}
  accessModes:
    - {{ .Values.persistence.mongo.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.mongo.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: {{ .Release.Namespace }}
  labels: 
    {{- include "depictio.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.storageClass }}
  accessModes:
    - {{ .Values.persistence.minio.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.minio.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: depictio-screenshots-pvc
  namespace: {{ .Release.Namespace }}
  labels: 
    {{- include "depictio.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.storageClass }}
  accessModes:
    - {{ .Values.persistence.screenshots.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.screenshots.size }}
