apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-depictio-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: depictio
    component: secrets
type: Opaque
# {{- $access := default .Release.Name .Values.secrets.minioRootUser }}
# {{- $secret := default (randAlphaNum 32) .Values.secrets.minioRootPassword }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-depictio-secrets" .Release.Name)) }}
{{- $access := default .Release.Name .Values.secrets.minioRootUser }}
data:
  MINIO_ROOT_USER: {{ $access | b64enc | quote }}
  {{- if and $secret $secret.data $secret.data.MINIO_ROOT_PASSWORD }}
  MINIO_ROOT_PASSWORD: {{ $secret.data.MINIO_ROOT_PASSWORD | quote }}
  {{- else if .Values.secrets.minioRootPassword }}
  MINIO_ROOT_PASSWORD: {{ .Values.secrets.minioRootPassword | b64enc | quote }}
  {{- else }}
  MINIO_ROOT_PASSWORD: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
