apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-depictio-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: depictio
    component: secrets
type: Opaque
{{- $access := default .Release.Name .Values.secrets.minioRootUser }}
{{- $secret := default (randAlphaNum 32) .Values.secrets.minioRootPassword }}
data:
  MINIO_ROOT_USER: {{ $access | b64enc }}
  MINIO_ROOT_PASSWORD: {{ $secret | b64enc }}
  MINIO_ACCESS_KEY: {{ $access | b64enc }}
  MINIO_SECRET_KEY: {{ $secret | b64enc }}
