apiVersion: v1
kind: Secret
metadata:
  name: depictio-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: depictio
    component: secrets
type: Opaque
data:
  MINIO_ROOT_USER: {{ .Values.secrets.minioRootUser | b64enc }}
  MINIO_ROOT_PASSWORD: {{ .Values.secrets.minioRootPassword | b64enc }}
