# MongoDB Regular Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongo
  namespace: {{ .Release.Namespace }}
  # labels:
  #   app: mongo
spec:
  type: {{ .Values.mongo.service.type }}
  ports:
    - name: db
      port: {{ .Values.mongo.service.port }}
      targetPort: {{ .Values.mongo.service.port }}
  selector:
    release: {{ .Release.Name }}
    app: mongo
    project: {{ .Values.project.slug }}
    type: app
---
# MongoDB Headless Service (for StatefulSet replica set discovery)
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongo-headless
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  ports:
    - name: db
      port: {{ .Values.mongo.service.port }}
      targetPort: {{ .Values.mongo.service.port }}
  selector:
    release: {{ .Release.Name }}
    app: mongo
    project: {{ .Values.project.slug }}
    type: app
---
{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-minio
  namespace: {{ .Release.Namespace }}
  # labels:
  #   app: minio
spec:
  type: {{ .Values.minio.service.type }}
  ports:
    - port: {{ .Values.minio.service.httpPort }}
      name: http
      targetPort: {{ .Values.minio.service.httpPort }}
    - port: {{ .Values.minio.service.consolePort }}
      name: console
      targetPort: {{ .Values.minio.service.consolePort }}
  selector:
    release: {{ .Release.Name }}
    app: minio
    project: {{ .Values.project.slug }}
    type: app
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-depictio-backend
  namespace: {{ .Release.Namespace }}
  # labels:
  #   app: depictio-backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.httpPort }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.backend.service.httpsPort }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: https
  selector:
    release: {{ .Release.Name }}
    app: depictio-backend
    project: {{ .Values.project.slug }}
    type: app
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-depictio-frontend
  namespace: {{ .Release.Namespace }}
  # labels:
  #   app: depictio-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.httpPort }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.frontend.service.httpsPort }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: https
  selector:
    release: {{ .Release.Name }}
    app: depictio-frontend
    project: {{ .Values.project.slug }}
    type: app
