{{- if .Values.mongo.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "depictio.labels" . | nindent 4 }}
spec:
  ports:
    - name: db
      port: {{ .Values.mongo.service.port }}
      targetPort: {{ .Values.mongo.service.port }}
  selector:
    {{- include "depictio.mongo.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "depictio.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.minio.service.httpPort }}
      name: http
      targetPort: {{ .Values.minio.service.httpPort }}
    - port: {{ .Values.minio.service.consolePort }}
      name: console
      targetPort: {{ .Values.minio.service.consolePort }}
  selector:
    {{- include "depictio.minio.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: depictio-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "depictio.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.backend.service.httpPort }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.backend.service.httpsPort }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: https
  selector:
    {{- include "depictio.backend.selectorLabels" . | nindent 4 }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    run: {{ .Release.Name }}-depictio
spec:
  ports:
    - port: {{ .Values.frontend.service.httpPort }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    release: {{ $.Release.Name }}