#!/usr/bin/env python3
"""
Generate multiple MultiQC parquet reports in a run-oriented structure.

Produces 10 sequencing runs (run_01 .. run_10), each with 3-5 paired-end
FASTQ samples and a corresponding multiqc.parquet file generated by MultiQC 1.31.

Usage:
    python generate_multi_run_reports.py [--output-dir ./data] [--seed 42]
"""

from __future__ import annotations

import argparse
import math
import os
import random
import shutil
import tempfile
from pathlib import Path

import multiqc
from multiqc.core.update_config import ClConfig

# ---------------------------------------------------------------------------
# Sample definitions per run
# ---------------------------------------------------------------------------

RUN_SAMPLES: dict[str, list[str]] = {
    "run_01": ["NA12878", "NA12891", "NA12892"],
    "run_02": ["HG001", "HG002", "HG003", "HG004"],
    "run_03": ["GM12878", "GM18507", "GM19240", "K562", "HeLa"],
    "run_04": ["PATIENT_001", "PATIENT_002", "PATIENT_003"],
    "run_05": ["PATIENT_010", "PATIENT_011", "PATIENT_012", "PATIENT_013"],
    "run_06": ["DONOR_A", "DONOR_B", "DONOR_C", "DONOR_D", "DONOR_E"],
    "run_07": ["PROJ_WGS_S1", "PROJ_WGS_S2", "PROJ_WGS_S3"],
    "run_08": ["RNASEQ_LIB01", "RNASEQ_LIB02", "RNASEQ_LIB03", "RNASEQ_LIB04"],
    "run_09": ["EXOME_A1", "EXOME_A2", "EXOME_B1", "EXOME_B2", "EXOME_B3"],
    "run_10": ["CTRL_POS", "CTRL_NEG", "LIBRARY_QC1", "LIBRARY_QC2"],
}

# Per-run sequencing characteristics
RUN_PROFILES: dict[str, dict] = {
    "run_01": {"read_length": 150, "depth_range": (20_000_000, 40_000_000), "gc_center": 42},
    "run_02": {"read_length": 150, "depth_range": (25_000_000, 50_000_000), "gc_center": 44},
    "run_03": {"read_length": 150, "depth_range": (15_000_000, 35_000_000), "gc_center": 46},
    "run_04": {"read_length": 150, "depth_range": (10_000_000, 30_000_000), "gc_center": 43},
    "run_05": {"read_length": 100, "depth_range": (5_000_000, 15_000_000), "gc_center": 48},
    "run_06": {"read_length": 150, "depth_range": (30_000_000, 60_000_000), "gc_center": 41},
    "run_07": {"read_length": 150, "depth_range": (40_000_000, 80_000_000), "gc_center": 45},
    "run_08": {"read_length": 100, "depth_range": (8_000_000, 20_000_000), "gc_center": 50},
    "run_09": {"read_length": 150, "depth_range": (20_000_000, 45_000_000), "gc_center": 44},
    "run_10": {"read_length": 150, "depth_range": (1_000_000, 5_000_000), "gc_center": 47},
}


# ---------------------------------------------------------------------------
# FastQC data generation
# ---------------------------------------------------------------------------


def _generate_quality_per_base(read_length: int, is_r2: bool) -> str:
    """Generate Per base sequence quality module data."""
    lines = [">>Per base sequence quality\tpass"]
    lines.append(
        "#Base\tMean\tMedian\tLower Quartile\tUpper Quartile\t10th Percentile\t90th Percentile"
    )

    base_quality = 35.0 if not is_r2 else 33.0
    for pos in range(1, read_length + 1):
        # Quality drops slightly at the start and more toward the end
        if pos <= 5:
            decay = (5 - pos) * 0.4
        elif pos > read_length * 0.8:
            decay = (pos - read_length * 0.8) / (read_length * 0.2) * 6.0
        else:
            decay = 0.0
        mean_q = base_quality - decay + random.gauss(0, 0.3)
        mean_q = max(20.0, min(40.0, mean_q))
        median_q = mean_q + random.uniform(0, 1)
        lq = mean_q - random.uniform(1.5, 3.0)
        uq = mean_q + random.uniform(0.5, 2.0)
        p10 = mean_q - random.uniform(3.0, 6.0)
        p90 = mean_q + random.uniform(1.0, 3.0)
        lines.append(
            f"{pos}\t{mean_q:.1f}\t{median_q:.1f}\t{lq:.1f}\t{uq:.1f}\t{p10:.1f}\t{p90:.1f}"
        )

    lines.append(">>END_MODULE")
    return "\n".join(lines)


def _generate_quality_per_seq() -> str:
    """Generate Per sequence quality scores module data."""
    lines = [">>Per sequence quality scores\tpass"]
    lines.append("#Quality\tCount")
    # Bell curve peaking around Q36
    for q in range(2, 41):
        count = max(0.0, math.exp(-0.5 * ((q - 36) / 3.0) ** 2) * 50000)
        count += random.uniform(0, count * 0.05)
        lines.append(f"{q}\t{count:.1f}")
    lines.append(">>END_MODULE")
    return "\n".join(lines)


def _generate_base_content(read_length: int) -> str:
    """Generate Per base sequence content module data."""
    lines = [">>Per base sequence content\tpass"]
    lines.append("#Base\tG\tA\tT\tC")
    for pos in range(1, read_length + 1):
        # Slight bias in first few bases (typical Illumina)
        bias = max(0, (10 - pos) * 0.3)
        g = 25.0 + random.gauss(0, 0.3) + bias * 0.5
        a = 25.0 + random.gauss(0, 0.3) - bias * 0.3
        t = 25.0 + random.gauss(0, 0.3) - bias * 0.1
        c = 100.0 - g - a - t
        lines.append(f"{pos}\t{g:.1f}\t{a:.1f}\t{t:.1f}\t{c:.1f}")
    lines.append(">>END_MODULE")
    return "\n".join(lines)


def _generate_gc_content(gc_center: int) -> str:
    """Generate Per sequence GC content module data."""
    lines = [">>Per sequence GC content\tpass"]
    lines.append("#GC Content\tCount")
    for gc in range(0, 101):
        count = max(0.0, math.exp(-0.5 * ((gc - gc_center) / 8.0) ** 2) * 30000)
        count += random.uniform(0, max(1.0, count * 0.02))
        lines.append(f"{gc}\t{count:.1f}")
    lines.append(">>END_MODULE")
    return "\n".join(lines)


def _generate_seq_length_dist(read_length: int) -> str:
    """Generate Sequence Length Distribution module data."""
    lines = [">>Sequence Length Distribution\tpass"]
    lines.append("#Length\tCount")
    lines.append(f"{read_length}\t{random.randint(1000000, 50000000)}.0")
    lines.append(">>END_MODULE")
    return "\n".join(lines)


def _generate_duplication(dedup_pct: float) -> str:
    """Generate Sequence Duplication Levels module data."""
    lines = [">>Sequence Duplication Levels\tpass"]
    lines.append(f"#Total Deduplicated Percentage\t{dedup_pct:.1f}")
    lines.append("#Duplication Level\tPercentage of deduplicated\tPercentage of total")
    remaining = 100.0
    for level in [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        ">10",
        ">50",
        ">100",
        ">500",
        ">1k",
        ">5k",
        ">10k+",
    ]:
        if level == 1:
            pct_dedup = dedup_pct
        elif isinstance(level, int) and level <= 5:
            pct_dedup = random.uniform(1.0, (100 - dedup_pct) / 3)
        else:
            pct_dedup = random.uniform(0.0, 2.0)
        pct_dedup = min(pct_dedup, remaining)
        remaining -= pct_dedup
        pct_total = pct_dedup * (int(level) if isinstance(level, int) else 100) / 100
        lines.append(f"{level}\t{pct_dedup:.2f}\t{pct_total:.2f}")
    lines.append(">>END_MODULE")
    return "\n".join(lines)


def _generate_adapter_content(read_length: int) -> str:
    """Generate Adapter Content module data."""
    lines = [">>Adapter Content\tpass"]
    lines.append(
        "#Position\tIllumina Universal Adapter\tIllumina Small RNA 3' Adapter"
        "\tIllumina Small RNA 5' Adapter\tNextera Transposase Sequence"
    )
    for pos in range(1, read_length + 1):
        # Adapter contamination increases toward end of read
        frac = pos / read_length
        univ = frac**3 * random.uniform(0.5, 2.0)
        small3 = frac**4 * random.uniform(0.0, 0.3)
        small5 = frac**4 * random.uniform(0.0, 0.1)
        nextera = frac**3 * random.uniform(0.0, 0.5)
        lines.append(f"{pos}\t{univ:.4f}\t{small3:.4f}\t{small5:.4f}\t{nextera:.4f}")
    lines.append(">>END_MODULE")
    return "\n".join(lines)


def generate_fastqc_data(
    sample_name: str,
    read: int,
    total_sequences: int,
    read_length: int,
    gc_pct: int,
) -> str:
    """Generate a complete fastqc_data.txt for one FASTQ file."""
    is_r2 = read == 2
    filename = f"{sample_name}_R{read}.fastq.gz"
    dedup_pct = random.uniform(70.0, 95.0)

    sections = []

    # Basic Statistics
    sections.append(
        f"##FastQC\t0.12.1\n"
        f">>Basic Statistics\tpass\n"
        f"#Measure\tValue\n"
        f"Filename\t{filename}\n"
        f"File type\tConventional base calls\n"
        f"Encoding\tSanger / Illumina 1.9\n"
        f"Total Sequences\t{total_sequences}\n"
        f"Sequences flagged as poor quality\t{random.randint(0, int(total_sequences * 0.001))}\n"
        f"Sequence length\t{read_length}\n"
        f"%GC\t{gc_pct}\n"
        f">>END_MODULE"
    )

    sections.append(_generate_quality_per_base(read_length, is_r2))
    sections.append(_generate_quality_per_seq())
    sections.append(_generate_base_content(read_length))
    sections.append(_generate_gc_content(gc_pct))
    sections.append(_generate_seq_length_dist(read_length))
    sections.append(_generate_duplication(dedup_pct))
    sections.append(_generate_adapter_content(read_length))

    return "\n".join(sections) + "\n"


# ---------------------------------------------------------------------------
# Run generation
# ---------------------------------------------------------------------------


def generate_run(
    run_name: str,
    samples: list[str],
    profile: dict,
    output_dir: Path,
    rng: random.Random,
) -> Path:
    """Generate FastQC data for a run and produce a MultiQC parquet."""
    read_length: int = profile["read_length"]
    depth_lo, depth_hi = profile["depth_range"]
    gc_center: int = profile["gc_center"]

    # Create temp directory for FastQC inputs
    tmp_input = tempfile.mkdtemp(prefix=f"mqc_input_{run_name}_")

    try:
        for sample in samples:
            total_seqs = rng.randint(depth_lo, depth_hi)
            gc_pct = gc_center + rng.randint(-3, 3)

            for read_num in (1, 2):
                fastqc_dir = os.path.join(tmp_input, f"{sample}_R{read_num}_fastqc")
                os.makedirs(fastqc_dir)
                data = generate_fastqc_data(sample, read_num, total_seqs, read_length, gc_pct)
                with open(os.path.join(fastqc_dir, "fastqc_data.txt"), "w") as f:
                    f.write(data)

        # Run MultiQC to generate parquet
        run_output = output_dir / run_name
        run_output.mkdir(parents=True, exist_ok=True)

        multiqc.reset()
        cfg = ClConfig(
            output_dir=str(run_output),
            force=True,
            quiet=True,
            make_report=False,
            no_megaqc_upload=True,
        )
        multiqc.run(tmp_input, cfg=cfg)

        parquet_path = run_output / "multiqc_data" / "multiqc.parquet"
        return parquet_path

    finally:
        shutil.rmtree(tmp_input, ignore_errors=True)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate multi-run MultiQC parquet reports")
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path(__file__).parent / "data",
        help="Output directory for run data (default: ./data)",
    )
    parser.add_argument("--seed", type=int, default=42, help="Random seed for reproducibility")
    args = parser.parse_args()

    rng = random.Random(args.seed)
    random.seed(args.seed)

    output_dir: Path = args.output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    print(f"Generating 10 MultiQC runs in {output_dir}\n")
    print(f"{'Run':<12} {'Samples':>8} {'Paired FQs':>11} {'Parquet Size':>13}")
    print("-" * 48)

    for run_name in sorted(RUN_SAMPLES):
        samples = RUN_SAMPLES[run_name]
        profile = RUN_PROFILES[run_name]

        parquet_path = generate_run(run_name, samples, profile, output_dir, rng)

        if parquet_path.exists():
            size_kb = parquet_path.stat().st_size / 1024
            print(f"{run_name:<12} {len(samples):>8} {len(samples) * 2:>11} {size_kb:>10.1f} KB")
        else:
            print(f"{run_name:<12} {len(samples):>8} {len(samples) * 2:>11}   FAILED")

    print(f"\nDone. Parquet files at: {output_dir}/run_*/multiqc_data/multiqc.parquet")

    # Quick verification
    try:
        import polars as pl

        print("\n--- Verification ---")
        for run_name in sorted(RUN_SAMPLES):
            pq = output_dir / run_name / "multiqc_data" / "multiqc.parquet"
            if pq.exists():
                df = pl.read_parquet(pq)
                sample_col = df.filter(pl.col("sample").is_not_null())["sample"].unique().to_list()
                print(f"{run_name}: {df.shape[0]} rows, samples: {sorted(sample_col)}")
    except ImportError:
        pass


if __name__ == "__main__":
    main()
