#!/usr/bin/env python3
"""Generate ``docs/telemetry.md`` from the telemetry payload schema.

Documentation that can drift from the code is worse than no documentation when the
subject is "what data do we send about you". So the field tables are generated from
the pydantic models in :mod:`depictio.telemetry.schema`, which are also what the
runtime validates against. Adding a field without documenting it is not possible;
the field appears in the generated table automatically, and ``--check`` fails CI if
the committed file is stale.

Usage::

    python scripts/gen_telemetry_docs.py           # write docs/telemetry.md
    python scripts/gen_telemetry_docs.py --check   # exit 1 if the file is stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from depictio.telemetry.buckets import LABELS  # noqa: E402
from depictio.telemetry.constants import DEFAULT_ENDPOINT  # noqa: E402
from depictio.telemetry.schema import (  # noqa: E402
    EVENT_CLI_COMMAND,
    EVENT_HEARTBEAT,
    EVENT_INSTALL,
    CliCommandProperties,
    CommonProperties,
    FeatureFlags,
    ServerHeartbeatProperties,
    UsageBuckets,
)

OUTPUT_PATH = REPO_ROOT / "docs" / "telemetry.md"

GENERATED_MARKER = (
    "<!-- The field tables below are generated by scripts/gen_telemetry_docs.py "
    "from depictio/telemetry/schema.py. Do not edit them by hand. -->"
)


_SCALARS = {"str": "string", "bool": "boolean", "int": "integer", "float": "number"}


def _type_label(annotation: Any) -> str:
    """Render a field annotation as something a reader recognises.

    Pipes are escaped: an unescaped ``|`` from an optional type would be read as a
    markdown cell separator and silently shift every following column.
    """
    name = getattr(annotation, "__name__", None)
    if name in _SCALARS:
        return _SCALARS[name]

    # A nested model class: use its bare name, not its ``<class '...'>`` repr.
    if isinstance(annotation, type):
        return name or str(annotation)

    text = str(annotation).replace("typing.", "")
    text = text.replace("depictio.telemetry.schema.", "")
    text = text.replace("<class '", "").replace("'>", "")
    if text.startswith("dict[str, str]"):
        return "object (string → string)"
    if text.startswith("list[str]"):
        return "array of strings"
    # ``X | None`` reads better as "optional X", and drops the problematic pipe.
    if text.endswith(" | None"):
        return f"{text.removesuffix(' | None')}, optional"
    return text.replace("|", r"\|")


def _field_table(model: type, *, skip: set[str] | None = None) -> str:
    """Render one pydantic model's fields as a markdown table."""
    skip = skip or set()
    lines = ["| Field | Type | What it is |", "| --- | --- | --- |"]
    for name, field in model.model_fields.items():
        if name in skip:
            continue
        description = (field.description or "").replace("\n", " ").strip()
        lines.append(f"| `{name}` | {_type_label(field.annotation)} | {description} |")
    return "\n".join(lines)


def render() -> str:
    """Build the full document."""
    common_fields = set(CommonProperties.model_fields)
    buckets = ", ".join(f"`{label}`" for label in LABELS)

    return f"""# Telemetry

Depictio sends an **anonymous, aggregate** report about each installation so the
project can tell how many deployments exist, which versions are running, and which
features get used.

This page describes exactly what is sent, why, and how to turn it off.

{GENERATED_MARKER}

## Why this exists

Depictio is distributed four ways — Docker Compose, a Helm chart, the
`depictio-cli` PyPI package, and the browser-based Tools Studio — and until this
existed, none of them reported anything. The container images and the Helm chart
are hosted on GitHub Container Registry, which (unlike Docker Hub) publishes **no
pull counts at all**, and PyPI download numbers conflate CI runs, mirrors and
repeated installs. The practical effect was that nobody could answer "is anyone
using this?", which makes it impossible to justify effort, retire features safely,
or know which versions still need support.

## What is sent

Three events. Nothing else.

| Event | When |
| --- | --- |
| `{EVENT_INSTALL}` | Once per installation, ever. |
| `{EVENT_HEARTBEAT}` | At most once per UTC day per installation — regardless of how many workers or replicas are running. |
| `{EVENT_CLI_COMMAND}` | Once per `depictio-cli` invocation. |

Each event is identified by a random **installation ID** (server) or a random
**anonymous ID** (CLI). Neither is derived from anything about you, your machine or
your users — they are freshly generated UUIDs, stored so that repeat reports from
one installation are not counted as many.

### Properties on every event

{_field_table(CommonProperties)}

### `{EVENT_INSTALL}` and `{EVENT_HEARTBEAT}`

{_field_table(ServerHeartbeatProperties, skip=common_fields)}

#### `features`

Booleans only — which optional subsystems are switched on.

{_field_table(FeatureFlags)}

#### `usage`

Every value is a **coarse bucket label**, never an exact count: {buckets}, or
`unknown` when a value could not be computed.

Exact numbers are deliberately not sent. A deployment reporting precise sizes
across eight dimensions is close to uniquely identifiable even with no name
attached; the bucket answers the only question we actually have — roughly how big
is it — while leaving the installation in a group with many others.

{_field_table(UsageBuckets)}

### `{EVENT_CLI_COMMAND}`

{_field_table(CliCommandProperties, skip=common_fields)}

The `command` field deserves a note. A CLI's arguments routinely contain file
paths, project names, S3 URIs and occasionally a credential pasted into the wrong
flag. Rather than attempt to strip those out, the command path is **reconstructed
from the CLI's own command tree**: a token is kept only if it names a registered
command or sub-command, and the first token that does not ends the reconstruction.
So `depictio-cli data process --project-config /home/alice/cohort.yaml` reports
exactly `data process`. A sanitiser has to anticipate every bad input; this cannot
emit a string that is not already a command name in Depictio's source.

## What is never sent

* Email addresses, usernames, or any user identity
* Project, dashboard, workflow, data collection or column names
* Hostnames, domain names, URLs or IP addresses
* File paths, S3 endpoints or bucket names
* Tokens, passwords or any secret
* Google Analytics measurement IDs
* Anything a user typed, including CLI arguments
* Any of your actual data, in any form

The payload schema forbids undeclared fields, so a future change cannot quietly
add one of these: it would have to be declared in
`depictio/telemetry/schema.py`, where it would appear in the table above and trip
the payload-allowlist test in `depictio/tests/api/v1/test_telemetry.py`.

## Verify it yourself

Do not take the above on trust. On your own deployment, as an admin:

```bash
curl -H "Authorization: Bearer $YOUR_TOKEN" \\
  https://your-depictio/depictio/api/v1/utils/telemetry/preview
```

That returns the real payload, built by the same code that sends it, together with
whether telemetry is currently enabled and why not if it isn't. Reading it does not
consume the day's report.

To watch without transmitting anything, set `DEPICTIO_TELEMETRY_DEBUG=true`. Every
payload is then written to the application log instead of being sent.

## How to turn it off

Any one of these is enough:

```bash
DEPICTIO_TELEMETRY_ENABLED=false   # Depictio-specific
DO_NOT_TRACK=1                     # cross-tool convention, see consoledonottrack.com
```

For Docker Compose, put either in your `.env`. For Kubernetes:

```bash
helm upgrade depictio ./helm-charts/depictio \\
  --set backend.env.DEPICTIO_TELEMETRY_ENABLED=false
```

To keep the installation count but drop the size metrics:

```bash
DEPICTIO_TELEMETRY_INCLUDE_USAGE_METRICS=false
```

### Automatically disabled

No configuration needed — telemetry suppresses itself when:

* `DO_NOT_TRACK` is set
* An automated build is detected (`CI`, `GITHUB_ACTIONS`, `GITLAB_CI` and similar)
* Running under pytest, or with `DEPICTIO_DEV_MODE=true`
* The deployment booted with `DEPICTIO_MONGODB_WIPE` set
* No collector key is configured

CI suppression matters for accuracy, not just courtesy: Depictio's own workflows
boot the API on nearly every run, and users' pipelines invoke the CLI on every
commit. Counted, automation would swamp real installations.

The development Compose stack (`docker-compose.dev.yaml`) also ships with
telemetry off, since that file is what maintainers and contributors run.

## Where it goes

Events are sent to PostHog Cloud's **EU** region (`{DEFAULT_ENDPOINT}`), so
event data stays inside the EEA. The project token embedded in Depictio is a
public, write-only ingestion key — it grants no read access to anything.

Every event is flagged `$process_person_profile: false`, so the collector stores
no person profile for your installation. There is no user record on the receiving
end to enrich, segment or export — only counts.

## All configuration

| Variable | Default | Effect |
| --- | --- | --- |
| `DEPICTIO_TELEMETRY_ENABLED` | `true` | Master switch. |
| `DO_NOT_TRACK` | unset | Cross-tool opt-out; any meaningful value disables telemetry. |
| `DEPICTIO_TELEMETRY_INCLUDE_USAGE_METRICS` | `true` | Include the bucketed `usage` block. |
| `DEPICTIO_TELEMETRY_DEBUG` | `false` | Log payloads instead of sending them. |
| `DEPICTIO_TELEMETRY_INTERVAL_HOURS` | `24` | Hours between heartbeat attempts. |
| `DEPICTIO_TELEMETRY_DEPLOYMENT_KIND` | auto-detected | Override the reported deployment kind. |
| `DEPICTIO_TELEMETRY_ENDPOINT` | PostHog Cloud EU | Point events at your own collector. |
| `DEPICTIO_TELEMETRY_API_KEY` | (built in) | Collector project token. |
| `DEPICTIO_TELEMETRY_STATE_DIR` | `~/.depictio` | Where the CLI stores its anonymous ID. |

## Not to be confused with

Depictio has three separate systems with similar names. Only the first sends
anything to the Depictio maintainers:

1. **`DEPICTIO_TELEMETRY_*`** — this page. Anonymous installation counting.
   Enabled by default.
2. **`DEPICTIO_ANALYTICS_*`** — Depictio's own per-user session and activity
   tracking, stored in *your* MongoDB and surfaced in *your* admin UI. Never
   transmitted anywhere. Disabled by default.
3. **`DEPICTIO_GOOGLE_ANALYTICS_*`** — optional GA4 tracking in the web frontend.
   Data goes to *your* GA4 property, not to us. Disabled by default.

## Known limitation

Restoring a MongoDB backup into a second environment clones the installation ID, so
a production database copied into staging reports as one installation from two
places. The `boot_id` property makes this visible in the data rather than silently
wrong. We have not tried to engineer around it; a heuristic that re-mints IDs would
risk over-counting legitimate restores, which is the worse failure.
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the committed file differs from what would be generated.",
    )
    args = parser.parse_args()

    rendered = render()

    if args.check:
        if not OUTPUT_PATH.exists():
            print(f"{OUTPUT_PATH} is missing. Run: python scripts/gen_telemetry_docs.py")
            return 1
        if OUTPUT_PATH.read_text(encoding="utf-8") != rendered:
            print(
                f"{OUTPUT_PATH} is out of date with depictio/telemetry/schema.py.\n"
                "Regenerate it with: python scripts/gen_telemetry_docs.py"
            )
            return 1
        print(f"{OUTPUT_PATH} is up to date.")
        return 0

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(rendered, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
