#!/usr/bin/env python3
"""Exercise the 1.10.0 Nextflow completion handler without running a pipeline.

Maintainer tool (not shipped with ``depictio-cli``). ``depictio.config`` installs a
``workflow.onComplete`` handler that turns a finished pipeline into a
``depictio-cli run`` invocation. Everything it does is decided from
``workflow.manifest`` and ``params``, so none of it needs a pipeline to have
actually run: a ten-line workflow carrying the right manifest exercises the same
path in seconds.

That separation is the point. Whether nf-core/rnaseq produces the files a
template wants is one question, answered by running it on the cluster
(``scripts/nfcore_validation_hpc.py``). Whether the handler turns a completed run
into the right command is a different one, answered here, for all fourteen
template directories at once.

Two modes, neither of which writes to a Depictio instance:

``echo`` (default)
    ``params.depictio_cli_executable = ['echo']``. The handler builds its argv and
    hands it to ``echo``, so the assembled command is printed and asserted on.
    Proves the manifest is read, ``--pipeline-id`` is forwarded verbatim, the data
    root is absolutised and the flags are the expected ones.

``dry-run``
    A generated wrapper that appends ``--dry-run`` to the real CLI. The handler
    always puts ``run`` immediately after the executable, so ``--dry-run`` cannot
    be injected through ``depictio_cli_executable`` alone. This mode reaches
    ``locate_template()`` and therefore proves template *resolution*, including
    that an unknown version fails instead of silently falling back to the latest.

Usage::

    python scripts/nfcore_trigger_stub.py list
    python scripts/nfcore_trigger_stub.py run --mode echo
    python scripts/nfcore_trigger_stub.py run --mode echo --case ampliseq/2.17.0
    python scripts/nfcore_trigger_stub.py run --mode dry-run --data-root ~/Data/...

Exit codes: 0 every case matched its expectation, 1 at least one did not, 2 usage.
"""

from __future__ import annotations

import argparse
import os
import re
import shlex
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[1]
NFCORE_PROJECTS_DIR = _REPO_ROOT / "depictio" / "projects" / "nf-core"
DEFAULT_DEPICTIO_CONFIG = Path("~/.depictio/nextflow.config").expanduser()

# Versions nf-core released but Depictio ships no template directory for. The
# trigger forwards manifest.version verbatim and locate_template() has no
# fallback, so these must fail loudly rather than resolve to a neighbour.
NEGATIVE_CASES = [
    ("ampliseq", "2.17.0"),
    ("ampliseq", "2.15.0"),
    ("rnaseq", "3.25.0"),
    # Not a hypothetical: nf-core tagged atacseq 1.2.2 without bumping its
    # manifest, so a `-r 1.2.2` run reports version 1.2.1 and the trigger forwards
    # that. The template directory is 1.2.2, so the run cannot resolve - and no
    # revision pin fixes it, because the manifest is what gets forwarded.
    ("atacseq", "1.2.1"),
]


@dataclass
class Case:
    pipeline: str
    version: str
    should_resolve: bool

    @property
    def name(self) -> str:
        return f"{self.pipeline}/{self.version}"

    @property
    def pipeline_id(self) -> str:
        return f"nf-core/{self.pipeline}/{self.version}"


def discover_cases(include_negative: bool = True) -> list[Case]:
    """Every template directory, plus the released versions that have none."""
    cases = [
        Case(path.parent.parent.name, path.parent.name, True)
        for path in sorted(NFCORE_PROJECTS_DIR.glob("*/*/template.yaml"))
    ]
    if include_negative:
        cases += [Case(pipeline, version, False) for pipeline, version in NEGATIVE_CASES]
    return cases


def _log(message: str) -> None:
    print(message, file=sys.stderr, flush=True)


def _groovy(value: str) -> str:
    """Quote for the Nextflow config parser, which is Groovy and not a shell.

    shlex.quote leaves an unremarkable path bare, and a bare path is a syntax
    error in a config file rather than a string.
    """
    return "'" + str(value).replace("\\", "\\\\").replace("'", "\\'") + "'"


def write_stub(workdir: Path, case: Case, data_root: Path, config: Path, executable: str) -> None:
    """A workflow that does nothing, wearing the manifest of the pipeline under test."""
    (workdir / "main.nf").write_text("#!/usr/bin/env nextflow\n\nworkflow {\n}\n")
    (workdir / "nextflow.config").write_text(
        f"""// Generated by scripts/nfcore_trigger_stub.py - do not edit.
manifest {{
    name    = 'nf-core/{case.pipeline}'
    version = '{case.version}'
}}

params.outdir = {_groovy(str(data_root))}
params.depictio_cli_executable = {executable}

// Last -c wins outright in Nextflow, so the handler is included AFTER the
// params above, exactly as the file's own documentation requires.
includeConfig {_groovy(str(config))}
"""
    )


_DEPICTIO_LINE = re.compile(r"\[depictio\]\s?(.*)")


def make_fixture_root(workdir: Path) -> Path:
    """A minimal DATA_ROOT: just enough for the resolver's auto-detection to fire.

    The resolver fills SAMPLESHEET_FILE from <data_root>/input/ when the template
    does not declare it, and ampliseq 2.14.0 marks that variable required, so a
    data root with no input/ makes 2.14.0 fail for a reason that has nothing to do
    with the handler under test. A fixture keeps the two questions apart; pass
    --data-root to point at a real run instead.
    """
    root = workdir / "fixture-data-root"
    (root / "input").mkdir(parents=True, exist_ok=True)
    (root / "input" / "samplesheet.csv").write_text("sample,fastq_1,fastq_2\n")
    return root


def run_case(case: Case, args: argparse.Namespace) -> tuple[bool, str]:
    workdir = Path(tempfile.mkdtemp(prefix=f"nfstub-{case.pipeline}-{case.version}-"))
    try:
        data_root = args.data_root or make_fixture_root(workdir)
        if args.mode == "echo":
            executable = "['echo']"
        else:
            wrapper = workdir / "cli-dry-run.sh"
            wrapper.write_text(f'#!/bin/bash\nexec {shlex.quote(args.cli)} "$@" --dry-run\n')
            wrapper.chmod(0o755)
            executable = f"[{_groovy(str(wrapper))}]"
        write_stub(workdir, case, data_root, args.config, executable)

        result = subprocess.run(
            ["nextflow", "run", str(workdir), "-ansi-log", "false"],
            cwd=workdir,
            capture_output=True,
            text=True,
            check=False,
            timeout=args.timeout,
        )
        # Nextflow emits CR-terminated progress lines even with -ansi-log false.
        combined = (result.stdout + result.stderr).replace("\r", "\n")
        lines = [m.group(1).rstrip() for m in _DEPICTIO_LINE.finditer(combined)]
        body = "\n".join(lines)

        # The handler swallows every error so the pipeline's own status is never
        # changed, which means the nextflow exit code says nothing about it. The
        # [depictio] lines are the only signal, so they are what gets asserted.
        forwarded = f"--pipeline-id {case.pipeline_id}" in body.replace("\n", " ")
        if not forwarded:
            forwarded = case.pipeline_id in body
        if args.mode == "echo":
            ok = forwarded and "--triggered-by nextflow" in body.replace("\n", " ")
            if not ok:
                ok = forwarded and "--triggered-by" in body
        else:
            resolved = "exited with code" not in body and "❌" not in body
            ok = forwarded and (resolved == case.should_resolve)
        return ok, body or combined[-2000:]
    finally:
        if not args.keep:
            shutil.rmtree(workdir, ignore_errors=True)
        else:
            _log(f"   kept {workdir}")


def cmd_list(args: argparse.Namespace) -> int:
    for case in discover_cases(include_negative=not args.templates_only):
        kind = "template" if case.should_resolve else "must-fail"
        print(f"{case.name:<32} {kind}")
    return 0


def cmd_run(args: argparse.Namespace) -> int:
    cases = discover_cases(include_negative=not args.templates_only)
    if args.case:
        wanted = set(args.case)
        cases = [c for c in cases if c.name in wanted or c.pipeline in wanted]
        if not cases:
            raise SystemExit(f"no case matches {args.case}")
    if not args.config.is_file():
        raise SystemExit(
            f"no Depictio Nextflow config at {args.config}; "
            "generate one with `depictio-cli config nextflow` and pass --config"
        )
    failures = 0
    for case in cases:
        ok, body = run_case(case, args)
        # In echo mode nothing resolves a template: the handler only assembles the
        # argv and hands it to echo, so a version with no template directory is
        # indistinguishable from one that has it. Saying "expect fail" there would
        # claim a check that did not happen.
        if args.mode == "echo":
            expect = "forward"
        else:
            expect = "resolve" if case.should_resolve else "fail"
        mark = "ok " if ok else "FAIL"
        print(f"[{mark}] {case.name:<30} expect {expect}")
        if not ok or args.verbose:
            print("\n".join(f"        {line}" for line in body.splitlines()) + "\n")
        failures += 0 if ok else 1
    print(f"\n{len(cases) - failures}/{len(cases)} case(s) as expected")
    return 1 if failures else 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="nfcore_trigger_stub.py",
        description=__doc__.splitlines()[0],
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    p_list = subparsers.add_parser("list", help="show the cases")
    p_list.add_argument("--templates-only", action="store_true", help="skip the must-fail cases")
    p_list.set_defaults(func=cmd_list)

    p_run = subparsers.add_parser("run", help="run the stub workflow for each case")
    p_run.add_argument(
        "--case", action="append", metavar="PIPE[/VER]", help="restrict (repeatable)"
    )
    p_run.add_argument("--templates-only", action="store_true", help="skip the must-fail cases")
    p_run.add_argument(
        "--mode",
        choices=("echo", "dry-run"),
        default="echo",
        help="echo prints the assembled argv; dry-run reaches locate_template()",
    )
    p_run.add_argument(
        "--config",
        type=lambda v: Path(v).expanduser(),
        default=DEFAULT_DEPICTIO_CONFIG,
        help=f"the depictio Nextflow config to include (default {DEFAULT_DEPICTIO_CONFIG})",
    )
    p_run.add_argument(
        "--data-root",
        type=lambda v: Path(v).expanduser().resolve(),
        default=None,
        help="what params.outdir points at; default: a generated minimal fixture",
    )
    p_run.add_argument(
        "--cli",
        default=os.environ.get("DEPICTIO_CLI_BIN", "depictio-cli"),
        help="the CLI used by --mode dry-run",
    )
    p_run.add_argument("--timeout", type=int, default=300, help="seconds per case")
    p_run.add_argument("--keep", action="store_true", help="keep the generated stub directories")
    p_run.add_argument("-v", "--verbose", action="store_true", help="print the handler output")
    p_run.set_defaults(func=cmd_run)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        return int(args.func(args))
    except (OSError, ValueError, subprocess.TimeoutExpired) as exc:
        _log(f"! {exc}")
        return 1


if __name__ == "__main__":
    sys.exit(main())
