# nf-core/ampliseq Demo Project - Microbial Community Analysis
id: "646b0f3c1e4a2d7f8e5b8ca2"
name: "Ampliseq Microbial Community Analysis"
project_type: "advanced"
workflows:
  - id: "646b0f3c1e4a2d7f8e5b8ca3"
    name: "ampliseq"
    version: "2.14.0"
    engine:
      name: "nextflow"
      version: "24.10.4"
    catalog:
      name: "nf-core"
      url: "https://nf-co.re"
    repository_url: "https://github.com/nf-core/ampliseq"
    data_location:
      structure: "sequencing-runs"
      runs_regex: "run_*"
      locations:
        - /app/depictio/projects/reference/ampliseq
    data_collections:
      - id: "646b0f3c1e4a2d7f8e5b8ca4"
        data_collection_tag: "multiqc_data"
        description: "MultiQC report data"
        config:
          type: "MultiQC"
          scan:
            mode: "recursive"
            scan_parameters:
              regex_config:
                pattern: "multiqc_data/multiqc.parquet"
          dc_specific_properties:
            # S3 location will be populated during initialization when file is uploaded to MinIO
            s3_location: null  # Set by initialization script
            modules:
              - "cutadapt"
            plots:
              cutadapt:
                - "Filtered Reads"
                - "Trimmed Sequence Lengths (5')":
                    - "Counts"
                    - "Obs/Exp"
            samples:
              - "SRR10070130"
              - "SRR10070130 - First read: Adapter 1"
              - "SRR10070130 - Second read: Adapter 2"
              - "SRR10070131"
              - "SRR10070131 - First read: Adapter 1"
              - "SRR10070131 - Second read: Adapter 2"
              - "SRR10070132"
              - "SRR10070132 - First read: Adapter 1"
              - "SRR10070132 - Second read: Adapter 2"
              - "SRR10070133"
              - "SRR10070133 - First read: Adapter 1"
              - "SRR10070133 - Second read: Adapter 2"
              - "SRR10070134"
              - "SRR10070134 - First read: Adapter 1"
              - "SRR10070134 - Second read: Adapter 2"
              - "SRR10070135"
              - "SRR10070135 - First read: Adapter 1"
              - "SRR10070135 - Second read: Adapter 2"
              - "SRR10070136"
              - "SRR10070136 - First read: Adapter 1"
              - "SRR10070136 - Second read: Adapter 2"
              - "SRR10070137"
              - "SRR10070137 - First read: Adapter 1"
              - "SRR10070137 - Second read: Adapter 2"
              - "SRR10070138"
              - "SRR10070138 - First read: Adapter 1"
              - "SRR10070138 - Second read: Adapter 2"
              - "SRR10070139"
              - "SRR10070139 - First read: Adapter 1"
              - "SRR10070139 - Second read: Adapter 2"
              - "SRR10070140"
              - "SRR10070140 - First read: Adapter 1"
              - "SRR10070140 - Second read: Adapter 2"
              - "SRR10070141"
              - "SRR10070141 - First read: Adapter 1"
              - "SRR10070141 - Second read: Adapter 2"
              - "SRR10070142"
              - "SRR10070142 - First read: Adapter 1"
              - "SRR10070142 - Second read: Adapter 2"

      - id: "646b0f3c1e4a2d7f8e5b8ca5"
        data_collection_tag: "metadata"
        description: "Sample metadata for ampliseq analysis"
        config:
          type: "Table"
          metatype: "Metadata"
          scan:
            mode: "single"
            scan_parameters:
              filename: "/app/depictio/projects/reference/ampliseq/merged_metadata.tsv"
          dc_specific_properties:
            format: "TSV"
            polars_kwargs:
              separator: "\t"
              try_parse_dates: true
            columns_description:
              "sample": "Sample identifier (SRR accession)"
              "name": "Sample name"
              "habitat": "Sample habitat type"
              "Riv_vs_Gro": "Habitat comparison group 1"
              "Sed_vs_Soil": "Habitat comparison group 2"

      - id: "646b0f3c1e4a2d7f8e5b8ca8"
        data_collection_tag: "alpha_rarefaction"
        description: "Alpha diversity rarefaction curves"
        config:
          type: "Table"
          metatype: "Metadata"
          scan:
            mode: "single"
            scan_parameters:
              filename: "/app/depictio/projects/reference/ampliseq/faith_pd_long.tsv"
          dc_specific_properties:
            format: "TSV"
            polars_kwargs:
              separator: "\t"
            columns_description:
              "sample": "Sample identifier"
              "depth": "Sequencing depth"
              "iter": "Iteration number"
              "faith_pd": "Faith's Phylogenetic Diversity metric"

      - id: "646b0f3c1e4a2d7f8e5b8ca9"
        data_collection_tag: "taxonomy_composition"
        description: "Taxonomic composition across samples"
        config:
          type: "Table"
          metatype: "Metadata"
          scan:
            mode: "single"
            scan_parameters:
              filename: "/app/depictio/projects/reference/ampliseq/taxonomy_long.tsv"
          dc_specific_properties:
            format: "TSV"
            polars_kwargs:
              separator: "\t"
            columns_description:
              "sample": "Sample identifier"
              "taxonomy": "Taxonomic classification (Kingdom;Phylum)"
              "count": "Raw sequence count for this taxonomy"
              "habitat": "Habitat type of the sample"

      - id: "646b0f3c1e4a2d7f8e5b8caa"
        data_collection_tag: "ancom_volcano"
        description: "ANCOM differential abundance analysis results"
        config:
          type: "Table"
          metatype: "Metadata"
          scan:
            mode: "single"
            scan_parameters:
              filename: "/app/depictio/projects/reference/ampliseq/ancom_volcano.tsv"
          dc_specific_properties:
            format: "TSV"
            polars_kwargs:
              separator: "\t"
            columns_description:
              "id": "ASV identifier"
              "taxonomy": "Taxonomic classification (Kingdom;Phylum)"
              "Kingdom": "Kingdom level classification"
              "Phylum": "Phylum level classification"
              "W": "W statistic from ANCOM analysis"
              "clr": "Centered log-ratio transformed abundance"

# ============================================================================
# TABLE JOINS CONFIGURATION
# ============================================================================
# REMOVED: Joins were unnecessary as taxonomy_composition already contains
# the 'habitat' column from the source TSV file. Dashboard components use
# the original DCs directly without needing enriched versions.
# ============================================================================

# joins:
#   Joins removed - taxonomy_composition and alpha_rarefaction data collections
#   already contain all required columns for the dashboard visualizations.

# ============================================================================
# RUNTIME LINKS CONFIGURATION
# ============================================================================
# Runtime filtering for cross-DC interactions (especially MultiQC)
# ============================================================================

links:
  # Link 1: Metadata → MultiQC (for MultiQC component filtering)
  - source_dc_id: "646b0f3c1e4a2d7f8e5b8ca5"  # metadata
    source_column: "sample"
    target_dc_id: "646b0f3c1e4a2d7f8e5b8ca4"  # multiqc_data
    target_type: "multiqc"
    link_config:
      resolver: "sample_mapping"
      target_field: "sample_name"
    description: "Filter MultiQC by metadata samples (habitat selections)"
    enabled: true

  # Link 2: Metadata → Alpha Rarefaction (for Faith PD figure)
  - source_dc_id: "646b0f3c1e4a2d7f8e5b8ca5"  # metadata
    source_column: "sample"
    target_dc_id: "646b0f3c1e4a2d7f8e5b8ca8"  # alpha_rarefaction
    target_type: "table"
    link_config:
      resolver: "direct"
      target_field: "sample"
    description: "Filter alpha rarefaction by metadata samples"
    enabled: true

  # Link 3: Metadata → Taxonomy Composition (for taxonomy figure)
  - source_dc_id: "646b0f3c1e4a2d7f8e5b8ca5"  # metadata
    source_column: "sample"
    target_dc_id: "646b0f3c1e4a2d7f8e5b8ca9"  # taxonomy_composition
    target_type: "table"
    link_config:
      resolver: "direct"
      target_field: "sample"
    description: "Filter taxonomy by metadata samples"
    enabled: true

  # Note: ANCOM volcano (646b0f3c1e4a2d7f8e5b8caa) is not linked because it shows
  # habitat-independent differential abundance analysis and has no sample column
