/**
 * MultiQC coverage check for the Tool step.
 *
 * A tool MultiQC already parses normally reaches depictio through the MultiQC
 * integration (`depictio/catalog/multiqc/`), which produces its general-stats
 * table without anyone authoring a catalog entry. Hand-authoring a second,
 * parallel entry for such a tool is usually a mistake, so the Tool step warns
 * about it. Advisory only: a bespoke entry for a MultiQC-covered tool is a
 * legitimate choice (a richer output than general stats, a file MultiQC skips),
 * so nothing is blocked.
 *
 * The list is `depictio/catalog/_index/multiqc_modules.txt` (one MultiQC module
 * directory per line, regenerated by `depictio dev catalog refresh-index`),
 * copied into public/ at build time by scripts/genKinds.ts.
 */
import { useEffect, useState } from 'react';
import { canonicalNfCoreUrl } from './fromNfCore';

/** Compare on letters+digits only: MultiQC writes `trim_galore` where nf-core
 *  writes `trimgalore`, and neither casing is stable. */
const norm = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, '');

/** Load the advisory index; an empty set (no warning) if it can't be read. */
export function useMultiqcModules(): Set<string> {
  const [modules, setModules] = useState<Set<string>>(new Set());
  useEffect(() => {
    let cancelled = false;
    fetch(`${import.meta.env.BASE_URL}multiqc_modules.txt`)
      .then((r) => r.text())
      .then((text) => {
        if (cancelled) return;
        const names = text
          .split('\n')
          .map((l) => l.trim())
          .filter((l) => l && !l.startsWith('#'));
        setModules(new Set(names));
      })
      .catch(() => {
        /* leave empty: the wizard works, just without the MultiQC warning */
      });
    return () => {
      cancelled = true;
    };
  }, []);
  return modules;
}

/**
 * The MultiQC module covering this draft tool, or null.
 *
 * Checks the tool id and both halves of an nf-core module path (`subread/
 * featurecounts` is MultiQC's `featurecounts`). When nothing matches exactly, a
 * trailing version digit is dropped and retried once, which is what connects
 * nf-core's `kraken2` to MultiQC's `kraken`. The retry only fires when the exact
 * name is absent, so genuinely separate versioned modules (MultiQC ships both
 * `bowtie1` and `bowtie2`) keep matching themselves.
 */
export function multiqcModuleFor(
  modules: Set<string>,
  draft: { id?: string; nf_core_url?: string | null },
): string | null {
  if (!modules.size) return null;
  const byNorm = new Map<string, string>();
  for (const m of modules) if (!byNorm.has(norm(m))) byNorm.set(norm(m), m);

  const candidates: string[] = [];
  if (draft.id) candidates.push(draft.id);
  if (draft.nf_core_url) {
    const path = canonicalNfCoreUrl(draft.nf_core_url).split('/modules/nf-core/')[1];
    if (path) candidates.push(...path.split('/').filter(Boolean));
  }

  for (const c of candidates) {
    const exact = byNorm.get(norm(c));
    if (exact) return exact;
  }
  for (const c of candidates) {
    const stripped = norm(c).replace(/\d+$/, '');
    // Guard the empty string ("2" would strip to "") and one-letter stems.
    if (stripped.length < 3) continue;
    const hit = byNorm.get(stripped);
    if (hit) return hit;
  }
  return null;
}
