"""Translate nf-core ``template.yaml`` files into Markdown reference partials.

Each template is the source of truth for its variables, data collections,
conditional routes, cross-DC links and recipe schemas. Hand-written reference
tables drift out of sync with the template as soon as a DC or recipe changes
(e.g. the ampliseq 2.16.0 template grew to 23 DCs while its doc page still
listed 9). This script reads every template directly and regenerates a
deterministic Markdown partial per template, so the reference always matches
the code with zero hand-maintenance.

The narrative pipeline pages (intro, screenshots, dashboard-tab descriptions)
stay hand-written and *include* the generated partial via an mkdocs snippet:

    ## Reference
    --8<-- "pipeline-templates/nf-core/_generated/ampliseq-2.16.0.md"

So narrative and reference never conflict, and new templates only need a thin
narrative page plus a re-run of this script.

Usage:
    python -m depictio.dev_scripts.gen_template_docs
    python -m depictio.dev_scripts.gen_template_docs --check   # CI / pre-commit
    python -m depictio.dev_scripts.gen_template_docs --docs-root /path/to/depictio-docs
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

from depictio.cli.cli.utils.templates import _load_yaml
from depictio.models.models.templates import TemplateConditional, TemplateMetadata
from depictio.recipes import load_recipe, resolve_recipe_path

# Repo root: depictio/dev_scripts/gen_template_docs.py -> <repo>/
_REPO_ROOT = Path(__file__).resolve().parents[2]
_GITHUB_BLOB = "https://github.com/depictio/depictio/blob/main"
_DEFAULT_TEMPLATES_ROOT = _REPO_ROOT / "depictio" / "projects" / "nf-core"
# Where generated partials land within the docs repo (relative to its docs/ dir).
_GENERATED_SUBDIR = Path("pipeline-templates") / "nf-core" / "_generated"

_GEN_BANNER = "<!-- GENERATED by depictio/dev_scripts/gen_template_docs.py — do not edit. -->"
_REGEN_HINT = "<!-- Regenerate: python -m depictio.dev_scripts.gen_template_docs -->"

# Shared scoped CSS for the generated reference (emitted once per partial).
# Generic (no per-template values): brand teal for headers, Material theme vars
# for neutrals, coloured badges for the DC table, and a sticky first column so
# wide route matrices scroll cleanly. Headers are horizontal + wrapped (readable).
_STYLE = """<style>
.gtd-badge{display:inline-block;padding:0 .5em;border-radius:10px;font-size:.78em;font-weight:600;line-height:1.5;white-space:nowrap;}
.gtd-scan{background:#eef1fb;color:#3949ab;}
.gtd-transformed{background:#e6f7f5;color:#2a8c82;}
.gtd-opt{background:#fff6e6;color:#b9770e;}
.gtd-req{background:#e9f7ef;color:#1e8e5a;}
.gtd-plus-chip{background:#e9f7ef;color:#1e8e5a;}
.gtd-minus-chip{background:#fdecea;color:#c0392b;}
.gtd-swap-chip{background:#fff6e6;color:#b9770e;}
.gtd-legend{display:flex;flex-wrap:wrap;align-items:center;gap:.4rem;margin:.2rem 0 .8rem;}
.gtd-legend-note{font-size:.8rem;opacity:.85;}
/* Let long code/paths wrap so the wide reference tables fit without their own
   horizontal scrollbar (Material wraps each table in a scroller at runtime). */
.md-typeset table{font-size:.78rem;}
.md-typeset table code{font-size:.92em;}
/* First-column identifiers (variable / DC / recipe names) stay on one line;
   only the other columns' long paths may wrap. */
.md-typeset table td:first-child{white-space:nowrap;}
.md-typeset table td:not(:first-child) code{overflow-wrap:anywhere;}
.gtd-mtx{margin:.8rem 0;}
.gtd-mtx table{border-collapse:separate;border-spacing:0;font-size:.7rem;}
.gtd-mtx th,.gtd-mtx td{border:1px solid var(--md-default-fg-color--lightest,#e6e6e6);padding:2px 5px;text-align:center;}
.gtd-mtx thead th{background:#45B8AC;color:#fff;vertical-align:bottom;white-space:nowrap;font-size:.64rem;line-height:1.12;}
.gtd-mtx th.dc{text-align:left;white-space:nowrap;font-weight:600;background:var(--md-default-bg-color,#fff);}
.gtd-mtx thead th.dc{background:#45B8AC;color:#fff;}
/* Only large matrices get the capped, scroll-both-ways container with a pinned
   header row + first column; tables that fit the page render plain (no overflow). */
.gtd-mtx.scroll{max-height:75vh;overflow:auto;}
.gtd-mtx.scroll thead th{position:sticky;top:0;z-index:2;}
.gtd-mtx.scroll th.dc{position:sticky;left:0;z-index:1;}
.gtd-mtx.scroll thead th.dc{z-index:3;}
.gtd-mtx td.plus,.gtd-mtx td.minus,.gtd-mtx td.swap{font-size:1rem;font-weight:700;line-height:1;}
.gtd-mtx td.plus{color:#1e8e5a;}
.gtd-mtx td.minus{color:#c0392b;}
.gtd-mtx td.swap{color:#b9770e;}
.gtd-mtx tbody tr:nth-child(even) td{background:var(--md-default-fg-color--lightest,#f6f8fa);}
.gtd-mtx code{background:none;padding:0;color:inherit;}
.gtd-links{margin:1rem 0;}
.gtd-links table{border-collapse:collapse;font-size:.74rem;width:100%;}
.gtd-links th,.gtd-links td{border:1px solid var(--md-default-fg-color--lightest,#e6e6e6);padding:2px 6px;text-align:left;}
.gtd-links thead th{background:#45B8AC;color:#fff;}
.gtd-links td.arr{color:#45B8AC;text-align:center;font-weight:700;}
.gtd-links .col{opacity:.7;font-size:.92em;}
.gtd-links code{background:none;padding:0;overflow-wrap:anywhere;}
.gtd-links tbody tr:nth-child(even){background:var(--md-default-fg-color--lightest,#f6f8fa);}
</style>"""


def _find_docs_root(explicit: str | None) -> Path:
    """Resolve the depictio-docs repo root, honouring --docs-root when given."""
    if explicit:
        root = Path(explicit).expanduser().resolve()
        if not (root / "docs").is_dir():
            sys.exit(f"--docs-root {root} has no docs/ directory")
        return root
    # The docs repo is a sibling checkout; from a git worktree the repo root is
    # nested, so probe a few ancestors for a depictio-docs git checkout. Require
    # a .git so a stray sibling directory with a docs/ folder can't shadow it.
    for ancestor in (_REPO_ROOT, *_REPO_ROOT.parents):
        candidate = ancestor.parent / "depictio-docs"
        if (candidate / "docs").is_dir() and (candidate / ".git").exists():
            return candidate.resolve()
    sys.exit("Could not locate depictio-docs git checkout — pass --docs-root explicitly.")


def _esc(text: str) -> str:
    """Escape pipe characters so free text is safe inside a Markdown table cell."""
    return text.replace("|", "\\|").replace("\n", " ").strip()


def _code(text: str) -> str:
    return f"`{text}`"


def _yes_no(flag: bool) -> str:
    return "✓" if flag else "—"


def _iter_dcs(raw: dict[str, Any]) -> list[dict[str, Any]]:
    """Return every DC across all workflows, deduplicated by tag (file order)."""
    seen: set[str] = set()
    dcs: list[dict[str, Any]] = []
    for workflow in raw.get("workflows") or []:
        for dc in workflow.get("data_collections") or []:
            tag = dc.get("data_collection_tag")
            if not tag or tag in seen:
                continue
            seen.add(tag)
            dcs.append(dc)
    return dcs


def _dc_source_detail(dc: dict[str, Any]) -> tuple[str, str]:
    """Return (source, detail) — recipe ref for transformed DCs, scan target otherwise."""
    # `or {}` (not get default) so a present-but-null YAML key (e.g. empty
    # `transform:`) coerces to {} instead of crashing the chained .get().
    config = dc.get("config") or {}
    source = config.get("source", "scan")
    if source == "transformed":
        recipe = (config.get("transform") or {}).get("recipe")
        return source, _code(recipe) if recipe else "—"
    scan_params = (config.get("scan") or {}).get("scan_parameters") or {}
    target = (scan_params.get("regex_config") or {}).get("pattern") or scan_params.get("filename")
    return source, _code(target) if target else "—"


def _collect_recipe_refs(raw: dict[str, Any], meta: TemplateMetadata) -> list[str]:
    """Every recipe referenced by a DC or a conditional override, sorted & unique."""
    refs: set[str] = set()
    for dc in _iter_dcs(raw):
        recipe = ((dc.get("config") or {}).get("transform") or {}).get("recipe")
        if recipe:
            refs.add(recipe)
    for cond in meta.conditional:
        for override in cond.override_dcs:
            if override.recipe:
                refs.add(override.recipe)
    return sorted(refs)


def _join_codes(items: list[str]) -> str:
    return ", ".join(_code(i) for i in items) if items else "—"


def _recipe_columns(schema: dict[str, Any]) -> str:
    return ", ".join(_code(col) for col in schema) if schema else "—"


def _recipe_github_url(ref: str, pipeline_version: str) -> str | None:
    """Resolve a recipe ref to its source file URL on GitHub (None if unresolved)."""
    try:
        rel = resolve_recipe_path(ref, pipeline_version).resolve().relative_to(_REPO_ROOT)
    except Exception:  # noqa: BLE001 — unresolved recipe just renders without a link
        return None
    return f"{_GITHUB_BLOB}/{rel.as_posix()}"


def _render_variables(meta: TemplateMetadata) -> list[str]:
    # Auto-detected vars (descriptions start with "Auto-…") are derived from the
    # run, not user inputs — listing them inline keeps the main table short and
    # readable. The route flags among them drive the Conditional routes below.
    provided = [v for v in meta.variables if not v.description.lstrip().startswith("Auto")]
    auto = [v for v in meta.variables if v.description.lstrip().startswith("Auto")]

    lines = [
        "### Template variables",
        "",
        "Variables you provide when running the template — `DATA_ROOT` via `--data-root`, "
        "the rest via `--var NAME=value`:",
        "",
        "| Variable | Required | Description |",
        "|---|:--:|---|",
    ]
    for var in provided:
        lines.append(f"| {_code(var.name)} | {_yes_no(var.required)} | {_esc(var.description)} |")
    lines.append("")
    if auto:
        names = ", ".join(_code(v.name) for v in auto)
        lines += [
            f"**Auto-detected** (set from the run's metadata / `params.json`; the route "
            f"flags drive *Conditional routes* below): {names}",
            "",
        ]
    return lines


def _badge(text: str, cls: str) -> str:
    return f'<span class="gtd-badge {cls}">{text}</span>'


def _render_data_collections(dcs: list[dict[str, Any]]) -> list[str]:
    optional_count = sum(1 for dc in dcs if dc.get("optional"))
    required_count = len(dcs) - optional_count
    lines = [
        "### Data collections",
        "",
        f"{len(dcs)} data collections — {_badge(f'{required_count} required', 'gtd-req')} "
        f"{_badge(f'{optional_count} optional', 'gtd-opt')}.",
        "",
        "| Tag | Type | Source | Recipe / scan target | Status |",
        "|---|---|---|---|:--:|",
    ]
    for dc in dcs:
        source, detail = _dc_source_detail(dc)
        dc_type = (dc.get("config") or {}).get("type", "—")
        src = _badge(source, "gtd-transformed" if source == "transformed" else "gtd-scan")
        status = (
            _badge("optional", "gtd-opt") if dc.get("optional") else _badge("required", "gtd-req")
        )
        lines.append(
            f"| {_code(dc['data_collection_tag'])} | {dc_type} | {src} | {detail} | {status} |"
        )
    lines.append("")
    return lines


def _html(text: str) -> str:
    """Escape text for embedding in raw HTML."""
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _condition_parts(cond: TemplateConditional) -> tuple[str, str]:
    """Trigger split into (variable, polarity) for a two-line header."""
    if cond.if_var_present:
        return cond.if_var_present, "present"
    if cond.if_var_absent:
        return cond.if_var_absent, "absent"
    return "always", ""


def _render_conditionals(meta: TemplateMetadata, dc_tags: list[str]) -> list[str]:
    """Matrix of data collections (rows) × variables (cols).

    One column per variable (the two present/absent rules of the same flag share
    a column); each filled cell names the state — present or absent — that
    triggers the effect, coloured red (removed) or amber (repointed). Generic
    across templates; dashboard-only routes are skipped.
    """
    routes = [c for c in meta.conditional if c.remove_dc_tags or c.override_dcs]
    if not routes:
        return []

    cols: list[str] = []  # unique variables, first-appearance order
    # Each column is anchored to the variable being SET (present). A cell records
    # the effect of setting that variable: − removed, + included-only-then, ⇄ repointed.
    # dc tag -> {variable -> (glyph, css class, tooltip)}
    marks: dict[str, dict[str, tuple[str, str, str]]] = {}
    for cond in routes:
        var, pol = _condition_parts(cond)
        if var not in cols:
            cols.append(var)
        for tag in cond.remove_dc_tags:
            if pol == "present":
                entry = ("−", "minus", f"removed when {var} is set")
            else:  # removed when the variable is ABSENT → only present when it is set
                entry = ("+", "plus", f"included only when {var} is set")
            marks.setdefault(tag, {}).setdefault(var, entry)
        for override in cond.override_dcs:
            when = "set" if pol == "present" else "unset"
            marks.setdefault(override.data_collection_tag, {}).setdefault(
                var, ("⇄", "swap", f"re-sourced when {var} is {when}")
            )

    # Rows in DC-table order; append any conditional-only tags not in the DC list.
    rows = [t for t in dc_tags if t in marks] + [t for t in marks if t not in dc_tags]
    kept = sum(1 for t in dc_tags if t not in marks)

    heads = "".join(f"<th><code>{_html(c)}</code></th>" for c in cols)
    body_rows = []
    for tag in rows:
        cells = ""
        for var in cols:
            if var in marks[tag]:
                glyph, cls, title = marks[tag][var]
                cells += f'<td class="{cls}" title="{_html(title)}">{glyph}</td>'
            else:
                cells += "<td></td>"
        body_rows.append(f'<tr><th class="dc"><code>{_html(tag)}</code></th>{cells}</tr>')

    # Only cap height / pin headers when the matrix is too big to fit a screen;
    # smaller ones render plain so there's no needless scroll container.
    scroll = " scroll" if len(rows) > 16 or len(cols) > 6 else ""
    html = [
        f'<div class="gtd-mtx{scroll}">',
        "<table>",
        f'<thead><tr><th class="dc">Data collection</th>{heads}</tr></thead>',
        "<tbody>",
        *body_rows,
        "</tbody></table></div>",
    ]
    return [
        "### Conditional routes",
        "",
        "Rows are data collections; columns are the variables you set or `params.json` "
        "flags auto-detected from the run. Each filled cell is the effect of **setting** "
        "that variable; an **empty cell** means that variable leaves the collection "
        f"unchanged. ({kept} collections are unaffected by any variable — present on every run.)",
        "",
        '<p class="gtd-legend">'
        '<span class="gtd-badge gtd-plus-chip">+ included</span>'
        '<span class="gtd-badge gtd-minus-chip">− removed</span>'
        '<span class="gtd-badge gtd-swap-chip">⇄ repointed</span></p>',
        "",
        *html,
        "",
    ]


def _render_links(raw: dict[str, Any]) -> list[str]:
    links = raw.get("links") or []
    if not links:
        return []
    body_rows = []
    for link in links:
        src = _html(link.get("source_dc_tag", "?"))
        col = _html(link.get("source_column", "?"))
        tgt = _html(link.get("target_dc_tag", "?"))
        desc = _html(link.get("description", ""))
        body_rows.append(
            f'<tr><td><code>{src}</code> <span class="col">·&nbsp;{col}</span></td>'
            f'<td class="arr">→</td><td><code>{tgt}</code></td><td>{desc}</td></tr>'
        )
    return [
        "### Cross-DC links",
        "",
        f"{len(links)} links — selecting a value in the **source** collection filters the "
        "**target**. The join column is shown after the source.",
        "",
        '<div class="gtd-links">',
        "<table>",
        "<thead><tr><th>Source · column</th><th></th><th>Target</th><th>Filters</th></tr></thead>",
        "<tbody>",
        *body_rows,
        "</tbody></table></div>",
        "",
    ]


def _render_recipes(refs: list[str], pipeline_version: str) -> list[str]:
    if not refs:
        return []
    lines = [
        "### Recipes",
        "",
        "Each recipe reshapes raw pipeline output into a tidy table. The name links "
        "to its source; *Output* lists the validated `EXPECTED_SCHEMA` columns.",
        "",
        "| Recipe | Transforms | Output |",
        "|---|---|---|",
    ]
    for ref in refs:
        url = _recipe_github_url(ref, pipeline_version)
        name = f"[`{ref}`]({url})" if url else _code(ref)
        try:
            module = load_recipe(ref, pipeline_version)
            doc = (module.__doc__ or "").strip().splitlines()
            summary = _esc(doc[0]) if doc else "—"
            columns = _recipe_columns(module.EXPECTED_SCHEMA)
        except Exception as exc:  # noqa: BLE001 — surface load failure, don't abort the doc
            summary, columns = f"⚠ failed to load: {_esc(str(exc))}", "—"
        lines.append(f"| {name} | {summary} | {columns} |")
    lines.append("")
    return lines


def render_template(template_path: Path) -> str:
    """Render the full Markdown reference partial for one template.yaml."""
    raw = _load_yaml(str(template_path))
    meta = TemplateMetadata(**raw["template"])
    # Pipeline version is the template's directory name (template_id schema version differs).
    pipeline_version = template_path.parent.name
    dcs = _iter_dcs(raw)
    recipe_refs = _collect_recipe_refs(raw, meta)

    lines = [
        _GEN_BANNER,
        f"<!-- Source: {template_path.relative_to(_REPO_ROOT)} -->",
        _REGEN_HINT,
        "",
        _STYLE,
        "",
        *_render_variables(meta),
        *_render_data_collections(dcs),
        *_render_conditionals(meta, [dc["data_collection_tag"] for dc in dcs]),
        *_render_links(raw),
        *_render_recipes(recipe_refs, pipeline_version),
    ]
    # Trailing single newline; collapse the final blank line the sections add.
    return "\n".join(lines).rstrip() + "\n"


def _output_slug(template_path: Path, templates_root: Path) -> str:
    """e.g. depictio/projects/nf-core/ampliseq/2.16.0/template.yaml -> ampliseq-2.16.0."""
    rel = template_path.parent.relative_to(templates_root)
    return "-".join(rel.parts)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--templates-root",
        default=str(_DEFAULT_TEMPLATES_ROOT),
        help="Directory scanned recursively for template.yaml files.",
    )
    parser.add_argument(
        "--docs-root",
        default=None,
        help="depictio-docs repo root (auto-detected as a sibling checkout when omitted).",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail (exit 1) if any partial is stale, without writing.",
    )
    args = parser.parse_args(argv)

    templates_root = Path(args.templates_root).expanduser().resolve()
    docs_root = _find_docs_root(args.docs_root)
    out_dir = docs_root / "docs" / _GENERATED_SUBDIR

    template_paths = sorted(templates_root.rglob("template.yaml"))
    if not template_paths:
        sys.exit(f"No template.yaml found under {templates_root}")

    stale: list[str] = []
    for template_path in template_paths:
        content = render_template(template_path)
        out_path = out_dir / f"{_output_slug(template_path, templates_root)}.md"
        existing = out_path.read_text() if out_path.is_file() else None

        if args.check:
            if existing != content:
                stale.append(str(out_path.relative_to(docs_root)))
            continue

        if existing == content:
            print(f"unchanged  {out_path.relative_to(docs_root)}")
            continue
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(content)
        print(f"wrote      {out_path.relative_to(docs_root)}")

    if args.check and stale:
        print("Stale generated reference partials (run gen_template_docs to refresh):")
        for path in stale:
            print(f"  {path}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
