"""Generate the nf-core template docs pages, catalog cards and index rows.

A page joins three sources, each owning what it is the authority on:

- ``template.yaml`` and the recipes: the reference tables, which
  ``gen_template_docs`` renders into ``_generated/<pipeline>-latest.md`` and
  the page includes;
- the dashboard YAML: tab titles, icons, colours, sections, filters and
  components, rendered here into each tab block;
- ``docs/page.yaml`` next to the template (``TemplateDocs``): the prose only a
  person can write, from the question each tab answers to the validation runs.

The same ``page.yaml`` drives the status badge, the catalog card in
``pipeline-templates/README.md`` and the row in ``nf-core/index.md``, so the
status and the blurbs are written once. A template whose ``page.yaml`` sets
``generate_page: false`` keeps a hand-written page; its card and row are still
generated.

Only the highest version directory of each pipeline is read (the one
``nf-core/<pipeline>/latest`` resolves to); older versions appear in the version
picker. Pipelines without a ``docs/page.yaml`` are left alone.

Usage:
    python -m depictio.dev_scripts.gen_template_pages --docs-root /path/to/depictio-docs
    python -m depictio.dev_scripts.gen_template_pages --check        # CI / pre-commit
    python -m depictio.dev_scripts.gen_template_pages --pipeline riboseq
"""

from __future__ import annotations

import argparse
import re
import textwrap
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from depictio.cli.cli.utils.templates import _load_yaml, _template_versions, _version_key
from depictio.dev_scripts.gen_template_docs import _find_docs_root
from depictio.models.models.template_docs import (
    CalloutPosition,
    DocsCallout,
    DocsDashboardTab,
    TemplateDocs,
    TemplateStatus,
)
from depictio.models.models.templates import TemplateMetadata

_REPO_ROOT = Path(__file__).resolve().parents[2]
_DEFAULT_TEMPLATES_ROOT = _REPO_ROOT / "depictio" / "projects" / "nf-core"
_PAGE_YAML = Path("docs") / "page.yaml"

_PAGES_SUBDIR = Path("pipeline-templates") / "nf-core"
_IMAGES_SUBDIR = Path("images") / "pipeline-templates" / "nf-core"
_CATALOG_PAGE = Path("pipeline-templates") / "README.md"
_INDEX_PAGE = Path("pipeline-templates") / "nf-core" / "index.md"

_GEN_NOTE = (
    "<!-- GENERATED by depictio/dev_scripts/gen_template_pages.py from {source}. "
    "Edit that file, then re-run the script. -->"
)

_STATUS_LABEL = {
    TemplateStatus.DRAFT: "Draft",
    TemplateStatus.EXPERIMENTAL: "Experimental",
    TemplateStatus.REVIEWED: "Reviewed",
    TemplateStatus.CERTIFIED: "Certified",
}
_STATUS_ICON = {
    TemplateStatus.DRAFT: "mdi-pencil-outline",
    TemplateStatus.EXPERIMENTAL: "mdi-flask-outline",
    TemplateStatus.REVIEWED: "mdi-check-circle-outline",
    TemplateStatus.CERTIFIED: "mdi-shield-check",
}
_STATUS_TOOLTIP = {
    TemplateStatus.DRAFT: (
        "Draft: generated and not yet reviewed. Expect it to need fixes before it is usable."
    ),
    TemplateStatus.EXPERIMENTAL: "Experimental: shared as-is. Feedback and PRs welcome.",
    TemplateStatus.REVIEWED: (
        "Reviewed: tested, CI passes, and reviewed by the Depictio team or community."
    ),
    TemplateStatus.CERTIFIED: "Certified: validated by the pipeline lead developer.",
}
# Why the template sits at its status, from the reviewer's side.
_REVIEWER_NOTE = {
    TemplateStatus.DRAFT: (
        "Nobody has run it on their own data and signed it off yet, which is what keeps it a Draft."
    ),
    TemplateStatus.EXPERIMENTAL: (
        "Nobody has run it on their own data and signed it off yet, "
        "which is what keeps it Experimental."
    ),
    TemplateStatus.REVIEWED: "Ran it on their own data and signed it off.",
    TemplateStatus.CERTIFIED: "Leads the pipeline and validated the template against it.",
}

# Dashboard icons missing from the Material set bundled with the docs theme.
_ICON_ALIASES = {"target-arrow": "bullseye-arrow"}
# Dashboard colours with a `.mc-<colour>` class in the docs stylesheet.
_DOC_COLOURS = {
    "red", "pink", "grape", "violet", "indigo", "blue", "cyan", "teal",
    "green", "lime", "yellow", "orange", "dark",
}  # fmt: skip

_MULTIQC_HEADER = (
    "![MultiQC](../../images/logos/multiqc_light.svg#only-light){ width=18 }"
    "![MultiQC](../../images/logos/multiqc_dark.svg#only-dark){ width=18 } MultiQC"
)

_SELF_ADAPTING = """!!! info "Self-adapting layout"
    The dashboard adapts to whatever the run actually produced: components bound
    to pruned or unparsed data collections are hidden, tabs left with no real
    visualizations are dropped entirely, and the remaining components are
    re-packed so there are no empty rows."""


@dataclass
class DashboardTab:
    """One tab of the dashboard YAML, reduced to what the page shows."""

    title: str
    icon: str | None
    colour: str | None
    is_main: bool
    raw: dict[str, Any]


@dataclass
class PipelineDocs:
    pipeline: str
    version: str
    versions: list[str]
    template_dir: Path
    docs: TemplateDocs
    meta: TemplateMetadata
    dashboard: dict[str, Any]
    tabs: list[DashboardTab] = field(default_factory=list)


class DocsError(Exception):
    """A page.yaml that disagrees with its template or dashboard."""


# ---------------------------------------------------------------------------
# Loading
# ---------------------------------------------------------------------------


def load_pipeline(pipeline_dir: Path) -> PipelineDocs | None:
    """Load the latest version of a pipeline, or None when it has no page.yaml."""
    versions = sorted(_template_versions(pipeline_dir), key=_version_key, reverse=True)
    if not versions:
        return None
    template_dir = pipeline_dir / versions[0]
    page_yaml = template_dir / _PAGE_YAML
    if not page_yaml.is_file():
        return None
    docs = TemplateDocs(**(_load_yaml(str(page_yaml)) or {}))
    raw_template = _load_yaml(str(template_dir / "template.yaml"))
    meta = TemplateMetadata(**raw_template["template"])
    if not meta.dashboards:
        raise DocsError(f"{template_dir}: template.yaml lists no dashboards")
    dashboard = _load_yaml(str(template_dir / meta.dashboards[0]))
    pipeline = PipelineDocs(
        pipeline=pipeline_dir.name,
        version=versions[0],
        versions=versions,
        template_dir=template_dir,
        docs=docs,
        meta=meta,
        dashboard=dashboard,
    )
    pipeline.tabs = _dashboard_tabs(dashboard)
    if docs.generate_page:
        _check_tab_coverage(pipeline)
    return pipeline


def _dashboard_tabs(dashboard: dict[str, Any]) -> list[DashboardTab]:
    main = dashboard.get("main_dashboard") or {}
    tabs = [
        DashboardTab(
            title=main.get("main_tab_name") or "Main",
            icon=main.get("tab_icon"),
            colour=main.get("tab_icon_color"),
            is_main=True,
            raw=main,
        )
    ]
    children = sorted(dashboard.get("tabs") or [], key=lambda t: t.get("tab_order", 0))
    tabs += [
        DashboardTab(
            title=t["title"],
            icon=t.get("tab_icon"),
            colour=t.get("tab_icon_color"),
            is_main=False,
            raw=t,
        )
        for t in children
    ]
    return tabs


def _check_tab_coverage(p: PipelineDocs) -> None:
    """Every dashboard tab has prose and every prose block names a real tab."""
    dash = [t.title for t in p.tabs]
    docs = [t.title for t in p.docs.tabs]
    missing = [t for t in dash if t not in docs]
    unknown = [t for t in docs if t not in dash]
    if missing or unknown:
        raise DocsError(
            f"{p.template_dir / _PAGE_YAML}: tabs out of sync with {p.meta.dashboards[0]}"
            f" (missing: {missing or '-'}; not in the dashboard: {unknown or '-'})"
        )


# ---------------------------------------------------------------------------
# Small helpers
# ---------------------------------------------------------------------------


def _indent(text: str, level: int = 1) -> str:
    return textwrap.indent(text.strip("\n"), "    " * level, lambda line: bool(line.strip()))


def _block(text: str | None) -> list[str]:
    """A Markdown field as page lines followed by a blank line (nothing if empty)."""
    return [text.strip("\n"), ""] if text and text.strip() else []


def _slug(title: str) -> str:
    """Screenshot slug: lowercase, words joined by underscores (MultiQC -> multiqc)."""
    return "_".join(re.findall(r"[a-z0-9]+", title.lower()))


def _material_icon(icon: str | None) -> str | None:
    """``mdi:chart-bar`` -> ``material-chart-bar`` (None for image paths)."""
    if not icon or not icon.startswith("mdi:"):
        return None
    name = icon.removeprefix("mdi:")
    return f"material-{_ICON_ALIASES.get(name, name)}"


def _is_multiqc_tab(tab: DashboardTab) -> bool:
    return "multiqc" in (tab.icon or "").lower() or tab.title == "MultiQC"


def _tab_header(tab: DashboardTab) -> str:
    if _is_multiqc_tab(tab):
        return _MULTIQC_HEADER
    icon = _material_icon(tab.icon)
    if not icon:
        return tab.title
    colour = f"{{ .mc-{tab.colour} }}" if tab.colour in _DOC_COLOURS else ""
    return f":{icon}:{colour} {tab.title}"


def _bullet_icon(tab: DashboardTab) -> str:
    if _is_multiqc_tab(tab):
        return ":material-chart-box-outline:"
    icon = _material_icon(tab.icon)
    return f":{icon}:" if icon else ":material-tab:"


def _callouts(docs: TemplateDocs, position: CalloutPosition) -> list[str]:
    lines: list[str] = []
    for callout in docs.callouts:
        if callout.position == position:
            lines += [_render_callout(callout), ""]
    return lines


def _render_callout(callout: DocsCallout) -> str:
    return f'!!! {callout.kind} "{callout.title}"\n{_indent(callout.body)}'


def _person(handle: str) -> str:
    return (
        f'    <a class="tpl-person" href="https://github.com/{handle}" target="_blank" '
        f'rel="noopener">\n'
        f'      <img src="https://github.com/{handle}.png?size=80" alt="" loading="lazy"> '
        f"{handle}\n    </a>"
    )


def _logo_imgs(pipeline: str, indent: str) -> str:
    base = f"https://raw.githubusercontent.com/nf-core/{pipeline}/master/docs/images"
    return (
        f'{indent}<img class="nf-core-dark" src="{base}/nf-core-{pipeline}_logo_dark.png" '
        f'alt="nf-core/{pipeline}">\n'
        f'{indent}<img class="nf-core-light" src="{base}/nf-core-{pipeline}_logo_light.png" '
        f'alt="nf-core/{pipeline}">'
    )


# ---------------------------------------------------------------------------
# Filters and components, from the dashboard YAML
# ---------------------------------------------------------------------------


def _component_label(component: dict[str, Any]) -> str:
    title = component.get("title") or component.get("selected_plot")
    title = title or component.get("selected_module") or component.get("component_type", "")
    return f"*{title}*"


def _section_cell(components: list[dict[str, Any]]) -> str:
    cards = [c for c in components if c.get("component_type") == "card"]
    others = [c for c in components if c.get("component_type") != "card"]
    parts: list[str] = []
    if len(cards) == 1:
        parts.append(_component_label(cards[0]))
    elif cards:
        parts.append(f"{len(cards)} cards")
    parts += [_component_label(c) for c in others]
    return ", ".join(parts)


def _section_flags(section: dict[str, Any]) -> str:
    flags = []
    if section.get("collapsed"):
        flags.append("collapsed")
    if section.get("persistent") or section.get("pin"):
        flags.append("pinned")
    return f" ({', '.join(flags)})" if flags else ""


def render_components_table(tab: DashboardTab) -> list[str]:
    """Section rows in dashboard order; text tiles and filters are left out."""
    by_section: dict[str, list[dict[str, Any]]] = {}
    for component in tab.raw.get("components") or []:
        if component.get("component_type") in ("text", "interactive"):
            continue
        by_section.setdefault(component.get("section") or "", []).append(component)
    rows = []
    for section in tab.raw.get("grid_sections") or []:
        components = by_section.pop(section["name"], [])
        if components:
            rows.append(
                f"| {section['name']} | {_section_cell(components)}{_section_flags(section)} |"
            )
    for name, components in by_section.items():  # components outside a declared section
        rows.append(f"| {name or 'Ungrouped'} | {_section_cell(components)} |")
    if not rows:
        return []
    return ["| Section | What it holds |", "|---|---|", *rows]


_RANGE_TYPES = {"RangeSlider", "Slider"}


def _join(items: list[str]) -> str:
    """``a``, ``a and b``, ``a, b and c``."""
    return items[0] if len(items) == 1 else f"{', '.join(items[:-1])} and {items[-1]}"


def _article(word: str) -> str:
    return "an" if word[:1].lower() in "aeiou" else "a"


def _filter_name(component: dict[str, Any]) -> str:
    """Filter label in code, with ``{GROUP_COL_DISPLAY}`` shown as ``<GROUP_COL>``."""
    title = str(component.get("title") or component.get("column_name") or "")
    title = re.sub(r"\{([A-Z0-9_]+?)(?:_DISPLAY)?\}", r"<\1>", title)
    name = f"`{title}`"
    if component.get("interactive_component_type") in _RANGE_TYPES:
        name = f"{name} range"
    return name


def render_filters_line(tab: DashboardTab) -> str:
    """``**Filters** · `A` and `B` in a *Group* group; ...`` from the tab's own filters."""
    by_section: dict[str, list[str]] = {}
    for component in tab.raw.get("components") or []:
        if component.get("component_type") == "interactive":
            by_section.setdefault(component.get("section") or "", []).append(
                _filter_name(component)
            )
    parts = []
    for section in tab.raw.get("filter_sections") or []:
        names = by_section.pop(section["name"], [])
        if not names:
            continue
        where = ""
        if section.get("persistent"):
            pin = section.get("pin")
            where = f", on every tab{', pinned to the ' + pin if pin else ''}"
        group = section["name"]
        parts.append(f"{_join(names)} in {_article(group)} *{group}* group{where}")
    parts += [_join(names) for names in by_section.values()]
    if not parts:
        return "**Filters** · none of its own; the pinned filters of the first tab apply."
    return "**Filters** · " + "; ".join(parts) + "."


# ---------------------------------------------------------------------------
# Page
# ---------------------------------------------------------------------------


def _screenshot_lines(p: PipelineDocs, tab: DocsDashboardTab, images_dir: Path) -> list[str]:
    slug = tab.image or _slug(tab.title)
    rel = f"../../images/pipeline-templates/nf-core/{p.pipeline}/{slug}"
    light = images_dir / p.pipeline / f"{slug}_light.png"
    dark = images_dir / p.pipeline / f"{slug}_dark.png"
    if not light.is_file():
        return []
    attrs = '{ .tpl-shot target="_blank" rel="noopener" }'
    if not dark.is_file():
        return [
            f"[![{tab.title} dashboard]({rel}_light.png){{ loading=lazy }}]"
            f"({rel}_light.png){attrs}",
            "",
        ]
    return [
        f"[![{tab.title} dashboard]({rel}_light.png#only-light){{ loading=lazy }}]"
        f"({rel}_light.png){attrs}",
        "",
        f"[![{tab.title} dashboard]({rel}_dark.png#only-dark){{ loading=lazy }}]"
        f"({rel}_dark.png){attrs}",
        "",
    ]


def _render_tab(p: PipelineDocs, tab: DashboardTab, images_dir: Path) -> list[str]:
    prose = next(t for t in p.docs.tabs if t.title == tab.title)
    body: list[str] = [f"*{prose.question.strip()}*", ""]
    body += _block(prose.conditional)
    body += _screenshot_lines(p, prose, images_dir)
    body += _block(prose.description)
    inner = [prose.filters.strip() if prose.filters else render_filters_line(tab), ""]
    inner += render_components_table(tab)
    body += ['??? abstract ":material-tune-variant: Filters and components"', ""]
    body += [_indent("\n".join(inner)), ""]
    body += _block(prose.after)
    return [f'=== "{_tab_header(tab)}"', "", _indent("\n".join(body)), ""]


def _use_count_line(p: PipelineDocs) -> list[str]:
    components = [
        c
        for tab in p.tabs
        for c in tab.raw.get("components") or []
        if c.get("component_type") != "text"
    ]
    with_use = sum(1 for c in components if c.get("use"))
    if not with_use:
        return []
    return [
        f"{with_use} of its {len(components)} components carry a `use:` catalog reference, "
        "so a tile says where its panel comes from.",
        "",
    ]


def render_page(p: PipelineDocs, docs_dir: Path) -> str:
    d = p.docs
    status = d.status
    source = (p.template_dir / _PAGE_YAML).relative_to(_REPO_ROOT)
    images_dir = docs_dir / _IMAGES_SUBDIR

    options = "\n".join(
        f'    <option value="{v}"{" selected" if v == p.version else ""}>{v}</option>'
        for v in p.versions
    )
    lines = [
        "---",
        f"title: {d.page_title}",
        "hide:",
        "  - navigation",
        "---",
        "",
        _GEN_NOTE.format(source=source),
        "",
        '<div class="template-banner">',
        f'  <a class="template-banner-logo" href="https://nf-co.re/{p.pipeline}" '
        f'target="_blank" title="nf-core/{p.pipeline} on nf-co.re">',
        _logo_imgs(p.pipeline, "    "),
        "  </a>",
        '  <div class="template-banner-body">',
        f'    <h1 class="template-title">{d.page_title}</h1>',
        f'    <p class="template-subtitle">{(d.subtitle or "").strip()}</p>',
        '    <p class="template-links">',
        f'      <a href="https://nf-co.re/{p.pipeline}" target="_blank">'
        '<i class="mdi mdi-open-in-new"></i> nf-co.re</a>',
        f'      <a href="https://github.com/nf-core/{p.pipeline}" target="_blank">'
        '<i class="mdi mdi-github"></i> GitHub</a>',
        "    </p>",
        "  </div>",
        f'  <span class="template-status-{status.value} template-banner-badge" '
        f'data-tooltip="{_STATUS_TOOLTIP[status]}"><i class="mdi {_STATUS_ICON[status]}"></i> '
        f"{_STATUS_LABEL[status]}</span>",
        "</div>",
        "",
        f'<div class="tpl-version-pick" data-latest="{p.version}">',
        '  <span class="tpl-version-icon"><i class="mdi mdi-source-branch"></i></span>',
        '  <span class="tpl-version-label">Template version</span>',
        '  <select id="tpl-version" class="tpl-version-select" aria-label="Template version">',
        options,
        "  </select>",
        '  <span class="tpl-version-badge">latest</span>',
        "</div>",
        "",
        *_block(d.intro),
    ]
    bullets = [
        f"- {_bullet_icon(tab)} **{tab.title}**: {(prose.summary or '').strip()}"
        for tab in p.tabs
        for prose in d.tabs
        if prose.title == tab.title and prose.summary
    ]
    lines += [*bullets, "", *_block(d.intro_after), *_callouts(d, CalloutPosition.INTRO)]

    # Quick start
    run_cmd = [
        "depictio run \\",
        f"  --template nf-core/{p.pipeline}/latest \\",
        f"  --data-root /path/to/{p.pipeline}_results" + (" \\" if d.run_vars else ""),
    ]
    run_cmd += [
        f"  --var {var}" + (" \\" if i < len(d.run_vars) - 1 else "")
        for i, var in enumerate(d.run_vars)
    ]
    first_tab = ["```bash", *run_cmd, "```", "", (d.quick_start or "").strip("\n")]
    lines += [
        "---",
        "",
        "## :material-rocket-launch-outline: Quick start",
        "",
        '=== "Point at a finished run"',
        "",
        _indent("\n".join(first_tab)),
        "",
    ]
    for extra in d.quick_start_tabs:
        lines += [f'=== "{extra.label}"', "", _indent(extra.body), ""]
    trigger = [
        "```bash",
        "depictio-cli config nextflow --install     # once per machine",
        f"nextflow run nf-core/{p.pipeline} -r {p.version} -profile docker --outdir results",
        "```",
        "",
        "No `depictio run`, and no template named: the pipeline ingests its own",
        "output directory when it finishes and resolves this template from its own",
        "manifest. See [Nextflow trigger](../../depictio-cli/nextflow-trigger.md).",
    ]
    lines += [
        '=== "From the pipeline itself (v1.10.0+)"',
        "",
        _indent("\n".join(trigger)),
        "",
        *_callouts(d, CalloutPosition.QUICK_START),
    ]

    # Reference
    lines += [
        "---",
        "",
        "## :material-book-open-variant: Reference",
        "",
        *_block(d.reference),
        *_use_count_line(p),
        _SELF_ADAPTING,
        "",
        *_callouts(d, CalloutPosition.REFERENCE),
        f'<div class="tpl-version-block" data-version="{p.version}" markdown>',
        "",
        f'--8<-- "pipeline-templates/nf-core/_generated/{p.pipeline}-latest.md"',
        "",
        "</div>",
        "",
    ]

    # Dashboard tabs
    lines += [
        "---",
        "",
        "## :material-view-dashboard-outline: Dashboard tabs",
        "",
        *_block(d.tabs_intro),
    ]
    for tab in p.tabs:
        lines += _render_tab(p, tab, images_dir)
    lines += _callouts(d, CalloutPosition.TABS)

    # Running, data structure, validation
    for icon, heading, text, position in (
        ("play-circle-outline", "Running the pipeline", d.running, CalloutPosition.RUNNING),
        (
            "folder-open-outline",
            "Required data structure",
            d.data_structure,
            CalloutPosition.DATA_STRUCTURE,
        ),
        ("flask-outline", "Validation runs", d.validation, CalloutPosition.VALIDATION),
    ):
        lines += ["---", "", f"## :material-{icon}: {heading}", "", *_block(text)]
        lines += _callouts(d, position)

    # Resources and authorship
    resources = [
        (
            f"nf-co.re/{p.pipeline}",
            f"https://nf-co.re/{p.pipeline}",
            "official pipeline documentation",
        ),
        (
            f"nf-co.re/{p.pipeline}/{p.version}/results",
            f"https://nf-co.re/{p.pipeline}/{p.version}/results",
            "AWS test results",
        ),
        (
            "Template System Reference",
            "../../usage/projects/templates.md",
            "YAML format, variables, conditionals",
        ),
        ("Recipes", "../../usage/projects/recipes.md", "how to read, test, and write recipes"),
        *((r.label, r.url, r.note) for r in d.resources),
    ]
    lines += [
        "---",
        "",
        "## :material-link-variant: Additional resources",
        "",
        *(f"- [{label}]({url}): {note}" for label, url, note in resources),
        "",
        "---",
        "",
        "## :material-account-group-outline: Authorship",
        "",
        *_render_authorship(p),
        "",
        "Reviewing a template on your own data, or taking over a role here, is a",
        "contribution in itself: the [contributing guide](../../developer/contributing-templates.md)",
        "says what each one involves.",
    ]
    text = "\n".join(lines)
    return re.sub(r"\n{3,}", "\n\n", text).rstrip() + "\n"


def _render_authorship(p: PipelineDocs) -> list[str]:
    a = p.docs.authorship
    roles = [
        ("mdi-code-braces", "Developers", "Wrote the template, its recipes and its dashboards.",
         a.developers),
        ("mdi-eye-check-outline", "Reviewers", _REVIEWER_NOTE[p.docs.status], a.reviewers),
        ("mdi-wrench-outline", "Maintainers", f"Keep it working as nf-core/{p.pipeline} releases.",
         a.maintainers),
    ]  # fmt: skip
    lines = ['<div class="tpl-credits">']
    for icon, role, note, handles in roles:
        lines += [
            '  <div class="tpl-credit">',
            f'    <span class="tpl-credit-role"><i class="mdi {icon}"></i> {role}</span>',
            f'    <span class="tpl-credit-note">{note}</span>',
        ]
        if handles:
            lines += [_person(h) for h in handles]
        else:
            lines.append(
                '    <span class="tpl-person"><i class="mdi mdi-account-plus-outline"></i> Open</span>'
            )
        lines.append("  </div>")
    lines.append("</div>")
    return lines


# ---------------------------------------------------------------------------
# Registries: catalog card and index row
# ---------------------------------------------------------------------------


def render_card(p: PipelineDocs) -> str:
    d = p.docs
    status = d.status
    keywords = " ".join(d.keywords)
    return "\n".join(
        [
            f'  <a class="template-card" href="nf-core/{p.pipeline}/" '
            f'data-tpl-name="nf-core/{p.pipeline}" data-tpl-status="{status.value}" '
            f'data-tpl-version="{p.version}" data-tpl-keywords="{keywords}">',
            '    <div class="template-card-logo">',
            _logo_imgs(p.pipeline, "      "),
            "    </div>",
            '    <div class="template-card-body">',
            f'      <p class="template-card-desc">{d.card_blurb.strip()}</p>',
            '      <div class="template-card-meta">',
            f'        <span class="template-version">v{p.version}</span>',
            f'        <span class="template-status-{status.value}"><i class="mdi '
            f'{_STATUS_ICON[status]}" style="vertical-align:-1px;"></i> '
            f"{_STATUS_LABEL[status]}</span>",
            "      </div>",
            "    </div>",
            "  </a>",
        ]
    )


def render_index_row(p: PipelineDocs) -> str:
    versions = ", ".join(sorted(p.versions, key=_version_key))
    return f"| [{p.pipeline}]({p.pipeline}.md) | {p.docs.index_summary} | {versions} |"


def _card_span(text: str, pipeline: str) -> tuple[int, int] | None:
    match = re.search(
        rf'  <a class="template-card" href="nf-core/{re.escape(pipeline)}/".*?</a>', text, re.S
    )
    return match.span() if match else None


def update_catalog(text: str, pipelines: list[PipelineDocs]) -> str:
    """Replace each pipeline's card in place; append new ones after the last nf-core card."""
    for p in pipelines:
        card = render_card(p)
        span = _card_span(text, p.pipeline)
        if span:
            text = text[: span[0]] + card + text[span[1] :]
            continue
        last = None
        for match in re.finditer(r'  <a class="template-card" href="nf-core/.*?</a>', text, re.S):
            last = match
        if last is None:
            raise DocsError("no nf-core card found in the catalog page to append after")
        text = text[: last.end()] + "\n\n" + card + text[last.end() :]
    return text


def update_index(text: str, pipelines: list[PipelineDocs]) -> str:
    """Replace each pipeline's row in place; append new ones after the last row."""
    lines = text.split("\n")
    for p in pipelines:
        row = render_index_row(p)
        prefix = f"| [{p.pipeline}]({p.pipeline}.md) |"
        hits = [i for i, line in enumerate(lines) if line.startswith(prefix)]
        if hits:
            lines[hits[0]] = row
            continue
        rows = [
            i for i, line in enumerate(lines) if re.match(r"\| \[[^\]]+\]\([^)]+\.md\) \|", line)
        ]
        if not rows:
            raise DocsError("no template row found in the nf-core index to append after")
        lines.insert(rows[-1] + 1, row)
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Checks against the docs tree
# ---------------------------------------------------------------------------


def _material_icons_dir(docs_root: Path) -> Path | None:
    for candidate in sorted(docs_root.glob(".venv/lib/python*/site-packages")):
        icons = candidate / "material" / "templates" / ".icons" / "material"
        if icons.is_dir():
            return icons
    return None


def lint_pipeline(p: PipelineDocs, docs_root: Path) -> list[str]:
    """Problems that would render silently wrong: missing screenshots or icons."""
    problems = []
    images_dir = docs_root / "docs" / _IMAGES_SUBDIR / p.pipeline
    for prose in p.docs.tabs:
        slug = prose.image or _slug(prose.title)
        if not (images_dir / f"{slug}_light.png").is_file() and not prose.conditional:
            problems.append(f"{p.pipeline}: no screenshot {slug}_light.png for tab {prose.title!r}")
    icons_dir = _material_icons_dir(docs_root)
    if icons_dir:
        for tab in p.tabs:
            icon = _material_icon(tab.icon)
            if icon and not (icons_dir / f"{icon.removeprefix('material-')}.svg").is_file():
                problems.append(f"{p.pipeline}: icon {tab.icon} missing from the docs theme")
    return problems


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def _write_or_check(path: Path, content: str, check: bool, root: Path, stale: list[str]) -> None:
    existing = path.read_text() if path.is_file() else None
    rel = path.relative_to(root)
    if existing == content:
        if not check:
            print(f"unchanged  {rel}")
        return
    if check:
        stale.append(str(rel))
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    print(f"wrote      {rel}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--templates-root", default=str(_DEFAULT_TEMPLATES_ROOT))
    parser.add_argument(
        "--docs-root",
        default=None,
        help="depictio-docs repo root (auto-detected as a sibling checkout when omitted).",
    )
    parser.add_argument("--pipeline", action="append", help="Limit to these pipelines.")
    parser.add_argument(
        "--check", action="store_true", help="Fail (exit 1) if anything is stale, without writing."
    )
    args = parser.parse_args(argv)

    templates_root = Path(args.templates_root).expanduser().resolve()
    docs_root = _find_docs_root(args.docs_root)
    docs_dir = docs_root / "docs"

    pipelines: list[PipelineDocs] = []
    errors: list[str] = []
    for pipeline_dir in sorted(p for p in templates_root.iterdir() if p.is_dir()):
        if args.pipeline and pipeline_dir.name not in args.pipeline:
            continue
        try:
            loaded = load_pipeline(pipeline_dir)
        except Exception as exc:  # noqa: BLE001 — report every broken page.yaml at once
            errors.append(f"{pipeline_dir.name}: {exc}")
            continue
        if loaded:
            pipelines.append(loaded)
    if errors:
        print("Invalid page.yaml:", *errors, sep="\n  ")
        return 1

    problems = [msg for p in pipelines for msg in lint_pipeline(p, docs_root)]
    for msg in problems:
        print(f"warning    {msg}")

    stale: list[str] = []
    for p in pipelines:
        if p.docs.generate_page:
            page = docs_dir / _PAGES_SUBDIR / f"{p.pipeline}.md"
            _write_or_check(page, render_page(p, docs_dir), args.check, docs_root, stale)
    for rel, update in ((_CATALOG_PAGE, update_catalog), (_INDEX_PAGE, update_index)):
        path = docs_dir / rel
        _write_or_check(path, update(path.read_text(), pipelines), args.check, docs_root, stale)

    if args.check and stale:
        print("Stale template pages (run gen_template_pages to refresh):", *stale, sep="\n  ")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
