# Description: Configuration file for the MosaiCatcher pipeline
# This file is used to define the configuration of the MosaiCatcher pipeline
# It is used to define the data collections and workflows that are available
# in the system.

# Version of the configuration file
depictio_version: "0.1.0"

# Workflows that are available in the system
workflows:
  ## Workflow for the MosaiCatcher pipeline

  # The workflow engine that is used to run the workflow
  - engine: "snakemake"

    # The name of the workflow
    name: "mosaicatcher-pipeline"

    # A description of the workflow
    description: "Strand-Seq SV calling framewoaa"

    # The URL of the repository that contains the workflow
    repository_url: "https://github.com/friendsofstrandseq/mosaicatcher-pipeline"

    # The configuration to retrieve workflow data
    config:
      # TODO: to turn into a dict (location - regex)
      # The location of the runs - multiple locations can be specified
      parent_runs_location:
        - "/Users/tweber/Data/mosaicatcher-pipeline"

      # Regular expression to match the runs
      runs_regex: ".*"

    # Data collections that are associated with the workflow
    data_collections:
      # The tag that is used to identify the data collection
      - data_collection_tag: "mosaicatcher_stats"

        # A description of the data collection
        description: "Statistics file generated by MosaiCatcher"

        # The configuration of the data collection
        config:
          # The type of the data collection (options: Table, JBrowse2)
          type: "Table"

          # A regular expression that is used to match the files specific of the data collection
          files_regex: ".*.info_raw"

          # The specific properties of the data collection - is related to the type of the data collection (Table here)
          dc_specific_properties:
            # The format of the data collection
            format: "TSV"

            # The configuration of the Polars DataFrame for the data collection
            polars_kwargs:
              skip_rows: 13
              separator: "\t"
              # Other options for polars_kwargs:
              # - column_types
              # - column_names
              # ...

            # The columns that are kept in the table - all other columns are dropped
            keep_columns:
              - "sample"
              - "cell"
              - "mapped"
              - "dupl"
              - "pass1"
              - "good"

            # TODO: FIX BUG ABOUT OBJECTID
            # Allow to join the data collections - used for table join
            table_join:
              # The columns that are used to join the data collections
              on_columns:
                - "sample"
                - "cell"
              # The type of join that is used to join the data collections
              how: "inner"
              # The list of data collections that are used to join the data collection
              with_dc:
                - "ashleys_labels"

      # Other data collections of type Table
      - data_collection_tag: "ashleys_labels"
        description: "Probabilities generated by ashleys-qc model"
        config:
          type: "Table"
          files_regex: "labels.tsv"
          dc_specific_properties:
            format: "TSV"
            polars_kwargs:
              separator: "\t"

      # Data collections of type JBrowse2
      - data_collection_tag: "SV_calls"

        # A description of the data collection
        description: "BED files containing SV calls generated by MosaiCatcher"

        # The configuration of the data collection
        config:
          # The type of the data collection
          type: "JBrowse2"

          # A regular expression that is used to match the files specific of the data collection
          files_regex: "{cell}-SV.bed.gz"

          # The specific properties of the data collection - is related to the type of the data collection (JBrowse2 here)
          dc_specific_properties:
            # A list of wildcards that are used to match the files in the data collection - used for regex matching based on file name - must correspond to the regex in files_regex
            regex_wildcards:
              # The name/ID of the wildcard
              - name: "cell"
                # The regular expression that is used to match the wildcard
                regex: ".*"

                # The tag defined of the data collection that is used to join the data collection
                join_data_collection: "mosaicatcher_stats"

          # File format of the files in the data collection
          format: "BED"

          # The extension of the index file for the data collection
          index_extension: "tbi"

          # The location of the JBrowse template for the data collection
          jbrowse_template_location: "/Users/tweber/Gits/depictio/CLI_client/configs/mosaicatcher_pipeline/jbrowse2_templates/SV_calls.json"
