/* depictio-rose — generated by shared/depictio-rose/build.py, do not edit by hand.
   Sources: rose.js (geometry and variants) + element.js (<depictio-rose>). */
/* Depictio rose: the logo as an animated polar-area chart.
   Shared by the deck's title slide (index.qmd) and the animation lab (anim_lab.html).

   Each wedge is a full circle clipped to its 45° sector, so any radius stays a true
   arc around the centre and the white gaps keep a constant width. At equal radii the
   8 wedges form a perfect disc. Radii are animated as scale() of that circle with the
   Web Animations API; the bounce is a damped spring sampled into a CSS linear() easing. */
(function (root) {
  const NS = 'http://www.w3.org/2000/svg';
  const COLORS = ['#7F5FEE', '#627BF2', '#F09745', '#F3C647', '#A2D64E', '#59B5CC', '#DE6E94', '#BE63E2'];
  const RADII = [1, .72, .72, .38, .72, 1, .44, .72];   // logo radius of each wedge, clockwise from 12 o'clock
  const GAP = 7.7;                                      // half the white gap between wedges, in viewBox units
  const R = 300;
  const INOUT = 'cubic-bezier(.45, 0, .55, 1)';
  const IN = 'cubic-bezier(.55, 0, .8, .25)';
  const OUT = 'cubic-bezier(.2, .7, .3, 1)';

  // Damped spring x(t) = 1 - e^(-ζt)(cos ω't + ζ/ω' sin ω't), sampled into linear().
  function spring(zeta) {
    const n = 64, T = Math.max(7, 5 / zeta), wd = Math.sqrt(1 - zeta * zeta), pts = [];
    for (let k = 0; k <= n; k++) {
      const t = T * k / n;
      pts.push((1 - Math.exp(-zeta * t) * (Math.cos(wd * t) + zeta / wd * Math.sin(wd * t))).toFixed(4));
    }
    pts[n] = '1';
    return 'linear(' + pts.join(', ') + ')';
  }

  function build(svg, uid) {
    svg.setAttribute('viewBox', '-320 -320 640 640');
    while (svg.firstChild) svg.removeChild(svg.firstChild);
    const defs = document.createElementNS(NS, 'defs');
    svg.appendChild(defs);
    const u = a => [Math.sin(a), -Math.cos(a)];
    const L = 480, apex = GAP / Math.sin(Math.PI / 8);
    const wedges = COLORS.map((color, i) => {
      const a1 = i * Math.PI / 4, a2 = a1 + Math.PI / 4, am = a1 + Math.PI / 8;
      const n1 = u(a1 + Math.PI / 2), n2 = u(a2 - Math.PI / 2);
      const pts = [
        u(am).map(v => v * apex),
        u(a1).map((v, k) => v * L + n1[k] * GAP),
        u(am).map(v => v * L * 1.3),
        u(a2).map((v, k) => v * L + n2[k] * GAP),
      ];
      const clip = document.createElementNS(NS, 'clipPath');
      clip.id = uid + '-s' + i;
      const poly = document.createElementNS(NS, 'polygon');
      poly.setAttribute('points', pts.map(p => p.map(v => v.toFixed(2)).join(',')).join(' '));
      clip.appendChild(poly);
      defs.appendChild(clip);
      const g = document.createElementNS(NS, 'g');
      g.setAttribute('clip-path', 'url(#' + clip.id + ')');
      const c = document.createElementNS(NS, 'circle');
      c.setAttribute('r', R);
      c.setAttribute('fill', color);
      c.style.transformBox = 'view-box';
      c.style.transformOrigin = '0 0';
      c.style.transform = 'scale(' + RADII[i] + ')';
      g.appendChild(c);
      // The sector and its clip live inside a rotation group, so a variant can swing
      // a whole wedge around the centre (the fan) while its radius is animated.
      const rot = document.createElementNS(NS, 'g');
      rot.style.transformBox = 'view-box';
      rot.style.transformOrigin = '0 0';
      rot.appendChild(g);
      c.rot = rot;
      return c;
    });
    // Painted last wedge first, so the first one is on top: folded, the fan shows a
    // single blade, and a blade still travelling slides under the ones already landed.
    // Sectors never overlap in the open states, so this changes nothing there.
    for (let i = COLORS.length - 1; i >= 0; i--) svg.appendChild(wedges[i].rot);
    return wedges;
  }

  // Shared opening: disc, then each wedge springs to its logo radius, clockwise.
  function opening(i, p) {
    const lead = .3 * p.S, st = .09 * p.S, sp = 1.1 * p.S, end = lead + 7 * st + sp;
    return {
      end,
      anim: { once: true, P: end, events: [
        { t: 0, s: p.disc }, { t: lead + i * st, s: p.disc, e: p.spr },
        { t: lead + i * st + sp, s: RADII[i] }, { t: end, s: RADII[i] }] },
    };
  }

  const A = [.78, .95, .55, .62, .95, .70, .78, .60];
  const B = [.92, .60, .92, .50, .62, .95, .58, .92];

  const VARIANTS = {
    // Opens clockwise with a spring, holds, closes all at once. Reset = back + lead.
    spring: {
      reset: p => .8 * p.S,
      plan(i, p) {
        const lead = .3 * p.S, st = .09 * p.S, sp = 1.1 * p.S, back = .5 * p.S;
        const t1 = lead + i * st, t3 = lead + 7 * st + sp + p.hold, P = t3 + back;
        return [{ P, events: [
          { t: 0, s: p.disc }, { t: t1, s: p.disc, e: p.spr }, { t: t1 + sp, s: RADII[i] },
          { t: t3, s: RADII[i], e: INOUT }, { t: P, s: p.disc }] }];
      },
    },
    // Snappier: stronger bounce, and the disc closes clockwise too.
    domino: {
      reset: p => .55 * p.S,
      plan(i, p) {
        const st = .06 * p.S, sp = .9 * p.S, back = .4 * p.S, gap = .15 * p.S;
        const spr = spring(Math.max(.2, p.zeta - .15)), P = sp + p.hold + back + gap;
        return [{ P, delay: .2 * p.S + i * st, events: [
          { t: 0, s: p.disc, e: spr }, { t: sp, s: RADII[i] },
          { t: sp + p.hold, s: RADII[i], e: IN }, { t: sp + p.hold + back, s: p.disc }, { t: P, s: p.disc }] }];
      },
    },
    // Endless clockwise wave: each wedge closes just before its turn, then springs back.
    sweep: {
      reset: () => 0,
      plan(i, p) {
        const sp = 1 * p.S, c = .3 * p.S, P = Math.max(sp + c + .2, 2.2 * p.S + p.hold);
        return [{ P, delay: .2 * p.S + i * P / 8, events: [
          { t: 0, s: p.disc, e: p.spr }, { t: sp, s: RADII[i] },
          { t: P - c, s: RADII[i], e: IN }, { t: P, s: p.disc }] }];
      },
    },
    // Opens once, then a small pulse runs clockwise around the logo.
    pulse: {
      reset: () => 0,
      plan(i, p) {
        const o = opening(i, p), bump = .16 * p.S, settle = .7 * p.S, P = 1.2 * p.S + p.hold;
        return [o.anim, { P, fill: 'none', delay: o.end + .5 * p.hold + i * .07 * p.S, events: [
          { t: 0, s: RADII[i], e: OUT }, { t: bump, s: RADII[i] * 1.07, e: p.spr },
          { t: bump + settle, s: RADII[i] }, { t: P, s: RADII[i] }] }];
      },
    },
    // Opens once, then the radii change like a chart refreshing, and come back to the logo.
    live: {
      reset: () => 0,
      plan(i, p) {
        const o = opening(i, p), tr = .9 * p.S, h = Math.max(.3, .5 * p.hold), P = 3 * tr + 2 * h + p.hold;
        return [o.anim, { P, fill: 'none', delay: o.end + .5 * p.hold + i * .05 * p.S, events: [
          { t: 0, s: RADII[i], e: p.spr }, { t: tr, s: A[i] },
          { t: tr + h, s: A[i], e: p.spr }, { t: 2 * tr + h, s: B[i] },
          { t: 2 * tr + 2 * h, s: B[i], e: p.spr }, { t: 3 * tr + 2 * h, s: RADII[i] }, { t: P, s: RADII[i] }] }];
      },
    },
  };

  // Variante 3 puis 5: opening, one clockwise sweep, then the live loop rolling clockwise.
  VARIANTS.wave = {
    reset: () => 0,
    plan(i, p) {
      const o = opening(i, p);
      const stw = .13 * p.S, dip = .26 * p.S, back = .85 * p.S;
      const sweepEnd = o.end + 7 * stw + dip + back;
      const tr = .9 * p.S, h = Math.max(.3, .5 * p.hold), P = 3 * tr + 2 * h + p.hold;
      return [
        o.anim,
        { P: dip + back, fill: 'none', once: true, delay: o.end + i * stw, events: [
          { t: 0, s: RADII[i], e: IN }, { t: dip, s: p.disc, e: p.spr },
          { t: dip + back, s: RADII[i] }] },
        { P, fill: 'none', delay: sweepEnd + .2 * p.S + i * .11 * p.S, events: [
          { t: 0, s: RADII[i], e: p.spr }, { t: tr, s: A[i] },
          { t: tr + h, s: A[i], e: p.spr }, { t: 2 * tr + h, s: B[i] },
          { t: 2 * tr + 2 * h, s: B[i], e: p.spr }, { t: 3 * tr + 2 * h, s: RADII[i] },
          { t: P, s: RADII[i] }] },
      ];
    },
  };

  // Endless data loop, no opening: the mark never rests, so it reads as "busy".
  // This is the one to use as a loading indicator.
  VARIANTS.loading = {
    reset: () => 0,
    plan(i, p) {
      const tr = .75 * p.S, h = Math.max(.15, .35 * p.hold), P = 3 * tr + 3 * h;
      return [{ P, delay: i * .12 * p.S, events: [
        { t: 0, s: RADII[i], e: p.spr }, { t: tr, s: A[i] },
        { t: tr + h, s: A[i], e: p.spr }, { t: 2 * tr + h, s: B[i] },
        { t: 2 * tr + 2 * h, s: B[i], e: p.spr }, { t: 3 * tr + 2 * h, s: RADII[i] },
        { t: P, s: RADII[i] }] }];
    },
  };

  // Fan: the eight blades start folded on the first wedge, at one o'clock, all at the
  // same radius. They open like a hand fan into a perfect disc, the disc springs into
  // the logo clockwise, one sweep, the data loop, back to the disc, and the fan folds
  // the other way round before starting again.
  VARIANTS.fan = {
    reset: () => 0,
    plan(i, p) {
      const S = p.S, h = Math.max(.3, .35 * p.hold);
      // The fan turns at ONE angular speed: a blade's travel time is proportional to
      // the angle it covers, so the eight blades keep an even gap and never overtake
      // each other. Each lands with a small bounce of its own, the same for all.
      const shut = .35 * S, openAll = 2 * S, closeAll = 1.5 * S;
      const kick = .1 * S, settleT = .3 * S, settle = kick + settleT;
      const soft = spring(Math.min(.8, p.zeta + .3));
      const mo = .08 * S, sp = 1 * S, bk = .7 * S;          // disc to logo, and back
      const sw = .13 * S, dip = .26 * S, back = .85 * S;    // the sweep
      const tr = .8 * S, ls = .05 * S;                      // the data loop
      const morph0 = shut + openAll + settle + .35 * p.hold;   // the disc holds before it opens up
      const sweep0 = morph0 + 7 * mo + sp + .25 * p.hold;
      const live0 = sweep0 + 7 * sw + dip + back + .15 * S;
      const back0 = live0 + 7 * ls + 3 * tr + 2 * h + .25 * p.hold;
      const close0 = back0 + 7 * mo + bk + .2 * p.hold;
      const P = close0 + closeAll + .35 * S;
      const a = -i * 45, t1 = live0 + i * ls;
      const land = shut + openAll * i / 7;          // same speed for every blade
      const leave = close0 + closeAll * (7 - i) / 7;
      const rot = i === 0 ? [{ t: 0, r: 0 }, { t: P, r: 0 }] : [
        { t: 0, r: a },
        { t: shut, r: a },                           // linear travel: the gaps stay even
        { t: land, r: 0, e: OUT },
        { t: land + kick, r: 4.5, e: soft },         // a light bounce, identical on each blade
        { t: land + settle, r: 0 },
        { t: leave, r: 0 },
        { t: close0 + closeAll, r: a },
        { t: P, r: a },
      ];
      return [{
        P,
        events: [
          { t: 0, s: p.disc },
          { t: morph0 + i * mo, s: p.disc, e: p.spr },
          { t: morph0 + i * mo + sp, s: RADII[i] },
          { t: sweep0 + i * sw, s: RADII[i], e: IN },
          { t: sweep0 + i * sw + dip, s: p.disc, e: p.spr },
          { t: sweep0 + i * sw + dip + back, s: RADII[i] },
          { t: t1, s: RADII[i], e: p.spr },
          { t: t1 + tr, s: A[i] },
          { t: t1 + tr + h, s: A[i], e: p.spr },
          { t: t1 + 2 * tr + h, s: B[i] },
          { t: t1 + 2 * tr + 2 * h, s: B[i], e: p.spr },
          { t: t1 + 3 * tr + 2 * h, s: RADII[i] },
          { t: back0 + i * mo, s: RADII[i], e: INOUT },
          { t: back0 + i * mo + bk, s: p.disc },
          { t: P, s: p.disc },
        ],
        rot,
      }];
    },
  };

  function keyframes(events, P, key) {
    return events.map(e => ({
      offset: Math.min(1, Math.max(0, e.t / P)),
      transform: key === 'r' ? 'rotate(' + e.r.toFixed(2) + 'deg)' : 'scale(' + e.s.toFixed(4) + ')',
      easing: e.e || 'linear',
    }));
  }

  function params(opts) {
    const p = Object.assign({ speed: 1, hold: 2, zeta: .5, disc: .62 }, opts || {});
    p.S = 1 / p.speed;
    p.spr = spring(p.zeta);
    return p;
  }

  function play(wedges, variant, opts) {
    const p = params(opts), v = VARIANTS[variant] || VARIANTS.spring;
    wedges.forEach((w, i) => {
      w.getAnimations().forEach(a => a.cancel());
      if (w.rot) {
        w.rot.getAnimations().forEach(a => a.cancel());
        w.rot.style.transform = 'rotate(0deg)';   // only the fan leaves this anywhere else
      }
      v.plan(i, p).forEach(a => {
        const opt = {
          duration: a.P * 1000,
          delay: (a.delay || 0) * 1000,
          iterations: a.once ? 1 : Infinity,
          fill: a.fill || 'both',
        };
        w.animate(keyframes(a.events, a.P), opt);
        if (a.rot && w.rot) w.rot.animate(keyframes(a.rot, a.P, 'r'), opt);
      });
    });
  }

  root.DepictioRose = { COLORS, RADII, VARIANTS, spring, build, play, params };
})(window);

/* <depictio-rose> — the Depictio mark as a self-drawing, dependency-free custom element.

   <depictio-rose size="64" mode="loading"></depictio-rose>

   Attributes (all optional, all live):
     mode    loading | fan | intro | live | sweep | logo   default loading
     size    px, the side of the square                default 64
     speed   playback multiplier                       default 1
     hold    seconds the mark rests on the logo shape  default 1.2
     bounce  soft | medium | strong, or a damping 0.2 to 1   default strong
     disc    radius of the closed disc, 0.45 to 0.85   default 0.62
     paused  present = frozen on the logo shape
     motion  auto (honours prefers-reduced-motion) | always   default auto
     label   accessible name; empty string = decorative

   Nothing is fetched: the mark is drawn from the geometry in this file, so it
   cannot 404 on a path change and it costs no request. */
(function (root) {
  const R = root.DepictioRose;
  if (!R || !root.customElements || customElements.get('depictio-rose')) return;

  const BOUNCE = { soft: .7, medium: .5, strong: .35 };
  const NUM = (v, d) => (v === null || v === '' || isNaN(parseFloat(v)) ? d : parseFloat(v));
  let uid = 0;

  class DepictioRose extends HTMLElement {
    static get observedAttributes() {
      return ['mode', 'size', 'speed', 'hold', 'bounce', 'disc', 'paused', 'motion', 'label'];
    }

    constructor() {
      super();
      const shadow = this.attachShadow({ mode: 'open' });
      shadow.innerHTML =
        '<style>' +
        ':host{display:inline-block;line-height:0;contain:content}' +
        'svg{width:100%;height:100%;overflow:visible;display:block}' +
        ':host([data-still]) svg{animation:dpr-breathe 1.6s ease-in-out infinite}' +
        '@keyframes dpr-breathe{0%,100%{opacity:1}50%{opacity:.55}}' +
        '</style><svg aria-hidden="true"></svg>';
      this._svg = shadow.querySelector('svg');
      this._wedges = R.build(this._svg, 'dpr' + (uid++));
      this._mq = root.matchMedia ? root.matchMedia('(prefers-reduced-motion: reduce)') : null;
      this._onMq = () => this._apply();
      this._onVis = () => this._setRunning(!document.hidden && this._visible);
      this._visible = true;
      if (root.IntersectionObserver) {
        this._io = new IntersectionObserver(es => {
          this._visible = es[es.length - 1].isIntersecting;
          this._onVis();
        });
      }
    }

    connectedCallback() {
      if (this._io) this._io.observe(this);
      if (this._mq) (this._mq.addEventListener || this._mq.addListener).call(this._mq, 'change', this._onMq);
      document.addEventListener('visibilitychange', this._onVis);
      this._apply();
    }

    disconnectedCallback() {
      if (this._io) this._io.disconnect();
      if (this._mq) (this._mq.removeEventListener || this._mq.removeListener).call(this._mq, 'change', this._onMq);
      document.removeEventListener('visibilitychange', this._onVis);
      this._stop();
    }

    attributeChangedCallback() { if (this.isConnected) this._apply(); }

    /** Restart the animation from its first frame. */
    replay() { this._apply(); }

    get params() {
      const b = this.getAttribute('bounce');
      return {
        speed: NUM(this.getAttribute('speed'), 1),
        hold: NUM(this.getAttribute('hold'), 1.2),
        zeta: BOUNCE[b] || NUM(b, .35),
        disc: NUM(this.getAttribute('disc'), .62),
      };
    }

    // The fan swings a wedge's rotation group as well as its radius, so both stop together.
    _anims(w) { return w.getAnimations().concat(w.rot ? w.rot.getAnimations() : []); }

    _stop() {
      this._wedges.forEach(w => {
        this._anims(w).forEach(a => a.cancel());
        if (w.rot) w.rot.style.transform = 'rotate(0deg)';
      });
    }

    _setRunning(on) {
      this._wedges.forEach(w => this._anims(w).forEach(a => {
        try { on ? a.play() : a.pause(); } catch (e) { /* not yet ready */ }
      }));
    }

    _apply() {
      // With no size attribute the host keeps whatever the page's CSS gives it.
      const size = this.getAttribute('size');
      if (size !== null) {
        const px = NUM(size, 64) + 'px';
        this.style.width = px;
        this.style.height = px;
      }

      const label = this.getAttribute('label');
      const mode = this.getAttribute('mode') || 'loading';
      const name = label === null ? (mode === 'loading' ? 'Loading' : '') : label;
      if (name) { this.setAttribute('role', 'status'); this.setAttribute('aria-label', name); }
      else { this.removeAttribute('role'); this.setAttribute('aria-hidden', 'true'); }

      const reduce = this._mq && this._mq.matches && this.getAttribute('motion') !== 'always';
      const still = mode === 'logo' || reduce;
      this.toggleAttribute('data-still', !!(still && mode === 'loading'));
      this._stop();
      if (still) {
        this._wedges.forEach((w, i) => { w.style.transform = 'scale(' + R.RADII[i] + ')'; });
        return;
      }
      R.play(this._wedges, R.VARIANTS[mode] ? mode : 'loading', this.params);
      if (this.hasAttribute('paused') || document.hidden || !this._visible) this._setRunning(false);
    }
  }

  customElements.define('depictio-rose', DepictioRose);
  R.Element = DepictioRose;
})(window);
