# Minikube-specific values overlay (values-minikube.yaml)

# Storage class for Minikube
storageClass: "standard"
# Storage class for Rancher Desktop
# storageClass: "local-path"
# persistence:
#   mongo:
#     size: 1Gi
#     accessMode: ReadWriteOnce
#   minio:
#     size: 1Gi
#     accessMode: ReadWriteOnce
#   screenshots:
#     size: 100Mi
#     accessMode: ReadWriteOnce
#   keys:
#     size: 1Mi
#     accessMode: ReadWriteOnce



# Ingress configuration for Minikube
ingress:
  enabled: false
  ingressClassName: null
  annotations: {}

global:
  domain: null

backend:
  env:
    DEPICTIO_MONGODB_WIPE: "true"

local_development:
  false # Set to true for local development


  # # Host configuration for local access with minikube tunnel
  # hosts:
  #   - host: "depictio.local"
  #     paths:
  #       - path: /
  #         pathType: Prefix
  #         service:
  #           name: depictio-frontend
  #           port: 80
  #       - path: /api
  #         pathType: Prefix
  #         service:
  #           name: depictio-backend
  #           port: 80

  # No TLS for local development
  # tls: []
# Resource adjustments for local development
# mongo:
#   resources:
#     requests:
#       memory: "256Mi"
#       cpu: "0.1"
#     limits:
#       memory: "512Mi"
#       cpu: "0.5"

# minio:
#   resources:
#     requests:
#       memory: "256Mi"
#       cpu: "0.1"
#     limits:
#       memory: "512Mi"
#       cpu: "0.5"

# backend:
#   resources:
#     requests:
#       memory: "256Mi"
#       cpu: "0.1"
#     limits:
#       memory: "512Mi"
#       cpu: "0.5"

# frontend:
#   resources:
#     requests:
#       memory: "256Mi"
#       cpu: "0.1"
#     limits:
#       memory: "512Mi"
#       cpu: "0.5"
