# Disable ingress for testing
ingress:
  enabled: false

# Use standard storage class for Minikube
storageClass: "standard"

# Test environment resource settings
mongo:
  resources:
    requests:
      memory: "256Mi"
      cpu: "0.1"
    limits:
      memory: "2Gi"
      cpu: "1"

minio:
  resources:
    requests:
      memory: "256Mi"
      cpu: "0.1"
    limits:
      memory: "2Gi"
      cpu: "1"

backend:
  resources:
    requests:
      memory: "256Mi"
      cpu: "0.1"
    limits:
      memory: "2Gi"
      cpu: "1"
  env:
    DEPICTIO_LOGGING_VERBOSITY_LEVEL: "DEBUG"

frontend:
  resources:
    requests:
      memory: "256Mi"
      cpu: "0.1"
    limits:
      memory: "2Gi"
      cpu: "1"

# Use small PVC sizes for testing
persistence:
  mongo:
    size: 1Gi
  minio:
    size: 1Gi
  screenshots:
    size: 100Mi
  keys:
    size: 1Mi

local_development: false # Set to true for local development
