name: ARM64 Docker Image Build

on:
  push:
    tags:
      - "v[0-9]*.[0-9]*.[0-9]*"  # Only build ARM for stable releases
      # Exclude beta tags for ARM builds to save time
      - "v[0-9]*.[0-9]*.[0-9]*-beta*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-arm64:
    # Use native ARM runner
    runs-on: ubuntu-22.04-arm64
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: version
        run: |
          # Extract the git tag (v0.0.4)
          GIT_TAG=${GITHUB_REF#refs/tags/}
          # Clean version number (without v prefix)
          CLEAN_VERSION=${GIT_TAG#v}
          echo "VERSION=$CLEAN_VERSION" >> $GITHUB_OUTPUT

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:latest

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # Version with architecture suffix
            type=raw,value=${{ steps.version.outputs.VERSION }}-arm64
            
            # Tag as stable with architecture
            type=raw,value=stable-arm64
            
            # Tag as latest with architecture
            type=raw,value=latest-arm64

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker-images/Dockerfile_depictio.dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # No need to specify platform when running on native hardware
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache-arm64
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache-arm64,mode=max