name: Build container

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug
      # tags:
      #   description: "Test scenario tags"
      #   required: false
      #   type: boolean
      # environment:
      #   description: "Environment to run tests against"
      #   type: environment
      #   required: true
  push: 
    branches: "232-gh-actions-initial-setup"

jobs:
  build_and_push_depictio:
    name: Build and Push Depictio Image
    runs-on: ubuntu-latest
    env:
      REGISTRY_URL: registry.git.embl.de/tweber  # Updated to use the correct namespace based on your instructions.

    steps:
      - uses: actions/checkout@v3

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Build and Push Depictio Image
      - name: Build and Push Depictio Image
        run: |
          docker build -t ${{ env.REGISTRY_URL }}/depictio -f docker-images/Dockerfile_depictio.dockerfile .
          docker push ${{ env.REGISTRY_URL }}/depictio

  build_and_push_jbrowse2:
    name: Build and Push JBrowse2 Image
    runs-on: ubuntu-latest
    env:
      REGISTRY_URL: registry.git.embl.de/tweber  # Updated to use the correct namespace based on your instructions.

    steps:
      - uses: actions/checkout@v3

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}


      # Build and Push JBrowse2 Image
      - name: Build and Push JBrowse2 Image
        run: |
          docker build -t ${{ env.REGISTRY_URL }}/jbrowse2 -f docker-images/Dockerfile_jbrowse.dev.240424.dockerfile .
          docker push ${{ env.REGISTRY_URL }}/jbrowse2

      - name: Verify Pushed Images
        run: echo "Images have been successfully pushed to ${{ env.REGISTRY_URL }}"
